-- Migration: seed the exercise library from wger (part 3 of 7)
--
-- GENERATED by scripts/build-exercise-seed.mjs — do not hand-edit. Re-run the
-- script to regenerate.
--
-- Source: https://wger.de (open exercise database, fetched via its public API)
-- Licences present: CC-BY-SA 4, CC0, CC-BY-SA 3
-- Each row carries its own license and license_author, which must be honoured
-- wherever its description or image is displayed. CC-BY-SA in particular
-- requires attribution and share-alike on the text.
--
-- NOT sourced from ExRx.net: that content is copyrighted and the site refuses
-- automated access. Its taxonomy — browse by body part, narrow by equipment —
-- is a structure rather than an expression, and is what this follows.
--
-- Split into 7 parts because the Supabase SQL editor truncates a
-- very large paste, and a cut inside a description leaves an unterminated
-- string literal. Run the parts in order; each is independent and re-runnable.
-- This part: 120 exercises.
--
-- Exercises kept: 722 of 863 fetched
-- With a description: 700 · with an image: 232 · with a video: 45
-- By category: Legs 166, Back 128, Arms 121, Abs 102, Shoulders 90, Chest 75, Cardio 31, Calves 9
-- Skipped 128: no primary muscle
-- Skipped 13: no usable name
--
-- pattern and unilateral are INFERRED from the exercise name, because wger
-- records neither. Both feed real maths — §4.3 picks the load increment from
-- pattern, §4.4 totals volume by it, and §4.1 keeps unilateral sets out of
-- bilateral PR comparisons — so check the ones you actually train. They are
-- heuristics over names, not facts from the source.
-- Inferred unilateral: 42

insert into public.exercises
  (name, pattern, unilateral, lower_body, compound,
   category, primary_muscles, secondary_muscles, equipment,
   description, image_url, video_url, source, source_id, license, license_author)
values
  ('Trx Single Arm Bicep Curl', 'isolation', true, false, true, 'Arms', '{"Biceps","Brachialis"}', '{"Shoulders","Trapezius"}', '{}', 'Step 1: Stand comfortably and grasp the handles of the suspension system. Step 2: Lean back resting your weight on one arm, keepng the spine neutral. Step 3: Slowly curl to pull your body weight to the up position. Supinate the arm and squeeze as you approach the end position. Step 4: Lower yourself back down and repeat.', null, null, 'wger', '7f2628bf-6381-4228-9840-b75cbcc843a1', 'CC-BY-SA 4', 'cynomops'),
  ('TRX Tricep Extension', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{}', 'Attach the TRX or other suspension system overhead, having the handles hanging at chest level or slightly lower. Experiment to see what height allows you to set up in the best way.
Stand in front of the handles and grab them with your palms facing down.
Engage your abs, squeeze your glutes, take a breath and lean forward, lifting your heels off the floor. Keep your elbows straight.
Take another breath and lower yourself slowly by bending your elbows.
Go down until your elbows are at a 90-degree angle (to the point where your wrists are above your elbows). Hold the position for a moment.
Extend your arms by engaging your triceps and bring yourself to the starting position as you exhale.', null, null, 'wger', 'de8a3db6-2b05-4c4e-977b-b61342718356', 'CC-BY-SA 4', 'cynomops'),
  ('TRX dips', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{"Chest"}', '{}', 'Start with the hands on the suspension trainer and feet on the ground.
Your hands should be under your shoulders with the feet slightly in front.
Lower yourself by bringing the hips between the handles and flexing the elbows.
Extend the elbows to come back to the starting position and repeat.', null, null, 'wger', '8019be2c-47a3-475f-8e16-a2fca761a8fe', 'CC-BY-SA 4', 'cynomops'),
  ('Pullover', 'pull_h', false, false, false, 'Back', '{"Chest"}', '{"Lats"}', '{"Dumbbell"}', 'Doubling as a back and chest exercise, the Dumbbell Pullover can train both your pecs and lats.', null, null, 'wger', '9ccd53e0-8392-4e61-91aa-e4e5f4ea339c', 'CC-BY-SA 4', '3leh'),
  ('Biceps Close Grip Pull Down', 'pull_v', false, false, true, 'Arms', '{"Biceps"}', '{"Shoulders","Lats"}', '{}', 'On a lat pull down machine, hold the bar keeping your hands relatively close. Use an underhand grip (I.E.: the back of your hand must be facing the machine). Then pull down the bar in a straight line towards the ground. Make sure your biceps are the main drivers of the motion. You will probably feel your shoulders and lats working, but make sure your biceps are working more.', null, null, 'wger', '8bb42000-834f-48ab-af5c-0c31d94e0181', 'CC-BY-SA 4', 'daniel.escada'),
  ('Isometria trazioni impugnatura inversa', 'pull_h', false, false, true, 'Back', '{"Lats"}', '{"Biceps","Trapezius"}', '{"Pull-up bar"}', 'Trazioni in isometria con impugnatura inversa', null, null, 'wger', '5fd01c23-6c54-40cb-9a67-87c7a325baee', 'CC-BY-SA 4', 'clafal'),
  ('Incline Chest-Supported Dumbbell Row', 'pull_h', false, false, true, 'Back', '{"Biceps","Lats","Trapezius"}', '{}', '{"Bench","Dumbbell"}', 'Set up an adjustable bench at a 45-degree angle.
Lay on your stomach with your head hanging just above the edge of the bench.
Grab a dumbbell in each hand and set up with a good posture – core and lats engaged and shoulders neutral.
Row the dumbbells toward the top of the stomach and squeeze the back at the top of the rep.
Finally, lower the dumbbells back to the starting position and repeat until all reps are completed.', 'https://wger.de/media/exercise-images/1283/e7262f70-7512-408a-8d00-4c499ef632fc.jpg', null, 'wger', '51a2d520-b510-4b6e-bd65-9fc40365e8de', 'CC-BY-SA 4', 'carlos3c'),
  ('Pseudo Planche Push-up', 'push_h', false, false, false, 'Shoulders', '{"Shoulders"}', '{"Chest"}', '{"Bodyweight"}', 'You should have the shoulder line in front of your wrists an perform a push-up, maintaining the shoulder in the same position', null, null, 'wger', 'c38b0f69-7f01-4f0f-82cc-e33cdc658f9e', 'CC-BY-SA 4', 'vdrb'),
  ('Talons fesses', null, false, false, false, 'Cardio', '{"Calves"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Touch your heels to your buttocks, while remaining static or moving', 'https://wger.de/media/exercise-images/1285/1ab8005d-41e4-4505-9a7d-5277d59bb3cd.jpg', null, 'wger', '42657bd4-bf4e-4429-8e6a-2f5f585aa22a', 'CC-BY-SA 4', 'painDpice'),
  ('Dynamic Planche', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{"Bodyweight"}', 'Start in a plank position, with your hands directly under your shoulders and your feet hip-width apart.
Engage your core to keep your body in a straight line from head to toe.
From this position, bend your knees slightly and jump with both feet inward, bringing them as close to your core as possible
As soon as your feet touch the ground, push off forcefully to jump again and return to the starting plank position.
Continue repeating this jumping motion, maintaining control and core stability throughout the exercise.
Make sure to keep your breathing steady while jumping, breathing deeply and controlling your breathing.
Keep your gaze fixed on the ground to maintain proper spinal alignment.
Repeat the jumps for the desired length of time or the number of repetitions recommended for your workout program.
To finish the exercise, rest by releasing the plank position, then stretch if necessary to loosen your muscles.', null, null, 'wger', '73dbe7a5-e8f3-48fd-814e-bc3378c15be2', 'CC-BY-SA 4', 'painDpice'),
  ('Reach ups', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis"}', '{"Abs"}', '{"Bodyweight"}', 'To perform this exercise, lie on your back with your arms extended overhead. Then, contract your abdominals and lift your torso off the floor while reaching your arms toward the ceiling to "reach" as high as possible. Slowly return to the starting position, controlling the movement. Reach ups strengthen the abdominal muscles and improve the flexibility of the spine. They can be incorporated into a variety of training routines to work on core strength and stability.', null, null, 'wger', '6c21c09b-90c8-4e43-a43c-ed566f812784', 'CC-BY-SA 4', 'painDpice'),
  ('Dynamic side plank', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis"}', '{"Abs"}', '{"Bodyweight"}', 'The dynamic side plank involves positioning yourself on your side, supported on one elbow and the side of your foot, then dipping your hips up and down while keeping your body in a straight line.', null, null, 'wger', '81c6b9ef-7cb7-4328-8cb4-47ae8ecc42be', 'CC-BY-SA 4', 'painDpice'),
  ('Seated Dumbbell Curls', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{"Brachialis"}', '{"Dumbbell"}', 'Seated Dumbbell Curls are an effective bicep workout that isolates the muscles by stabilizing the upper body, reducing momentum that can detract from the exercise’s effectiveness. This exercise is performed sitting down with a dumbbell in each hand, focusing on controlled movement to maximize engagement of the bicep muscles.', null, null, 'wger', '19fba43a-8363-4da3-82c6-d8a14628b5e7', 'CC-BY-SA 4', 'sTiKyt'),
  ('Reverse Grip Barbell Curls', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{"Brachialis"}', '{"Barbell"}', 'Hold the barbell with an overhand grip (palms facing down) approximately shoulder-width apart. Ensure your back is straight, shoulders slightly pulled back, and arms fully extended.
Curl the barbell upwards towards your chest in a controlled motion, keeping your elbows close to your body. The motion should be smooth without any swinging or momentum use.
Once the barbell is at chest level, pause briefly to maximize contraction in the biceps and forearms.
Slowly lower the barbell back to the starting position with a controlled movement, fully extending your arms.', 'https://wger.de/media/exercise-images/1290/c05818bf-1c81-46df-9f24-42e354265388.png', null, 'wger', 'dd6e8753-a574-476e-900a-b794eb592e7b', 'CC-BY-SA 4', 'sTiKyt'),
  ('Reverse-grip pull-ups', 'isolation', false, false, true, 'Abs', '{"Biceps","Lats"}', '{"Abs"}', '{"Pull-up bar"}', 'Pull-ups on the bar with your thumbs pointing outward.', null, null, 'wger', '2acb5ba1-caa3-4204-9903-ff0095b032ba', 'CC-BY-SA 4', 'clafal'),
  ('One armed push-ups', 'isolation', false, false, true, 'Abs', '{"Chest","Triceps"}', '{"Shoulders","Abs"}', '{"Bodyweight"}', 'Perform push-ups with one hand, alternating the sides', null, null, 'wger', '8911c37d-8907-4077-b883-86a7c5fcb606', 'CC-BY-SA 4', 'clafal'),
  ('Cable Tri Extension - Internal Rotation', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Cable machine"}', 'single arm exercise with cable held at opposite shoulder with elbow bent. Turn towards the cable, and the straighten the elbow across the body.', null, null, 'wger', '07ded945-de5d-4e77-b13c-17d51a2f0007', 'CC-BY-SA 4', 'Shiladree'),
  ('Preacher Curl - Internally Rotated', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Dumbbell"}', 'Single arm curl that can be done using a dumbbell and a preacher bench, or a preacher curl machine. Turn body towards the weight', null, null, 'wger', '4baa4962-64bd-434f-b2ed-0c3c88099841', 'CC-BY-SA 4', 'Shiladree'),
  ('JM Press', 'isolation', false, false, true, 'Arms', '{"Triceps"}', '{"Biceps","Chest"}', '{"Barbell"}', 'The JM press keeps your shoulders stationary, relying on the elbow flexion and extension to move the weight using your triceps strength. That means you get all the benefits of the best triceps-strengthening exercises without overtaxing that delicate shoulder joint. Classic win-win!', null, null, 'wger', '67c2fe41-f1e9-4f75-b2cb-72d1f2e092f7', 'CC-BY-SA 4', 'Epiphany8424'),
  ('Helms Row', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{"Trapezius"}', '{"Dumbbell"}', 'Setup: Place your chest on the end of a bench, using a towel or anything soft to keep your chest protected. You want your chest to be in contact with the bench around the nipple line. Your back should be almost parallel to the floor
Execution: When you’re starting the exercise, focus on pulling your elbows back until you feel maximum tightness in the lats.
If you want to get some trap activation with the exercise, relax your shoulder blades when the weights are hanging down and then retract them as you start the rep.', null, null, 'wger', 'e781dae5-90b8-4105-8aa6-82d278ac5ff5', 'CC-BY-SA 4', 'carlos3c'),
  ('Meadows Row', 'pull_h', false, false, true, 'Back', '{"Lats","Trapezius"}', '{"Biceps","Abs"}', '{"Barbell"}', 'The Meadows row is a unilateral row performed with a landmine setup, overhand grip, and staggered stance. Lean your torso forward and grip the barbell. Rest the other forearm on the forward leg. Start this movement by driving the elbow behind you while retracting the shoulder-blade. Keep the working shoulder down. Pull toward your back hip until the elbow is level with your torso.', null, null, 'wger', '28b65190-cae2-4d15-8f4e-dde0d9cc4d4b', 'CC-BY-SA 4', 'carlos3c'),
  ('Front Plank', 'isolation', false, false, true, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis","Chest","Quads","Serratus anterior"}', '{"Bodyweight"}', 'The plank is a bodyweight exercise. As a multi-functional movement, the plank not only targets your abdominal muscles but also the spine and hip. Plank strengthens and tightens your entire body, improves your posture and balance, reduces body fat, and can help boost your metabolism.
Exercises such as the “plank pose” help strengthen the stamina of stabilizing abdominal muscles. It can also help relieve back pain associated with a weakening of the function of the stabilizing muscles of the body.
Planks are a versatile exercise that targets many of the most important muscle groups in the body, so they can be applied by anyone to improve endurance and overall body strength.', null, null, 'wger', 'dd9dcfd2-879f-422a-ad06-d2c187c58d1f', 'CC-BY-SA 4', 'hektkaso'),
  ('One Arm Overhead Cable Tricep Extension', 'isolation', true, false, false, 'Arms', '{"Triceps"}', '{}', '{"Cable machine"}', 'Set the pulley at the bottom of the cable machine and grab onto it without using any attachments. Extend the cable directly overhead.

While keeping your back straight and upper arm stationary, lower the cable behind your head until you feel a good stretch in your triceps, and then extend it back upward until your elbow is locked out.', null, null, 'wger', '5ed12527-c8be-4e86-8f2a-cf9dd4781f5b', 'CC-BY-SA 4', 'AlucardEvil40'),
  ('Recovery Bobbing', null, false, false, false, 'Cardio', '{"Abs"}', '{}', '{}', 'Same motion as the Bobbing Exhale Drill, but done in slightly deeper water (so you''re not touching the bottom) and at a slower, more relaxed pace — think of it as a recovery/reset exercise rather than a hard drill. Use it between harder drills to reset your breathing rhythm and calm down if you''re feeling rushed or out of sync.', null, null, 'wger', '6705ec92-c6c6-4b2c-b919-bddb8177bf98', 'CC-BY-SA 4', 'Imported from swim plan'),
  ('Curl - With Shoulder Elevated', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Dumbbell"}', 'Place elbow so that it is about level with the shoulder. Curl the wieght to your shoulder. Focus on the stretch in the eccentric part of the curl', null, null, 'wger', '9828f705-350b-4afd-86c4-fcc0e8a0fb4b', 'CC-BY-SA 4', 'Shiladree'),
  ('Single-leg hamstring curl', 'squat', true, true, false, 'Legs', '{"Hamstrings"}', '{"Glutes"}', '{"Bodyweight"}', 'Specifically, the muscles involved are: biceps femoris, semimembranosus and semitendinosus.', null, null, 'wger', 'caccd791-ff30-452a-816e-790edadb78cd', 'CC-BY-SA 4', 'clafal'),
  ('Jumping Jack HD', null, false, false, true, 'Cardio', '{"Quads"}', '{"Glutes","Obliquus externus abdominis","Abs"}', '{"Bodyweight"}', 'Jumping jack are a plyometric exercise. Plyometrics are explosive aerobic moves that increase speed, quickness, and power and they work your whole body.
Jumping jack target the arm, shoulder, abdominal muscles, hip muscles and hip flexors and also work on the thighs, knee tendons and quadriceps.
Jumps are beneficial to your health because they combine cardiovascular conditioning with strength work. Since jumps elevate your heart rate, they can also improve your cardiovascular fitness.', null, null, 'wger', '89443e49-e5be-4b67-a5f6-e3f5ff80f6ea', 'CC-BY-SA 4', 'hektkaso'),
  ('Dumbbell Hex Press', 'push_h', false, false, true, 'Chest', '{"Chest","Triceps"}', '{"Shoulders"}', '{"Dumbbell"}', 'Engage the muscles
Position your feet wide
Controlled movement
Slow movement
Bring the weights toward your lower chest/stomach', 'https://wger.de/media/exercise-images/1353/138cb483-7d4d-4519-b029-63e4269810a6.webp', null, 'wger', '587af8f1-516b-44c3-8660-70f262e1bef8', 'CC-BY-SA 4', 'Anastasious'),
  ('Single Leg RDL', 'hinge', true, true, false, 'Legs', '{"Hamstrings"}', '{"Glutes"}', '{"Bodyweight"}', 'Stand upright and hold weights in both hands if using loads.
Brace your core and lift one leg off the ground.
Keep your back straight, hinge at the hips while lowering your torso forward, ensuring you don’t rotate your hips.
Lower until you feel a stretch in your standing leg''s hamstring, then return to standing position. Repeat on both sides.', null, null, 'wger', '957ca37c-b6d7-4c30-8ba9-9512b0fa2659', 'CC-BY-SA 4', 'admin'),
  ('High Knee Skips HD', null, false, false, true, 'Cardio', '{"Obliquus externus abdominis","Abs"}', '{"Biceps","Glutes","Quads","Triceps"}', '{"Bodyweight"}', 'You can use this exercise both as a dynamic warm-up before training and add it to your cardio training routine to burn fat.
High knee skips are a plyometric exercise. Plyometrics are explosive aerobic moves that increase speed, quickness, and power and they work your whole body.
High knee skips target the oblique, leg muscles, hip muscles and hip flexors and also work on the thighs, knee tendons, quadriceps and shoulders.
Jumps are beneficial to your health because they combine cardiovascular conditioning with strength work. Since jumps elevate your heart rate, they can also improve your cardiovascular fitness.', null, null, 'wger', '32942c8c-0572-4d8b-9aec-48cb026fda1f', 'CC-BY-SA 4', 'hektkaso'),
  ('Bench Dips On Floor HD', 'push_h', false, false, true, 'Arms', '{"Biceps","Brachialis","Triceps"}', '{"Shoulders","Chest","Soleus","Trapezius"}', '{"Bodyweight"}', 'Triceps dips on floor are a compound exercise as they worked multiple muscle groups simultaneously. Although this bodyweight exercise mainly targets the triceps, it also hits your chest and front of your shoulder.
Triceps dips on floor are one of the most effective exercises to increase arm strength and also build lean muscle in your upper arms.
Triceps dips on floor are a closed kinetic chain exercise and express that you do the movements around a fixed point. It increases compression force on your joints thereby improving stability.', null, null, 'wger', 'fbeb1fd5-d259-4a85-a993-03569d8146dc', 'CC-BY-SA 4', 'hektkaso'),
  ('Dumbbell Split Squat', 'squat', true, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings","Calves"}', '{"Dumbbell"}', 'Controlled execution
No momentum
Execute slowly', null, null, 'wger', '8a3e08ab-4e97-4aee-897a-60d8693b9b43', 'CC-BY-SA 4', 'Anastasious'),
  ('Dumbbell Deadlift', 'hinge', false, true, true, 'Legs', '{"Hamstrings","Glutes"}', '{"Quads","Trapezius"}', '{"Dumbbell"}', 'Controlled execution
Don''t use momentum
Slow execution', null, null, 'wger', 'b199baca-7353-4dee-bbcf-620f96dba5b4', 'CC-BY-SA 4', 'Anastasious'),
  ('Bodyweight lunge HD', 'squat', true, true, true, 'Legs', '{"Quads"}', '{"Glutes","Soleus"}', '{"Bodyweight"}', 'Bodyweight lunges are an effective calisthenic exercise for
strengthening the lower body, improving balance and stability, and
developing functional strength. They are a popular choice for bodyweight workouts, home workouts, and can also be included as part of a larger strength training routine.', null, null, 'wger', 'f9a0a918-3c0c-464e-bbba-1bd309d4a519', 'CC-BY-SA 4', 'hektkaso'),
  ('Lateral Push Off', 'squat', false, true, false, 'Legs', '{"Calves"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Push off the ground and land on one leg and regain balance before jumping to the other leg', 'https://wger.de/media/exercise-images/1325/d8372291-6725-452a-9711-6321c061e354.jpg', null, 'wger', '45e44940-d4a0-4c66-8cbb-7afe785d5610', 'CC-BY-SA 4', 'cleen'),
  ('Low-Cable Cross-Over - NB', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Shoulders"}', '{"Cable machine"}', 'The low-cable cross-over is an isolation movement that uses a cable stack to target the upper portion of the pectoral muscles. It is common in upper-body and chest-focused muscle-building workouts, often in combination with presses or flyes from other angles to target all portions of the chest.', 'https://wger.de/media/exercise-images/1296/c42782fe-337a-44f4-9079-7f6dedab4885.png', null, 'wger', 'ac6e6a09-5175-4fea-9e56-e2ff3c00b0f2', 'CC-BY-SA 4', 'JackSparrow'),
  ('Leg Swings (Front–Back)', 'squat', false, true, true, 'Legs', '{"Hamstrings"}', '{"Glutes","Quads"}', '{"Bodyweight"}', 'Stand tall next to a wall or stable support. Swing one leg forward and backward in a controlled motion, keeping the torso upright and the core engaged. Alternate legs after completing the repetitions.', null, null, 'wger', '1fae7d45-0731-4640-8809-94c76b836571', 'CC-BY-SA 4', 'Jhonatan'),
  ('High-Cable Cross Tricep Extention - NB', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Cable machine"}', 'The high-cable cross tricep extension is an isolation exercise for targeting the triceps,
particularly the long head. It utilizes cables and handles grasped with opposite hands, allowing for a unique pressing motion that can be effective for building tricep strength. Unlike exercises that use a straight bar or rope, this variation can be more comfortable on your wrists and elbows', 'https://wger.de/media/exercise-images/1298/ec4b83ec-5a8f-4303-9050-99ec4389bc2a.png', null, 'wger', '4ef75e13-c058-4410-91c0-2f2d2df98130', 'CC-BY-SA 4', 'JackSparrow'),
  ('Seated Hip Abduction', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bodyweight"}', 'Starting Position:

Adjust the seat height so that your knees are aligned with the pivot point of the machine.
Sit with your back flat against the backrest, maintaining good posture.
Place the outside of your thighs against the machine''s padded levers.
Position your feet flat on the footrests or platform of the machine.
Grasp the handles or sides of the seat for stability.
Ensure your spine is neutral and your core is slightly engaged.

Movement:

Exhale as you slowly push your legs outward against the resistance pads.
Focus on initiating the movement from your hips, not your knees.
Continue opening your legs until you feel a strong contraction in your outer hips and thighs.
Hold the fully abducted position briefly (1-2 seconds) to maximize muscle engagement.
Inhale as you slowly control the return of your legs to the starting position, resisting the weight throughout the movement.
Avoid allowing the weight stack to touch down between repetitions to maintain constant tension on the muscles.
Repeat for the desired number of repetitions, maintaining control throughout the set.', null, null, 'wger', 'b144ac00-ec0c-4c43-898f-b2ac65048d98', 'CC-BY-SA 4', 'Iko'),
  ('Cable Lateral Raises (Single Arm)', 'push_v', true, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Cable machine"}', 'The single arm cable lateral raise is a variation of the lateral raise and an exercise used to build the muscles of the shoulders.

Position a cable at the lowest position possible and attach a single handle.
Reach across your body and grab the handle with a neutral grip.
Keep the elbow slightly bent and pull the handle across your body and raise laterally.
Slowly lower the handle back to the starting position under control.', 'https://wger.de/media/exercise-images/1378/7c1fcf34-fb7e-45e7-a0c1-51f296235315.jpg', null, 'wger', '81942f3d-d92c-431c-b9d0-0da12918d1e4', 'CC-BY-SA 4', 'carlos3c'),
  ('Lat Pulldown - Cross Body Single Arm', 'pull_v', true, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine"}', 'Sit at lat pulldown machine with body at a diagonal angle so that only one leg is under the pad. Pull the cable down with the opposite arm. this will force the cable to across your body while pulling down. Emphasises the stretch of the lat.', null, null, 'wger', '5a096571-4eae-472e-8849-fe5647035e2c', 'CC-BY-SA 4', 'Shiladree'),
  ('Cable Chest Press - Incline', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Triceps"}', '{"Cable machine"}', 'Single arm chest press done with the cable machine. Use the other arm to brace bodyweight to focus on strength of the press, rather than balancing of the body. Start with the hand as close to the chest as possible, and then press against the cable at a slight incline and aiming towards the center of your chest.', null, null, 'wger', 'e22c4320-7753-49c6-b7f7-4be21b025fb6', 'CC-BY-SA 4', 'Shiladree'),
  ('Cable Triceps Press', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Cable machine"}', 'A single arm exercise that starts with the hand close to the chest with with the elbows bent, and the elbow flared out. Press forward and down against the cable straightening the elbow.', null, null, 'wger', '5aee8ae1-2752-4868-af62-e3c79954d811', 'CC-BY-SA 4', 'Shiladree'),
  ('Triceps Overhead (Dumbbell)', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Dumbbell"}', 'Keep the elbows fixed
Engage the muscles
Don''t use momentum
Controlled movement
Slow movement
Don''t overextend', 'https://wger.de/media/exercise-images/1336/ebf88217-df26-4ef7-94cb-f0c2220c6abe.webp', null, 'wger', '19133a0d-e6b2-4d57-8a84-8aac3d962a99', 'CC-BY-SA 4', 'Anastasious'),
  ('Shoulder Raise (Dumbbell)', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Dumbbell"}', 'Engage the muscles
Don''t use momentum
Controlled movement
Slow movement
Always keep the arms bent
Don''t overextend', 'https://wger.de/media/exercise-images/1338/9d157b4d-5af0-43c1-bd34-f52144ba1b54.webp', null, 'wger', '9a644b0e-8691-4216-b2cc-f058f58ec96d', 'CC-BY-SA 4', 'Anastasious'),
  ('Wall Angels', 'push_v', false, false, false, 'Shoulders', '{"Trapezius"}', '{"Shoulders"}', '{}', 'The Wall Angels exercise primarily targets the upper back and shoulder muscles, helping improve posture, shoulder mobility, and scapular control.', null, null, 'wger', '2eb61587-85d1-494f-b2fb-a92dd108b3d3', 'CC-BY-SA 4', 'bbayuwega'),
  ('Seated figure four', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bench"}', 'Seat on a bench. Feet flat on the ground. Place your left ankle over your right knee. Your right knee stays flat. Keep your back straight. Gently push your left knee down.', null, null, 'wger', '73144238-414e-438f-8b0c-832a6591aa2f', 'CC-BY-SA 4', 'ricardodavidrd'),
  ('Double Kettlebell Clean and Press', 'isolation', false, false, true, 'Arms', '{"Shoulders","Biceps","Brachialis","Quads","Trapezius","Triceps"}', '{"Hamstrings","Glutes","Lats","Abs"}', '{"Kettlebell"}', 'Full-body muscles building exercise. This exercise provides a huge range of benefits in terms of strength & size and is extremely functional.', null, null, 'wger', 'fe249e2f-5856-420f-8a34-1b02c7fde141', 'CC-BY-SA 4', 'm4k3r'),
  ('Double Kettlebell Front Squat', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings","Calves","Abs"}', '{"Kettlebell"}', 'The kettlebell front squat is a compound, multi-joint exercise that works several muscle groups.', null, null, 'wger', 'a030a4e9-970c-4442-b0b3-e49b42143de0', 'CC-BY-SA 4', 'm4k3r'),
  ('Box jumps', null, false, false, false, 'Cardio', '{"Glutes"}', '{"Calves"}', '{"Bodyweight"}', 'Jump from a standing position onto the box, stretch your body, then step down again (do not jump)', null, null, 'wger', '002c6a4f-28ac-4b07-8e94-053e5b05d52b', 'CC-BY-SA 4', 'tekknokrat@gmx.de'),
  ('Rotary Torso Machine', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{}', 'Slow and Steady
Not too much weight', null, null, 'wger', '849f2fa6-42f9-4c59-90f6-275c8ada6725', 'CC-BY-SA 4', '6LXBO'),
  ('Recumbent Bike', null, false, false, true, 'Cardio', '{"Hamstrings","Calves","Glutes","Quads"}', '{}', '{}', 'For this exercise Recumbent Bike is needed. You just sit on it, set level and time and start the workout', null, null, 'wger', '12f88134-0f7a-4fb7-8bd9-436aa80d8b7c', 'CC-BY-SA 4', 'pera_perkan'),
  ('Torso Twist', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'Standing Torso Twist WorkoutTarget your core and improve flexibility with this dynamic standing exercise! The Standing Torso Twist Workout involves twisting your torso while keeping your feet and hips stable, engaging your obliques, and stretching your entire upper body. This movement helps to:Strengthen core musclesIncrease flexibility in the spine and torsoImprove posture and balanceEnhance overall athletic performancePerform 3 sets of 10-15 reps, twisting to each side, to feel the benefits of this effective and efficient workout!', 'https://wger.de/media/exercise-images/1377/12e7a231-d36a-4992-bf57-ff7bfe0f3ae4.jpg', null, 'wger', '56a03260-2901-4b28-bd41-a030185f985a', 'CC-BY-SA 4', 'brucem'),
  ('Upper Back', 'pull_h', false, false, true, 'Back', '{"Shoulders","Trapezius"}', '{"Biceps","Lats"}', '{}', 'Upper Back is suitable for building up the core muscles with a special focus on the deltoid and rhomboid muscles and the upper back muscles', null, null, 'wger', 'df18b577-0610-4804-a993-161024da67db', 'CC-BY-SA 4', 'phpi'),
  ('Bodyweight Squat HD', 'squat', false, true, true, 'Legs', '{"Quads"}', '{"Calves","Glutes","Obliquus externus abdominis","Abs","Soleus"}', '{"Bodyweight"}', 'Squat is a type of bodyweight exercise. It is one of the most popular exercises for strength and muscle growth. Squat is particularly effective for focusing on the muscles of the leg and hips.
Squat are an easy exercise for beginners to do. It can help strengthen leg muscles, tighten hip muscles and burn calories to lose weight.
It tightens the butt and legs. Squats are very effective for firming and strengthening your legs by acting on the gluteus,hip flexors, quadriceps, hamstrings and inner thigh muscles. Also, bodyweight squats can help shape your glutes and butt.', null, null, 'wger', 'edc3f6b7-96b0-4967-90d7-bba9d7d442cb', 'CC-BY-SA 4', 'admin'),
  ('Pullover Machine', 'pull_h', false, false, true, 'Back', '{"Lats"}', '{"Chest","Triceps"}', '{}', 'Pullover machine, sitting, elbows on pads', null, null, 'wger', 'ad20ef5e-e360-4859-9110-668ee0c24721', 'CC-BY-SA 4', 'Paul@Chemistry'),
  ('Zottman curl', 'isolation', false, false, false, 'Arms', '{"Biceps","Brachialis"}', '{}', '{"Dumbbell"}', 'With your palms facing forward, curl the weights up to your shoulders. Turn your hands so that that your palms downwards and slowly return the weights back down. Finally face your palms back forward.', null, null, 'wger', '9564ab2d-2534-4b47-bdf7-f2f653aae3de', 'CC-BY-SA 4', 'meldun'),
  ('Thruster', 'squat', false, true, false, 'Legs', '{"Shoulders"}', '{"Trapezius"}', '{"Barbell"}', 'Start by doing a front squat
At the top position, push the bar above your head (similar to a press)
Lower the bar to the shoulders', null, null, 'wger', '51420ded-5c17-4ce0-b005-89f1b67b7c65', 'CC0', 'BeLikeWater'),
  ('Hamstring Kicks', 'squat', false, true, false, 'Legs', '{"Hamstrings"}', '{"Glutes"}', '{"Bodyweight"}', 'Stand with your feet hip-width apart and extend one arm in front of you. Swing that leg up in front of you and back down while keeping your leg as straight as possible and your toes pointed up.Repeat with the other leg.', 'https://wger.de/media/exercise-images/1387/a2cf7eda-5540-4105-b30e-1c2f2679a6c7.png', null, 'wger', '66aef559-02e8-4f35-91f6-600f103e9cbf', 'CC-BY-SA 4', 'captive0592'),
  ('Toe Touch', 'squat', false, true, true, 'Legs', '{"Hamstrings","Glutes"}', '{"Calves"}', '{"Bodyweight"}', 'Stand with your feet closer together. Hinge at your hips and lower your upper body towards your toes. Reach your hands towards your feet, try to touch your toes, the ground, or as far down your legs as you can comfortably go.', null, null, 'wger', 'a51de8df-4101-45cb-8da5-de230d9bac1d', 'CC-BY-SA 4', 'captive0592'),
  ('Dumbbell Thruster', 'squat', false, true, true, 'Legs', '{"Hamstrings","Glutes","Quads"}', '{"Shoulders"}', '{"Dumbbell"}', 'Start with the dumbbells resting on your shoulders and squat down. Push
into standing and raise the dumbbells into an overhead position. Bring
the dumbbells back to your shoulders and repeat.', null, null, 'wger', 'ae6a522e-db10-45ba-9642-987468d8a4de', 'CC-BY-SA 4', 'meldun'),
  ('Glute Bridge Single-Arm Press', 'hinge', true, false, true, 'Arms', '{"Chest"}', '{"Shoulders","Biceps","Hamstrings","Glutes","Triceps"}', '{"Dumbbell"}', 'With one dumbbell in hand, perform a glute bridge. Now hold the dumbbell above your chest, this is the rep starting position. Lower the dumbbell so that your elbow touches the floor or is roughly 45 degrees below your shoulder if using a bench. Push the dumbbell back into the starting position.', null, null, 'wger', '8c4a9c16-294b-40e5-ba6d-50ae523704ba', 'CC-BY-SA 4', 'meldun'),
  ('Bear crawl pull through', 'hinge', false, false, true, 'Abs', '{"Shoulders","Glutes","Quads","Abs"}', '{"Hamstrings","Calves","Trapezius"}', '{"Dumbbell"}', 'Place a dumbbell at around hip level and assume a bear crawl position. Push the knees off the floor and hold.

With the opposite hand reach for the dumbbell and pull it to the other side. Place your hand back on the floor and repeat with your other hand.', null, null, 'wger', 'b4dc15da-4d4d-4a93-a30a-74aaf99192ff', 'CC-BY-SA 4', 'meldun'),
  ('Triceps Dips (Assisted)', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{"Chest"}', '{}', 'Assisted triceps dips is a gym work out exercise that targets triceps and also involves chest.', null, null, 'wger', '3dd0db1c-450a-46d1-ad46-d7854bdc26ed', 'CC-BY-SA 4', 'matpn'),
  ('Elephant Walks', 'squat', false, true, false, 'Legs', '{"Hamstrings"}', '{"Calves"}', '{"Bodyweight"}', 'Hinge at your hips until you feel a stretch behind your knees. Bend one leg while the other is straight then fluidly bend the other knee while straightening the first knee.', null, null, 'wger', '34cce09a-edb3-4140-892a-1cf70da8d98b', 'CC-BY-SA 4', 'captive0592'),
  ('Good Morning', 'hinge', false, true, false, 'Legs', '{"Hamstrings"}', '{}', '{"Bodyweight"}', 'Stand with your feet more than shoulder-width apart (wider stance) and place your hands on your hips. Hinge at your hips and lower your upper body towards the ground while keeping your back straight then come back up.', 'https://wger.de/media/exercise-images/1392/a02c9c7d-f42d-43e0-9946-1b99b014daee.png', null, 'wger', '77a56810-d050-4083-9501-d648f773376a', 'CC-BY-SA 4', 'captive0592'),
  ('Single Leg Hamstring Stretch', 'squat', true, true, false, 'Legs', '{"Hamstrings"}', '{}', '{"Bodyweight"}', 'Sit on the ground with one leg straight out in front of you and the other leg bent in toward you. Reach forward with both hands, trying to touch the toes of your straight leg.', null, null, 'wger', '45cd73d7-98ac-4451-849a-a645fcfe9bee', 'CC-BY-SA 4', 'captive0592'),
  ('Sit & Reach', 'pull_h', false, false, false, 'Back', '{"Hamstrings"}', '{}', '{"Gym mat"}', 'Sit on the ground with your legs extended straight in front of you. Reach both hands forward, trying to reach past your toes or as far as you can go. Return to the starting position and repeat.', null, null, 'wger', '5a5e8883-b185-40ff-b292-9e433d13b5e7', 'CC-BY-SA 4', 'captive0592'),
  ('Crossbody Leg Swings', 'squat', false, true, false, 'Legs', '{"Hamstrings"}', '{}', '{"Bodyweight"}', 'Hold onto a wall or something near you for support. Swing one leg across the front of your body, then back and out to the side. Repeat while slowly increasing your range of motion.', null, null, 'wger', 'bb948d34-8948-4995-9e59-003d7b6fc1b2', 'CC-BY-SA 4', 'captive0592'),
  ('Standing Pancake', 'squat', false, true, false, 'Legs', '{"Hamstrings"}', '{}', '{"Bodyweight"}', 'Stand and open your legs as wide as possible into a straddle position. Then bend at the hips, pushing them back while keeping your back straight.', null, null, 'wger', 'af59f161-147a-49ba-85c8-6c9f4e5ffe63', 'CC-BY-SA 4', 'captive0592'),
  ('Hamstring Chokes', 'squat', false, true, false, 'Legs', '{"Hamstrings"}', '{}', '{"Bodyweight"}', 'Sit on the ground and bend one leg, bringing your knee toward you. Place your hand behind your hamstring and gently pull your leg toward your chest, feeling a stretch in the back of your thigh. Straighten your leg, extending up toward the ceiling.', null, null, 'wger', '638756b5-a957-48f4-93ca-8994cead818f', 'CC-BY-SA 4', 'captive0592'),
  ('Crossbody Hamstring Stretch', 'squat', false, true, false, 'Legs', '{"Hamstrings"}', '{}', '{"Bodyweight"}', 'While standing, cross one leg behind the other (keep this leg straight). Reach downward and try to touch the toes of that leg. Slightly bend the other leg so that you can bend down.', null, null, 'wger', '4f38cc2e-5904-4ef5-b811-e729105cfd3b', 'CC-BY-SA 4', 'captive0592'),
  ('Preacher Curl - Externally Rotated', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Dumbbell"}', 'Single arm curl that can be done using a dumbbell and a preacher bench, or a preacher curl machine. Turn body away from the weight', null, null, 'wger', '7cd76565-8a8f-4658-98f1-253af9d8bb39', 'CC-BY-SA 4', 'Shiladree'),
  ('Plank-to-Elbow Extension', 'isolation', false, false, true, 'Abs', '{"Shoulders","Abs","Triceps"}', '{"Obliquus externus abdominis","Chest"}', '{"Bodyweight"}', 'The Plank-to-Elbow Extension is a dynamic exercise that combines the plank with an elbow extension movement', null, null, 'wger', 'e75629ed-4991-4a48-984c-b297f3f9fb58', 'CC-BY-SA 4', 'clafal'),
  ('Cool-Down Swim', null, false, false, true, 'Cardio', '{"Shoulders","Lats","Chest"}', '{"Glutes","Abs","Triceps"}', '{}', 'Swim at an easy, unhurried pace — freestyle, backstroke, or just floating/gliding — with zero focus on technique or drills. The only goal here is to let your heart rate come down gradually and your muscles relax before you get out of the pool.', null, null, 'wger', '1544c78d-fe6d-423d-876e-0ba1998063c6', 'CC-BY-SA 4', 'Imported from swim plan'),
  ('Plank Jacks', 'isolation', false, false, true, 'Abs', '{"Glutes","Obliquus externus abdominis","Abs"}', '{"Calves","Quads"}', '{"Bodyweight"}', 'Jumping jacks from the plank position.', null, null, 'wger', '4f5de647-eb73-4394-84a7-469d02a96de8', 'CC-BY-SA 4', 'jayninja'),
  ('Cossack squat', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Calves","Abs"}', '{}', 'The Cossack Squat is a multi-joint exercise that works mainly on the legs and buttocks, but also involves stabilizing muscles. It is an excellent exercise for improving strength, mobility and stability in a functional way.', null, null, 'wger', '96a899ee-16a4-457d-8f66-efdd39fd38a0', 'CC-BY-SA 4', 'clafal'),
  ('Wall-sit', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Calves","Abs"}', '{}', 'The Wall Sit (or wall chair) is an isometric exercise that mainly involves the leg muscles, improving muscular endurance and stability. Here are the main and secondary muscles activated during the exercise.', null, null, 'wger', '3f8ad988-1aee-48ca-ad37-44e39ae1715d', 'CC-BY-SA 4', 'clafal'),
  ('Dragon-flag', 'isolation', false, false, true, 'Abs', '{"Obliquus externus abdominis","Abs"}', '{"Shoulders","Glutes","Lats","Triceps"}', '{}', 'Keep your body completely rigid throughout the movement, avoiding sagging in your lower back.
Use a firm grip to stabilize your upper body.
Start with simpler versions (such as with bent knees) to build strength and control.', null, null, 'wger', 'f5ad82a8-adf8-4795-9874-1f6d183c56ed', 'CC-BY-SA 4', 'clafal'),
  ('Plank with Alternating Leg Lift', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bodyweight"}', 'In a plank position, lift one leg alternately.', null, null, 'wger', '94f2dea6-b336-41b2-a438-3ab7b13adbf7', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Heel Touches', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis"}', '{"Abs"}', '{"Bodyweight"}', 'Starting Position:

Lie on your back on an exercise mat.
Bend your knees, keeping your feet flat on the floor and hip-width apart.
Place your arms along your sides, palms facing inward, just off the floor.

Engage Core:

Lift your head, shoulders, and upper back slightly off the ground.
Keep your neck neutral and chin slightly tucked.

Perform the Movement:

Side-bend to the right, reaching your right hand toward your right heel.
Return to the center, then side-bend to the left, reaching your left hand toward your left heel.
Continue alternating sides in a controlled manner.

Breathing:

Exhale as you reach toward your heel and inhale as you return to the center.', null, null, 'wger', 'cfe3f20e-d078-4e6c-91fc-37da62f5ac0a', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Bicycle crunches', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{"Bodyweight"}', 'Bicycle crunches are a core exercise performed on the floor. Lie on your back with your hands behind your head and legs extended. Lift your shoulders off the ground, bring one knee toward your chest, and twist your torso so your opposite elbow meets the knee. Alternate sides in a pedaling motion, ensuring controlled movements and engaging your core throughout the exercise.', null, null, 'wger', 'fcf5039b-7784-4f82-830a-b213b597a646', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Cable Press Around', 'push_h', false, false, true, 'Chest', '{"Shoulders","Chest","Triceps"}', '{"Biceps","Serratus anterior"}', '{"Cable machine"}', 'Set the cable pulley at chest height and attach a D-handle bar. Grab
the handle with a neutral grip and hold it next to your chest with your
elbow fully flexed and tight to your side. Turn away from the pulley so
your torso is at 45 degrees.

Hold the other side of the functional trainer with your corresponding hand. Assume a staggered stance for better balance.

While keeping your chest proud, extend your elbow at 45 degrees
across your midline while keeping your arm parallel to the floor. Stop
shy of lockout and contract your chest at the top of the range of motion
(ROM).', null, null, 'wger', '70479b75-0df4-4ac2-a324-4a44b148304c', 'CC-BY-SA 4', 'Expenses7000'),
  ('Hack Squats', 'squat', false, true, true, 'Legs', '{"Quads"}', '{"Hamstrings","Calves","Glutes"}', '{}', 'Hack squats target the lower body and are performed on a hack squat machine or with a barbell. For the machine variation, position yourself on the platform with your shoulders under the pads and feet slightly forward. Push through your heels to lift the weight, then bend your knees to lower the platform in a controlled motion until your thighs are parallel to the ground. Push back up to the starting position. For the barbell variation, hold the bar behind your legs with your arms extended and perform a squat-like motion.', null, null, 'wger', 'f462df26-3264-48c2-b5aa-2374d0670c24', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Dumbbell Crunches', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{"Dumbbell"}', 'Dumbbell crunches are a weighted variation of traditional crunches designed to target the abdominal muscles more intensely. Lie flat on your back with your knees bent and feet flat on the floor. Hold a dumbbell with both hands close to your chest or above your head. Lift your shoulders and upper back off the ground in a crunching motion, engaging your core. Slowly lower yourself back to the starting position. Ensure controlled movements throughout the exercise to prevent strain.', null, null, 'wger', 'b48e4d9d-f7fc-4619-85fb-6dabe5d7c999', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Cross-Body Cable Y-Raise', 'pull_h', false, false, true, 'Back', '{"Shoulders","Lats","Trapezius"}', '{}', '{"Cable machine"}', 'Attach a D-Bar to the cable machine. Perform a motion akin to drawing a sword from across your body.', null, null, 'wger', '37314b67-1aad-4405-aa88-70846d5f035d', 'CC-BY-SA 4', 'Expenses7000'),
  ('Bent over Cable Flye', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Cable machine"}', 'Holding your upper body at an approximate 105° angle.', null, null, 'wger', '7ef2e00e-067c-48e0-9b42-3d622e0df8a4', 'CC-BY-SA 4', 'Expenses7000'),
  ('1-Arm Half-Kneeling Lat Pulldown', 'pull_v', false, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine"}', 'Attach a D-Handle to a high pully. And use your lat muscles to pull the weight single handedly.', null, null, 'wger', 'a8a4ea81-9531-48e1-b6dc-f7621c7b9283', 'CC-BY-SA 4', 'Expenses7000'),
  ('Cable Shrug-In', 'push_v', false, false, false, 'Shoulders', '{"Trapezius"}', '{}', '{"Cable machine"}', 'Attach two D-Handles to two low cables and shrug in using your upper traps.', null, null, 'wger', '05853a58-4426-450c-9b06-bfa461a767bf', 'CC-BY-SA 4', 'Expenses7000'),
  ('Reverse Cable Flye', 'push_h', false, false, false, 'Back', '{"Shoulders"}', '{"Trapezius"}', '{"Cable machine"}', 'Attach D-Handles to two cable pulleys in the upper position. Grab the left on with your right hand and vice-versa.', null, null, 'wger', '39c13706-6a8c-4ab5-b605-b9b716665a20', 'CC-BY-SA 4', 'Expenses7000'),
  ('Drag Pushdown', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Cable machine","SZ-Bar"}', 'Starting
position for this rope pushdown is standing facing a cable machine with
the handles of a rope attachment in both hands and feet shoulder width
apart.
Hinge
forward slightly at the hips maintaining an upright chest and bring the
shoulders and elbows behind the body so that when you push down on the
cable attachments, you can get a fully contracted triceps long head.
Drag
the cable machine rope attachment as close to the body as possible and
straighten your elbows until lockout.', null, null, 'wger', '02b96dc1-d1d9-4fc7-b54c-82dda1691485', 'CC-BY-SA 4', 'Moffi'),
  ('Omni Cable Cross-over', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Cable machine","SZ-Bar"}', 'Adjust the weights based on the
motion. When pulling from top to bottom, increase the weight by 20% to 40%
more than the bottom-to-top motion. This accounts for the fact that when
operating from top down, the upper chest muscles are naturally weaker than
the lower chest muscles. So, adjust your weight stack to
compensate.

Position one cable at a high
setting and the other at the lowest level setting. Get into a staggered
stance in between the cable towers.
For the cable set low, pull it
upward and across your body. This effectively targets the upper chest.
For the cable set high, draw it
downward and across your body. This will primarily engage the lower chest.

Once you’re done, swap the
positions of the cables. Change the previously high cable to the lowest
position and vice versa. Repeat the exercise sequence, ensuring you’re
targeting both chest regions effectively.', null, null, 'wger', 'ac00021c-12f9-4827-8003-ea07de980b76', 'CC-BY-SA 4', 'Moffi'),
  ('Rocking Triceps Pushdown', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Cable machine","SZ-Bar"}', 'Set your feet below the rope and lean your upper body towards the rope. Set one foot back. Push down the rope and lean your entire body back onto the rear foot as you push down to get your hands behind your body. Don''t forget to bring your chest to the front during the pushdown. As you release the rope slowly, lean your body back onto the front foot.', null, null, 'wger', '0dfe655e-ee2e-4c49-a279-c672d5591613', 'CC-BY-SA 4', 'Moffi'),
  ('Biceps Curl Machine', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{"Brachialis"}', '{}', 'The biceps curl machine is designed to isolate the biceps muscles and provide a controlled range of motion. Sit on the machine with your back against the pad and adjust the seat so your arms are aligned with the machine''s handles or pads. Grip the handles firmly, keeping your elbows fixed in place, and curl the handles upward by contracting your biceps. Slowly lower the handles to the starting position, maintaining control throughout the movement.', null, null, 'wger', 'e68f6d51-fe02-4175-b277-dec0c1521f36', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Toe Taps', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'Toe taps are a core-focused exercise performed lying on your back. Lie flat with your arms by your sides and your legs raised to a tabletop position (knees bent at 90 degrees). Slowly lower one foot to gently tap the floor, keeping your core engaged and your lower back pressed into the ground. Return to the starting position and alternate legs. This exercise strengthens the core while minimizing strain on the lower back.', null, null, 'wger', '33728393-2b84-4d39-8b68-462222e004e3', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Standing Side Crunches', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis"}', '{"Abs"}', '{"Bodyweight"}', 'Standing side crunches are a dynamic exercise that targets the obliques while improving balance and stability. Stand upright with your feet shoulder-width apart and hands behind your head or holding a dumbbell in one hand. Lean your torso to one side, contracting your obliques, while bringing your elbow toward your hip (or crunching toward the weight if using a dumbbell). Return to the starting position and alternate sides or perform all repetitions on one side before switching.', null, null, 'wger', '864b0a80-5d29-4d87-9144-f6ee6f5087b9', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Alternating High Cable Row', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine"}', 'Start
by putting the attachment in a high position on the cable station and step back about 1m from the attachment. Grab
the cable pulley handle in your left hand at about head height with your elbow slightly bent. Step back with your left foot.
Pull
your elbow joint in toward the torso twisting slightly and perform a
single-arm row. Engage the lats as you twist.
Return
to the starting position with cable pulley and left foot and grab the cable pulley handle in the right
hand. Repeat this motion on the opposite side with your right foot stepped back.', null, null, 'wger', '45251627-5f89-4858-bf0c-8884a21cbb1f', 'CC-BY-SA 4', 'Moffi'),
  ('Table Bodyweight Rows (Vasco L1)', 'pull_h', false, false, true, 'Back', '{"Lats"}', '{"Biceps","Trapezius"}', '{"Bodyweight"}', 'Vasco custom table bodyweight row for horizontal pulling in home training. Zero equipment except sturdy table. Part of Tuesday Pull day.', null, null, 'wger', 'a7a1e96f-2f34-48eb-93ad-75c08e9e2721', 'CC-BY-SA 4', 'Vasco Custom'),
  ('Dumbbell Shoulder Rotations', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Dumbbell"}', 'Dumbbell shoulder rotations are designed to strengthen the rotator cuff muscles and improve shoulder stability and mobility.

External Rotation: Hold a dumbbell in one hand, keeping your elbow bent at 90 degrees and close to your body. Rotate your forearm outward, away from your body, keeping your elbow stationary. Slowly return to the starting position.
Internal Rotation: Hold a dumbbell in one hand, keeping your elbow bent at 90 degrees and close to your body. Rotate your forearm inward, toward your body, and slowly return to the starting position. Perform the exercise with controlled movements to avoid strain.', null, null, 'wger', '5a9f4fa4-6b71-4bc7-a284-e76e43e3106a', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Plate Pinch Hold', 'isolation', false, false, false, 'Arms', '{"Shoulders"}', '{}', '{}', 'The plate pinch hold is a grip strength exercise designed to target the forearms and improve grip endurance. Select one or two weight plates (smooth-edged plates work best) and pinch them together between your thumb and fingers. Hold the plates with your arm straight down by your side or extended slightly in front of you. Maintain the hold for as long as you can, keeping your shoulders relaxed and your grip firm. This exercise can be done for time or repetitions.', null, null, 'wger', '493fb1ac-c45a-4b18-bcbb-58b809881e6f', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Reverse Wood Chops', 'pull_h', false, false, true, 'Back', '{"Glutes","Lats"}', '{"Shoulders","Biceps","Obliquus externus abdominis","Quads","Abs"}', '{"Bodyweight"}', 'Attach a looping resistance band to a rack below knee height
Grip the other end of the band like holding a baseball bat with both hands
Stretch the band facing it
Start with your hands at the side of your hips, knees bent
Rotate your hips while moving your hands towards over the top of your opposite shoulder
Imagine the motion as striking a baseball with a bat', null, null, 'wger', '6f5d4373-66d1-4acd-a16f-ba0e636fe979', 'CC-BY-SA 4', 'M9'),
  ('Lat Pull DB', 'pull_v', false, false, false, 'Back', '{"Lats"}', '{"Glutes"}', '{"Dumbbell"}', 'Bend upper body forward
Move dumbbells near your body with slightly bent arms towards your back', null, null, 'wger', '90dea8b9-4cf8-430e-8633-e08df1dd900b', 'CC-BY-SA 4', 'M9'),
  ('Scapula Pulls', 'pull_h', false, false, false, 'Back', '{"Lats","Trapezius"}', '{}', '{"Pull-up bar"}', 'Hang straight on a pull-up bar
Pull shoulder blades together, moving the body slightly up', null, null, 'wger', '2a983b8f-b77e-4f8f-8335-0e5caecd715f', 'CC-BY-SA 4', 'M9'),
  ('Pin Bench Press BB', 'push_h', false, false, false, 'Chest', '{"Chest","Triceps"}', '{}', '{"Barbell"}', 'Set security pins to about the height of your sticking point
Lower the bar, rest on the pins for 1s while holding tension
Move bar up with maximum force', null, null, 'wger', 'abd2854b-114a-4584-8746-30bd40127863', 'CC-BY-SA 4', 'M9'),
  ('Pin Squat', 'squat', false, true, true, 'Legs', '{"Hamstrings","Glutes","Quads"}', '{"Abs"}', '{"Barbell"}', 'Set security pins to about the height of your sticking point
Lower the bar, rest on the pins for 2s keeping tension
Stand up with maximum force', null, null, 'wger', '96f9d74a-7bf4-4ec1-9cd6-c62c13cf7b67', 'CC-BY-SA 4', 'M9'),
  ('Clean', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings","Lats","Abs"}', '{"Barbell"}', 'Regular olympic lift clean.
Pull bar from ground, catch on shoulders performing a front squat.', null, null, 'wger', 'a8f76beb-b6d8-430b-8e45-cc03d4959043', 'CC-BY-SA 4', 'M9'),
  ('Pin OHP', 'push_v', false, false, false, 'Shoulders', '{"Shoulders","Triceps"}', '{}', '{"Barbell"}', 'Set security pins to the height of your lower chin
Rest bar on pins keeping tension
Raise bar over head', null, null, 'wger', 'a33ba0c7-1680-4e42-a84e-aecc18c5d75b', 'CC-BY-SA 4', 'M9'),
  ('Push OHP', 'push_v', false, false, true, 'Shoulders', '{"Shoulders","Glutes","Quads"}', '{"Triceps"}', '{"Barbell"}', 'Rest bar in front on your shoulders
Bend knees while keeping upper body straight
Extend legs pushing the bar overhead with force', null, null, 'wger', 'a535b8f1-2024-4c5c-b323-f711cbf9773c', 'CC-BY-SA 4', 'M9'),
  ('Incline OHP DB', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{"Triceps"}', '{"Dumbbell"}', 'Sit on a bench with 45° incline
Ellbows 45° out
Move dumbbells down until upper arms are parallel to shoulders
Move dumbbells up, meeting overhead', null, null, 'wger', 'f89b3662-f911-4aab-9402-cfa6d47cea2b', 'CC-BY-SA 4', 'M9'),
  ('Kreis Press DB', 'push_v', false, false, true, 'Shoulders', '{"Shoulders"}', '{"Biceps","Chest","Abs","Triceps"}', '{"Dumbbell"}', 'Sit on a bench with 45° incline
Hold dumbbells overhead
Move dumbbells down as if doing overhead press
Rotate dumbbells palms facing up and extend your arms in front of your body
Move hands together until dumbbells meet, keep arms extended
Reverse the motion until dumbbells are overhead again
This is one repetition', null, null, 'wger', 'b4e78b5a-6141-4fc9-a6f7-cba13ce6559b', 'CC-BY-SA 4', 'M9'),
  ('Shoulder Raise Side and Front DB', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Dumbbell"}', 'Stand while holding dumbbells beside body
Keep arms almost fully extended
Without momentum raise dumbbells to the side of your body until shoulder height, palms facing down
Lower dumbbells beside body, palms facing inwards
Immediately raise dumbbells in front of your body until shoulder height, palms facing down
Down again
This is one repetition', null, null, 'wger', 'c146fa3c-35a4-4e6e-9000-e12a9ee19cbd', 'CC-BY-SA 4', 'M9'),
  ('Jerk OL', 'push_v', false, false, true, 'Shoulders', '{"Shoulders"}', '{"Glutes","Quads","Triceps"}', '{"Barbell"}', 'Olympic lift jerk

Hold bar in front on shoulders like push press
Bend and extend knees pushing bar up while diving under the bar
Catch bar overhead with straight arms using lunge
Move feet parallel while holding bar in lockout', null, null, 'wger', '85c28424-ab47-40d4-9a27-e1b9bfb01e7c', 'CC-BY-SA 4', 'M9'),
  ('Clean and Jerk OL', 'push_v', false, false, true, 'Shoulders', '{"Shoulders","Hamstrings","Glutes","Quads"}', '{"Lats","Abs","Trapezius","Triceps"}', '{"Barbell"}', 'Olympic lift clean and jerk.
Combination of clean and jerk in one motion.', null, null, 'wger', '8c509754-c86f-4c1b-bfa9-29c906ffc409', 'CC-BY-SA 4', 'M9'),
  ('Snatch OL', 'pull_h', false, false, true, 'Back', '{"Shoulders","Hamstrings","Glutes","Quads"}', '{"Lats"}', '{"Barbell"}', 'Olympic lift snatch

Pull barbell from ground to overhead lockout using a wide grip and overhead squat.
Move bar slowly until cleared knees then explosively extend hips, pull bar up and dive under the bar
Catch bar overhead with straight arms
Push head forward during lockout', null, null, 'wger', '127033e0-46c5-44a6-825b-fbecfe60ed9a', 'CC-BY-SA 4', 'M9'),
  ('Seated W Curl', 'isolation', false, false, false, 'Arms', '{"Biceps","Brachialis"}', '{}', '{"Bench","Dumbbell"}', 'Sit on bench with 60° incline
Hold dumbbells beside body near the ground, palms facing outwards, arms fully extended
Move dumbbells up using only biceps and without momentum', 'https://wger.de/media/exercise-images/1448/2184e68c-32b5-413f-a7c1-4a2d1bb98c35.png', null, 'wger', 'ecc46519-94b8-4ecc-b5b8-973e753e98a6', 'CC-BY-SA 4', 'M9'),
  ('ClimbMill', null, false, false, true, 'Cardio', '{"Quads"}', '{"Hamstrings","Glutes"}', '{}', 'The ClimbMill, also known as a stair climber, is a cardio-focused machine that simulates climbing stairs. It provides an effective way to improve endurance while strengthening the lower body. To use the machine, step onto the moving stairs, maintain an upright posture, and use the handrails for balance if needed. Adjust the speed and intensity to match your fitness level. This exercise helps improve cardiovascular health, burns calories, and enhances lower body muscle endurance.', null, null, 'wger', '2536b8cd-a287-48ee-b8da-58d8bd595f43', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Cobra Stretch', 'pull_h', false, false, false, 'Back', '{"Abs"}', '{"Chest"}', '{"Bodyweight"}', 'The Cobra Stretch is a back extension exercise that helps improve spinal flexibility and relieve lower back tension. To perform, lie face down on the floor with your hands placed under your shoulders. Press your palms into the floor and lift your chest while keeping your hips on the ground. Keep your elbows slightly bent and your shoulders relaxed. Hold the stretch for a few seconds, then slowly lower yourself back down. This exercise is beneficial for improving posture and reducing lower back stiffness.', null, null, 'wger', 'd8d1b919-94e1-4e91-b37e-29bb8a479740', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Torso rotation stretch', 'push_h', false, false, false, 'Chest', '{"Obliquus externus abdominis"}', '{"Chest"}', '{"Bodyweight"}', 'The torso rotation stretch helps improve spinal mobility and relieves tension in the lower back and obliques. It can be performed standing or seated.

Standing Variation: Stand upright with your feet shoulder-width apart. Place your hands on your hips or extend your arms in front of you. Slowly rotate your torso to one side, keeping your hips stable. Hold for a few seconds, then rotate to the opposite side.
Seated Variation: Sit on a chair with your feet flat on the floor. Place one hand on the outside of your opposite thigh and gently twist your torso toward that side. Hold the stretch before switching sides.', null, null, 'wger', '1e9b886f-0dbe-4434-829e-7159bcc40692', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Knee to Chest Stretch', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{"Hamstrings"}', '{"Bodyweight"}', 'The knee to chest stretch is a simple yet effective exercise for relieving lower back tension and improving hip mobility. To perform, lie flat on your back with your legs extended. Bring one knee toward your chest, wrapping your hands around your shin or behind your thigh. Gently pull the knee closer to your chest while keeping the other leg straight on the floor. Hold the stretch for 15–30 seconds, then switch sides. For a deeper stretch, both knees can be pulled toward the chest simultaneously.', 'https://wger.de/media/exercise-images/1452/85a6b9de-4eec-445b-8ebb-f1950b076aba.png', null, 'wger', '492e90a5-1ecb-4a06-8e9d-26a00042560e', 'CC-BY-SA 4', 'hpmbala@gmail.com'),
  ('Towel Superman', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{"Shoulders"}', '{}', 'In this exercise, you lie flat on your stomach, hold a
towel with your arms extended in front of you, and pull it apart to
create tension. Then, you move it forward and back under your stomach.
This exercise targets the back and shoulder muscles as well as core
stability.', null, null, 'wger', 'f44cf553-067e-4f3a-b35b-e16549c1d055', 'CC-BY-SA 4', 'Yderkone')
on conflict (name) do update set
  category          = excluded.category,
  primary_muscles   = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  equipment         = excluded.equipment,
  description       = excluded.description,
  image_url         = excluded.image_url,
  video_url         = excluded.video_url,
  source            = excluded.source,
  source_id         = excluded.source_id,
  license           = excluded.license,
  license_author    = excluded.license_author;
