-- Migration: seed the exercise library from wger (part 4 of 7)
--
-- GENERATED by scripts/build-exercise-seed.mjs — do not hand-edit. Re-run the
-- script to regenerate.
--
-- Source: https://wger.de (open exercise database, fetched via its public API)
-- Licences present: CC-BY-SA 4, CC0, CC-BY-SA 3
-- Each row carries its own license and license_author, which must be honoured
-- wherever its description or image is displayed. CC-BY-SA in particular
-- requires attribution and share-alike on the text.
--
-- NOT sourced from ExRx.net: that content is copyrighted and the site refuses
-- automated access. Its taxonomy — browse by body part, narrow by equipment —
-- is a structure rather than an expression, and is what this follows.
--
-- Split into 7 parts because the Supabase SQL editor truncates a
-- very large paste, and a cut inside a description leaves an unterminated
-- string literal. Run the parts in order; each is independent and re-runnable.
-- This part: 120 exercises.
--
-- Exercises kept: 722 of 863 fetched
-- With a description: 700 · with an image: 232 · with a video: 45
-- By category: Legs 166, Back 128, Arms 121, Abs 102, Shoulders 90, Chest 75, Cardio 31, Calves 9
-- Skipped 128: no primary muscle
-- Skipped 13: no usable name
--
-- pattern and unilateral are INFERRED from the exercise name, because wger
-- records neither. Both feed real maths — §4.3 picks the load increment from
-- pattern, §4.4 totals volume by it, and §4.1 keeps unilateral sets out of
-- bilateral PR comparisons — so check the ones you actually train. They are
-- heuristics over names, not facts from the source.
-- Inferred unilateral: 42

insert into public.exercises
  (name, pattern, unilateral, lower_body, compound,
   category, primary_muscles, secondary_muscles, equipment,
   description, image_url, video_url, source, source_id, license, license_author)
values
  ('No Leg Drive Dumbbell Chest Press', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Triceps"}', '{"Bench","Dumbbell"}', 'Set up for a normal Dumbbell chest press but lift your leg ups straight or put them on another bench to remove the leg drive.', null, null, 'wger', '10b0684c-1c48-4be6-913e-19bf1419107b', 'CC-BY-SA 4', 'Expenses7000'),
  ('Punches', 'isolation', false, false, false, 'Arms', '{"Shoulders","Triceps"}', '{}', '{"Bodyweight"}', 'stand stable and throw normal straight punches', null, null, 'wger', 'adf81065-407c-4dd7-8ec5-920cc5944d58', 'CC-BY-SA 4', 'lh1701'),
  ('Dumbbell Underhand Dead Row', 'pull_h', false, false, false, 'Arms', '{"Biceps"}', '{"Lats"}', '{"Dumbbell"}', 'The Dumbbell Underhand Dead Row will involve the back, which means you can try a bit heavier weight. The catch is that you need to be able to control the weight for all the reps.

Start by holding a pair of dumbbells with your feet shoulder-wide apart and your knees slightly bent.
Hinge at your hips to lower your torse forward until it''s almost parallel to the floor, keeping your back flat and maintaining a slight bend in your knees.
Exhale as you row the dumbbells to your sides up to chest height, leading with your elbows until your upper arms are just past parallel to the floor and the dumbbells are at ribcage level.
Slowly lower to the starting position and repeat. Keep your back flat all the time.', null, null, 'wger', '1dca10f9-a976-4a09-ab85-b95fafaa1a28', 'CC-BY-SA 4', 'Moffi'),
  ('Pause Hack Squats', 'squat', false, true, true, 'Legs', '{"Quads"}', '{"Hamstrings","Calves","Glutes"}', '{}', 'Hack Squats but with a 1-2s pause at the bottom of the movement. This makes sure that there is no more elastic energy stored in the muscles.', null, null, 'wger', '1b329beb-fcda-4471-ba70-eea62da410dd', 'CC-BY-SA 4', 'Expenses7000'),
  ('Spider Curl', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Incline bench"}', 'To get the most out of DB Spider Curls, you need an
adjustable weight bench set at a 45-degree incline. This inclined position
allows your arms to hang freely, putting them in an extended start position
with elbows slightly in front of your torso, which is the key to maintaining
low-level isometric tension throughout the movement pattern.

Lie face-down on an adjustable
weight bench with your chest fully supported, holding a pair of dumbbells.
Keep a neutral head position
and don’t crane your neck.
Let your arms hang straight
down with your palms facing forward (for a standard Spider Curl) or palms
facing inward for a Hammer Curl exercise variation.
Keep a stable foot position on
the floor to maintain balance and control.
Start the curl motion by
flexing your biceps muscles and lifting the pair of dumbbells or curl bar
toward your shoulders.
Keep your elbow flexion
controlled. Your arms should stay locked in position with no unnecessary
movement.
Squeeze hard at the top for 1-2 seconds. This
is where maximum tension hits the biceps muscle fibers.
Lower the weight under control
for 3-4 seconds to keep muscles under tension for the entire range of
motion.', null, null, 'wger', 'b3049397-a1d1-4442-9113-3532bcd1f278', 'CC-BY-SA 4', 'Moffi'),
  ('Calf Raise using Hack Squat Machine', 'squat', false, true, false, 'Legs', '{"Calves","Soleus"}', '{}', '{}', 'Ideally using a trapeze addon, Lift the weight up using your calves by getting on your toes.', null, null, 'wger', 'efeccb1b-73c0-4303-8542-bb4f45ef831a', 'CC-BY-SA 4', 'Expenses7000'),
  ('Incline Close Grip Barbell Bench Press', 'push_h', false, false, true, 'Arms', '{"Triceps"}', '{"Shoulders","Chest"}', '{"Barbell"}', 'Narrower grip than regular bench press, just outside shoulder width.', null, null, 'wger', 'fca05168-7212-42ec-8927-efb1e8dd0971', 'CC-BY-SA 4', 'Expenses7000'),
  ('Floor Skull Crusher', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"SZ-Bar"}', 'Allowing you to safely load more weight than a regular skull crusher, lie on the floor and rest the weight on the floor in between each repetition.', null, null, 'wger', '6b68043c-a900-41f4-89fb-ea5c8193f216', 'CC-BY-SA 4', 'Expenses7000'),
  ('Kroc Row', 'pull_h', false, false, false, 'Back', '{"Lats","Trapezius"}', '{}', '{}', 'Dumbbell rows with looser technique but heavier weight.', null, null, 'wger', '84b38ac6-9628-4f80-8940-204047fa2544', 'CC-BY-SA 4', 'Expenses7000'),
  ('W-Raise', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis","Abs"}', '{}', '{"Bodyweight"}', 'This challenging exercise is a variation of reverse crunches that is made up of three parts in which we’re basically drawing an upside down ‘W’ with our legs.
Start position is lying face up flat on the floor with legs extended at the low point of the outer leg of the ‘W’. Keeping a strong core and legs straight, go up, rise your hips and then slowly lower your legs down halfway. Then, lifting your legs back up to the top, rise your hips again, maintaining that straight line, use your core strength to finally come back all the way down to the other outer leg of the W. Then you reverse the ‘W’ to return to the start.', null, null, 'wger', '8b494562-012e-4944-be65-9b168f0c8c41', 'CC-BY-SA 4', 'Moffi'),
  ('Black Widow Knee Slides', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis","Abs"}', '{}', '{}', 'In
this bottom-up rotation exercise movement, you’ll cross your knee over and
drive it into that opposite elbow. Start in high plank position (or tabletop
position) with hands directly beneath your shoulders. Lift the left knee toward
the right arm and slide it up the forearm to get more of that posterior pelvic
tilt and engagement of the abdominal muscles. Then do the opposite side,
bringing your right knee toward your left hand.', null, null, 'wger', '64ebb7a5-15ec-48dd-8f82-47cdb022f215', 'CC-BY-SA 4', 'Moffi'),
  ('Butterfly Sit Up', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis","Abs"}', '{}', '{"Bodyweight"}', 'In
this midrange exercise your arm muscles provide you with a little bit of
momentum to help to get you off the ground. You also open them up in overhead
position which engages the upper back. Start
lying with feet flat on the ground, knees at an angle, arms crossed in towards your chest. Using
your ab muscles, bring your upper body off the ground as you open your arms
into goal post position, then slowly lower yourself back down to return to
starting position.', null, null, 'wger', '1bb3bbaf-2dc2-4651-95db-71faf5304075', 'CC-BY-SA 4', 'Moffi'),
  ('Seated Corkscrew', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis","Abs"}', '{}', '{"Bodyweight"}', 'To
do this abs and obliques exercise, start with your hands back behind your body
and bring your knees in and across, really trying to contract the obliques.
Then extend your legs back out to starting position and repeat toward the
opposite side of the abs.
Beginners
might find that they can’t even get through the first 45 seconds of this
challenging reverse crunches variation. That’s ok because it gives you a
place to start and something to improve upon.', null, null, 'wger', 'e9891a94-b1d4-47f4-a82b-c1aa82121abb', 'CC-BY-SA 4', 'Moffi'),
  ('Levitation Crunch', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'For
this top down movement, we’re trying to move the upper torso without moving the
lower torso. Start lying on the ground with feet flat on the floor and crossed
arms above your head with hands behind head. Lift upper body up and clear your
shoulder blades off the ground and then hold and pause at the top for a one or
two count. Try to make the upper abs work and hold that contraction for 10 good
quality reps.', null, null, 'wger', '9816dc3a-9739-4c70-bce0-4131f889e4f2', 'CC-BY-SA 4', 'Moffi'),
  ('Sit Up Elbow Thrust', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis","Abs"}', '{}', '{"Bodyweight"}', 'This
is a top down rotation movement, and it’s a bit more
explosive, too.
Lying with knees bent and feet on the floor, sit up and then drive your left elbow across your entire body toward the right, then come back
to center and then finally lower yourself down. Then hit the other side.', 'https://wger.de/media/exercise-images/1479/0305d98e-0887-4c0c-8992-7c220814efc2.webp', null, 'wger', '5af00591-2d77-4ea6-a347-825ad18beff1', 'CC-BY-SA 4', 'Moffi'),
  ('Lying Triceps Extensions', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Barbell","Dumbbell"}', 'Starting position for this
practical triceps exercise is lying on a standard bench holding a barbell or two dumbbells in both hands with an overhand grip, hands at shoulder width apart.
Begin with arms over your upper
chest and elbows bent back at about a 45-degree angle.
First bend at the elbows and
then allow the upper arm to drop back, bringing the barbell/dumbbells behind your
head and down toward the floor. In terms of upper arm position, the barbell/dumbbells should never be fully above your head, but instead behind it, to
ensure that you’re targeting the triceps.
Keep the shoulder blades tucked
under, the elbows tight in toward your head and your core active during
this entire movement.', null, null, 'wger', '8a356e9a-0058-4f60-b8d7-89147c3c371f', 'CC-BY-SA 4', 'Moffi'),
  ('Dumbbell Cheat Curl', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Dumbbell"}', 'Starting position is standing
with feet shoulder width apart.
Hands should take an underhand
or supinated grip on the dumbbells holding them with hands shoulder
width apart.
Keeping elbows tucked into your
sides throughout the entire movement, use momentum to curl the dumbbells,
squeezing your biceps at the top of the movement.
Slowly lower to return to the
starting position. Keep the core tight throughout the exercise.

Cheating
through the concentric curling portion of this challenging exercise gives us a
great opportunity to increase time under tension and create eccentric overload
with heavier weight when we lower.', null, null, 'wger', '31a58615-d3ae-4233-9c50-9143c899ce8c', 'CC-BY-SA 4', 'Moffi'),
  ('Bizeps Curls Trifecta', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Dumbbell"}', 'This exercise is a mixture of three different curls: the Supinated Cross Body Curl, the Pronated Cross Body Curl and the No Money Curl. You
alternate between three curl variations that each accomplish different goals,
and you’ll keep the set going beyond the usual 8-12 rep range which gives
us that intensity.

For the Supinated Cross Body
Curl, supinate the forearm with palms facing toward the ceiling and
forearms coming across the body. Lift the inner-facing weight of the dumbbell towards your shoulder.
For the Pronated Cross Body
Curl, pronate the forearm with palms facing toward the floor (pronated
grip or overhand grip) and forearms coming across the body. Lift the inner-facing weight of the dumbbell towards your shoulder.
For the No Money Curl, you’ll
curl the dumbbell as you outwardly rotate the shoulder. Lift the inner-facing weight of the dumbbell towards your outer side of the shoulder.', null, null, 'wger', 'da6ab4d8-edd2-428d-b194-fb15948d3fd5', 'CC-BY-SA 4', 'Moffi'),
  ('Hyper Y W Combo', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{}', 'Use a glute-ham raise or a
stability ball for this exercise and a light weight plate in each hand.
Raise your torso to form a straight line with your legs and raise the
arms outward slightly beyond a 90-degree angle into a W position to hit
the rotator cuff muscles, and then lower back to the starting position.
Then raise up again with arms
in a Y position to activate the lower traps.', null, null, 'wger', 'ebe7d74b-78a8-4757-9310-6fb22b23aa58', 'CC-BY-SA 4', 'Moffi'),
  ('Lying Triceps Kickback', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Dumbbell","Incline bench"}', 'Set the bench to an 60deg angle. Stand still and rest your upper body on the inclined bench, ensuring a nearly straight line of your entire body. Squeeze your shoulder blades together, so that your elbows are located behind your torso with your upper arms nearly parallel to the floor. Lift the dumbbells until your arms form a straight line. Slowly lower the dumbbells back to the initial position. Initial position corresponds to an rectangular position of upper and lower arms.', null, null, 'wger', '9c979645-78d1-44be-92a0-7940430a6a98', 'CC-BY-SA 4', 'Moffi'),
  ('Barbell Romanian Deadlift (RDL)', 'hinge', false, false, false, 'Back', '{"Hamstrings","Glutes"}', '{}', '{"Barbell"}', 'Execution

Hinge at the hips:

Push your hips backward, keeping a slight bend in the knees (soft knees).
Lower the barbell along the front of your thighs/shins while maintaining a neutral spine.
Keep the bar close to your body.', null, null, 'wger', '72129e4f-df97-4869-9561-33a1ba3c9186', 'CC-BY-SA 4', 'daiben'),
  ('DB Upper Chest Variation', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Shoulders"}', '{"Dumbbell"}', 'Dumbbell in hand in a curl fashion, lean body into the arm to help the dumbbell up above the chest, next to the head, to activate chest and delt combo', null, null, 'wger', '4b23738a-67a8-41af-996d-abc53a7c3f97', 'CC-BY-SA 4', 'JohnPreston'),
  ('DB Underhand bench press', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Shoulders"}', '{"Bench","Dumbbell"}', 'Underhand grip DB, perform a normal bench press movement, keeping the elbows close to the chest', null, null, 'wger', '7b40813b-80a3-42cc-8938-0c5199ef7620', 'CC-BY-SA 4', 'JohnPreston'),
  ('Elbows Tucked DB Bench Press', 'push_h', false, false, false, 'Arms', '{"Triceps"}', '{"Chest"}', '{"Bench","Dumbbell"}', 'Elbows Tucked DB Bench Press, chest press movement focusing on the triceps. DB stays parallel with body', null, null, 'wger', '732a9a7f-fb45-41ea-94a3-6a7246a699f6', 'CC-BY-SA 4', 'JohnPreston'),
  ('Lateral Walk', 'pull_h', false, false, false, 'Back', '{"Glutes"}', '{}', '{"Bodyweight"}', 'Lateral walks, also known as side steps or squat walks, are a type of exercise where you move sideways in a squatting position. They can be performed with or without resistance bands. These exercises strengthen the hip abductors, glutes, and other stabilizing muscles.', null, null, 'wger', 'c5015ed9-042b-42d3-9dac-13759ea9571e', 'CC-BY-SA 4', 'cozyGalvinism'),
  ('Alternative DB Gorilla rows', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{"Dumbbell"}', 'Slightly bent down and knees to mimic a gorilla position and pull/row up the DBs to the chest. DB stay straight (thumbs pointing up)', null, null, 'wger', '81015468-545f-4170-9b46-701afe77848e', 'CC-BY-SA 4', 'JohnPreston'),
  ('DB Cross Body Hammer Curls', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Dumbbell"}', 'Dumbbell cross body biceps curls, works on the braccialis', null, null, 'wger', '038f7cb1-6aa3-4c48-a19d-a31993f7b0d8', 'CC-BY-SA 4', 'JohnPreston'),
  ('Dumbbell Frog Press', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Dumbbell"}', 'Similar to hip thrust, but with feet put up together, lifting the butt off the ground in a frog like position.', null, null, 'wger', 'b407768d-d519-47b8-818a-44c9761a8be6', 'CC-BY-SA 4', 'JohnPreston'),
  ('Dumbbell Bradford press', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Dumbbell"}', 'From a front hold of the DBs in a OHP, press above the head, bring back towards the rear of the shoulders, down, and press back forward.', null, null, 'wger', '82f19d1c-f12b-49f0-bfdd-24239f93eabc', 'CC-BY-SA 4', 'JohnPreston'),
  ('Toes to bar', 'isolation', false, false, true, 'Abs', '{"Abs"}', '{"Lats","Obliquus externus abdominis"}', '{"Pull-up bar"}', 'The name "Toes to Bar" says it all: This exercise, in which you hang from a pull-up bar, involves bringing your toes toward the bar, pointing toward your face. This really works your abdominal muscles. "Toes to Bar" is popular in functional fitness programs like Freeletics and CrossFit, and is an effective exercise for six-pack training.', null, null, 'wger', '42d09639-a5a6-4aa6-b115-e4c96b1d3735', 'CC-BY-SA 4', 'florian.bussmann'),
  ('High-Incline Smith Machine Press', 'push_h', false, false, true, 'Chest', '{"Shoulders","Chest","Triceps"}', '{}', '{}', 'Set the bench to a 45-60° incline. Touch the upper chest with the bar.', null, null, 'wger', 'ecba2395-f364-4e5f-a34c-04f178c8b822', 'CC-BY-SA 4', 'Expenses7000'),
  ('Kong Curl', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Dumbbell"}', 'This exercise is somewhat similar to a cable curl and a cable crossover. But instead of a chest/biceps exercise, this exercise targets the brachialis muscle, responsible for that broad arm when viewed from a front view.
During the exercise, maintain a pronated forearm position with starting position of approx. 45 degree pronated. Start with slightly bend elbows and alternately curl until your hands (your thumb first) meet your upper middle chest (similar to how Kong hits his chest, thus the name of this exercise).', null, null, 'wger', '329d2adc-4b2c-4bb2-95d7-f5f6fedb9b96', 'CC-BY-SA 4', 'Moffi'),
  ('Drop Curl', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Dumbbell"}', 'Drop curls in a modified position at a slow pace effectively engage the brachialis for arm width.
Starting position is with both arms in a slight angle towards each other at chest height with a dumbbell in each hand. Lower one dumbbell close to full extended arm position slowly and in a controlled manner during the first half of the curl, then curl it back up to starting position, while the other dumbbell stays at its starting position. Now lower the other dumbbell down. This keeps tension on the brachialis. As we pass the 90deg mark on our way down, the biceps will take over the work.', null, null, 'wger', '15ee508d-fbd7-4acf-ab44-e35525582693', 'CC-BY-SA 4', 'Moffi'),
  ('Leg Press Toe Press', 'squat', false, true, false, 'Legs', '{"Calves"}', '{}', '{}', 'Move the leg press using your calves by placing your feet at the bottom of the platform.', null, null, 'wger', '0cc9c8ed-57f1-42c3-a4c4-6e57e6a1b878', 'CC-BY-SA 4', 'Expenses7000'),
  ('Handstand', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{}', 'Handstand free standing by pressing arms into the ground and contracting core and glutes', null, null, 'wger', '35008ce6-74ca-40db-b965-44a1eccfa061', 'CC-BY-SA 4', 'Fittness69'),
  ('Overhead Triceps Extension', 'isolation', false, false, false, 'Arms', '{"Trapezius"}', '{}', '{"SZ-Bar"}', 'Overhead Triceps Extension with EZ Bar – Quick Guide

The overhead position emphasizes the long head of the triceps (because it''s stretched under load), the exercise does engage all three triceps heads (long, lateral, and medial) to some degree during extension.

Setup:
Sit on a bench (or stand) and hold an EZ bar with a narrow, overhand
grip. Lift the bar overhead, arms fully extended. Keep your core tight
and elbows close to your head.
Execution:
Slowly lower the bar behind your head by bending your elbows until they
reach ~90°. Keep elbows pointed forward (not flaring out).
Finish: Extend your arms back up to the starting position, squeezing your triceps at the top.

Tips:

Control the movement to avoid straining your shoulders.
Use a moderate weight for full range of motion.
Keep your back straight and avoid arching.', 'https://wger.de/media/exercise-images/1519/fab7f641-27d4-40b5-8edd-1a0a137bfd94.gif', null, 'wger', 'c5797bdf-1aa1-4d51-9775-c929ec5a2aaf', 'CC-BY-SA 4', 'benjamin.yildiz@proton.me'),
  ('Incline Static Hold', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Dumbbell"}', 'Execution

Hold Position:

Lower the dumbbells a few inches above your chest — about the midpoint of a normal incline press.
This is where your upper chest is under maximum tension.

Static Hold:

Hold the position for 20–45 seconds while keeping the chest tight.
Breathe slowly but stay tense — do not relax your chest or shoulders.

End the set:

After the hold, carefully bring the dumbbells down and rest.', null, null, 'wger', '88afb956-8d4a-45b3-8c7c-c23719316bfe', 'CC-BY-SA 4', 'daiben'),
  ('Flat Machine Press', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Bench"}', 'Execution

Start position:

Elbows bent at roughly 90°, hands just outside your chest.
Keep wrists straight and aligned with your forearms.

Pressing phase (concentric):

Push the handles forward until your arms are almost fully extended — don’t lock out.
Focus on squeezing your chest at the end of the movement.

Returning phase (eccentric):

Slowly bring the handles back toward your chest, feeling the stretch in your pecs.
Maintain tension — don’t let the weight stack touch down between reps.', null, null, 'wger', '03f7fc27-e64f-4417-ab0c-a52adac60fda', 'CC-BY-SA 4', 'daiben'),
  ('Sled Push', null, false, false, true, 'Cardio', '{"Calves","Glutes","Quads"}', '{"Shoulders","Hamstrings","Triceps"}', '{}', 'Load the sled with 25% of your maximum load. If you don’t know this, choose a weight you can push for 10 minutes with short breaks. Beginners may choose to push the sled with no weight.
Stand behind the sled and grab the poles with a high-grip hand position.
Engage your core muscles and start pushing the sled forward as fast as you can, powering through your entire leg. Extend your hips and knees as you move the sled forward. Your foot stance should resemble your natural running position.', null, null, 'wger', '32cc7175-3fda-4c7e-900f-8766c22e3b2b', 'CC-BY-SA 4', 'flanny'),
  ('Battle Ropes', null, false, false, true, 'Cardio', '{"Hamstrings","Glutes","Lats","Obliquus externus abdominis","Quads","Abs"}', '{"Shoulders","Biceps","Chest","Trapezius","Triceps"}', '{}', 'Hold the ends of the rope at arm''s length in front of your hips with your hands shoulder-width apart.
Brace your core and begin alternately raising and lowering each arm explosively.
Keep alternating arms for three to four sets of 1 to 2 minutes.', null, null, 'wger', 'a5d1f45b-ff07-45d7-a699-a654f9328934', 'CC-BY-SA 4', 'flanny'),
  ('Ball Slams', null, false, false, true, 'Cardio', '{"Lats","Obliquus externus abdominis","Abs"}', '{"Shoulders","Glutes"}', '{}', 'Stand with your feet about shoulder-width apart, your knees and hips slightly bent, holding the ball in both hands at chest height. Engage your core, and keep a good posture.
Extend your knees and drive your hips forward while simultaneously lifting the ball. Aim for being as tall as possible, the ball overhead, arms up, hips slightly forward, and on your toes from the force of your drive.
Use your core and arms to slam the medicine ball straight down between your feet with as much force as possible. Press your hips back and bend your knees to further power the slam. Exhale as you slam the ball down.
Squat down to pick up the ball from the floor, then immediately move into the next slam by repeating the movement. Repeat for reps or time.', null, null, 'wger', 'a1e8759d-72b9-422f-87a8-9d316fa18498', 'CC-BY-SA 4', 'flanny'),
  ('Ski Machine', null, false, false, true, 'Cardio', '{"Calves","Lats","Trapezius","Triceps"}', '{"Hamstrings","Glutes","Quads","Abs"}', '{}', 'Start standing on the platform with your feet hip-width apart.
Reach overhead to grip the handles with your palms facing in.
Soften your knees, then simultaneously drive your butt back as if you''re closing a door behind you while pulling your arms straight down past your hips until your hands pass by the side of your knees.
Next, bring your arms back overhead while thrusting your hips forward until you''re standing with your arms fully extended.
Repeat for reps, time or distance.', null, null, 'wger', 'e29d9914-6b02-490b-8f3a-f9fe8f21993c', 'CC-BY-SA 4', 'flanny'),
  ('Pendulum Squat', 'squat', false, true, true, 'Legs', '{"Quads"}', '{"Hamstrings","Glutes"}', '{"Bodyweight"}', 'Place your feet in the middle of the plate at about shoulder width. Tense your torso. Keep your neck relaxed.', null, null, 'wger', 'ffdb4806-d64e-474b-8ce5-8df9a57fb9c7', 'CC-BY-SA 4', 'schweezer'),
  ('Glute Drive', 'squat', false, true, true, 'Legs', '{"Glutes"}', '{"Hamstrings","Quads"}', '{}', 'Lie down on the back pad and strap yourself in with the waistband. Position yout feet shoulder-length apart. They should be slightly splayed.', null, null, 'wger', 'ce21d3a2-cdc5-410c-9970-c25029ca3769', 'CC-BY-SA 4', 'schweezer'),
  ('Lying Dumbbell Curls', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Bench","Dumbbell"}', 'Take a
dumbbell in each hand and lie backwards on a bench, similar to a classic chest press.
Let your arms hang down at your sides, with the dumbbells possibly touching the
floor. Now start to lift the dumbbells upwards until your forearms are
perpendicular to the ceiling. Slowly lower the dumbbells until they almost
touch the floor again. Keep your ellbows in place to minimize cheating.', null, null, 'wger', '861f7396-f34e-486c-a903-3c326086f920', 'CC-BY-SA 4', 'Moffi'),
  ('Pull-Ups (Wide Grip)', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{"Bodyweight"}', 'Execution

Pulling phase (concentric):

Drive your elbows down and slightly back, pulling your chest toward the bar.
Focus on leading with your chest, not your chin.
Keep your shoulders depressed (avoid shrugging).

Top position:

Chin should clear the bar (or at least reach bar level).
Pause for a brief squeeze in your lats.', null, null, 'wger', 'be4eb0b6-2c39-4ff5-b57d-419f1687c90f', 'CC-BY-SA 4', 'daiben'),
  ('Barbell Row (Overhand)', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{"Barbell"}', 'Execution

Starting position:

Hold the barbell with arms fully extended toward the floor.
Maintain tension in your lats and back muscles.', null, null, 'wger', '6ce25688-ae91-4dc7-9b17-0b66a47151fa', 'CC-BY-SA 4', 'daiben'),
  ('Barbell Row (Underhand)', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{"Barbell"}', 'Execution

Starting position:

Hold the barbell with arms fully extended toward the floor.
Maintain tension in your lats and back muscles.', null, null, 'wger', '3c2b5e2d-bd9d-43e8-8b5f-e6363331faa1', 'CC-BY-SA 4', 'daiben'),
  ('Delt Stretch', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Bodyweight"}', 'Stretch your deltoids for a certain period of time.', null, null, 'wger', '6a448382-0ea9-4f41-8a83-0b7cd7d8a2bf', 'CC-BY-SA 4', 'Expenses7000'),
  ('Pull-up Isometric Hold', 'pull_v', false, false, true, 'Back', '{"Biceps","Lats","Trapezius"}', '{}', '{"Pull-up bar"}', 'Hold the pull-up movement in any position', null, null, 'wger', '5e3a322b-98dd-4197-b16f-4ac72c42c223', 'CC-BY-SA 4', 'DiscoCop'),
  ('One-Arm Heavy Row', 'pull_h', true, false, false, 'Back', '{"Lats"}', '{}', '{"Dumbbell"}', 'Execution

Rowing phase (concentric):

Pull the dumbbell toward your lower chest or waist, leading with your elbow.
Keep your torso stable — avoid twisting or rotating your shoulders.
Pause at the top and squeeze your lats.', null, null, 'wger', 'd8ec22e5-8575-483f-bd66-5203fd4bfe84', 'CC-BY-SA 4', 'daiben'),
  ('Patadas traseras', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Bench","Dumbbell"}', 'The dumbbell kickback is a popular strength training exercise that targets the triceps muscles in the back of your upper arms. It helps strengthen and tone the triceps, contributing to overall arm strength and aesthetics.

Among the exercises that work the arm muscles, kickback and its variations are very effective. You can easily apply these exercises with dumbbells, cables or resistance bands.', null, null, 'wger', '17dd0986-5248-410d-89a4-9268282d103b', 'CC-BY-SA 4', 'Mariano_O'),
  ('Tuck L-sit', 'isolation', false, false, true, 'Abs', '{"Abs"}', '{"Brachialis","Chest","Quads","Trapezius","Triceps"}', '{"Bench"}', 'The tuck L-sit is a bodyweight hold where you support yourself on parallel bars, parallettes, or the floor with straight arms while pulling your knees toward your chest. Your hips stay lifted, your spine stays tall, and your feet hover off the ground. The goal is to keep your core tight, shoulders depressed, and arms locked out while maintaining the tucked position. It’s a core-intensive, shoulder-stabilizing static hold often used as a progression toward the full L-sit.', null, null, 'wger', '9396a728-3da4-4390-ae4d-882395805008', 'CC-BY-SA 4', 'clafal'),
  ('Bretzel stretch', 'pull_h', false, false, true, 'Back', '{"Glutes"}', '{"Hamstrings","Lats","Chest"}', '{"Bodyweight"}', 'How to Perform the Bretzel Stretch Starting Position: Lie on your back on a flat surface, such as a mat. Bend your knees and place your feet flat on the ground. Leg Positioning: Lift your right leg and cross it over your left leg, placing your right foot on the outside of your left knee. Your left leg should remain flat on the ground. Arm Positioning: Extend your left arm out to the side at shoulder height, keeping it straight. Use your right hand to gently pull your right knee towards the floor on the left side of your body. Stretching: As you pull your knee down, try to keep your left shoulder flat on the ground. You should feel a stretch in your hip, lower back, and possibly your chest. Hold the Position: Maintain this position for 20-30 seconds, breathing deeply and relaxing into the stretch. Switch sides and repeat the process.', null, null, 'wger', 'a94c635d-096c-45a8-a68c-64941d0b6ba4', 'CC-BY-SA 4', 'mountain.potato'),
  ('Archer Pull Up', 'pull_v', false, false, true, 'Back', '{"Lats"}', '{"Biceps","Trapezius"}', '{}', 'An archer pull-up is an advanced bodyweight exercise that strengthens your back and biceps, serving as a progression towards a one-arm pull-up. It gets its name from the "bow-drawing" position your body takes at the top.Here''s how to do it:1. Grip: Grasp a pull-up bar with a wider-than-shoulder-width overhand grip.2. Starting Position: Hang with arms fully extended, engaging your core and keeping your shoulder blades pulled down.3. The Pull: Pull your body up towards one hand, similar to a regular pull-up. At the same time, extend the other arm out to the side, keeping it as straight as possible. Your chin should come towards the hand that is pulling.4. Hold & Lower: Briefly hold the top position where one arm is bent and pulling, and the other is extended. Slowly lower yourself back to the starting position with control.5. Alternate: Repeat the movement, pulling up towards the opposite hand.The key to this exercise is to keep the assisting arm as straight as possible to maximise the load on the working arm. This makes it a challenging but effective exercise for unilateral pulling strength.', null, null, 'wger', '56808c52-050e-4c24-9f27-2657f0462499', 'CC-BY-SA 4', 'Antsy6277'),
  ('Larsen Press', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Triceps"}', '{"Barbell"}', 'Put your legs up on a separate Bench and press with no leg drive', null, null, 'wger', '87f30f6d-dc8a-4b26-8c4f-640b66ecacf0', 'CC-BY-SA 4', 'Expenses7000'),
  ('Bulgarian Squat with Dumbbells', 'squat', true, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings"}', '{"Dumbbell"}', 'The Bulgarian split squat consists of performing a squat on one leg with the rear foot resting on a raised platform. Elevating your back leg on a bench creates instability and increases the range of motion of the exercise.', 'https://wger.de/media/exercise-images/1706/0c5243cc-2539-4005-aee0-d3a8c5d3a32c.jfif', null, 'wger', '60d2c34b-43a1-48a3-b43b-160e4c0157f2', 'CC-BY-SA 4', 'AlucardEvil40'),
  ('Stair Master', null, false, false, true, 'Cardio', '{"Hamstrings","Calves","Glutes","Quads"}', '{}', '{"Bodyweight"}', 'cardio and lower-body strength machine designed to simulate climbing stairs. It provides a low-impact, high-intensity workout that targets the legs, glutes, and core while improving cardiovascular endurance.', null, null, 'wger', 'b3e433ed-0247-46b3-be77-9f2738a09a48', 'CC-BY-SA 4', 'MisterPinnacle'),
  ('High Row', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine"}', 'Kneeling down on one leg and pulling cable down while driving elbow into the lats.', null, null, 'wger', 'f80468f2-7c5d-45c5-9470-46a88c1a75c2', 'CC-BY-SA 4', 'aahuja'),
  ('Elevación lateral polea', 'pull_h', false, false, false, 'Back', '{"Shoulders"}', '{}', '{"Incline bench"}', 'Lateral elevation unilateral using a polea', null, null, 'wger', 'a2fa24ba-597f-4746-b9b0-fbabae6396e6', 'CC-BY-SA 4', 'polloperro'),
  ('Bayesian Curl', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Cable machine"}', 'Cable curl with stretched shoulder (backwards)', null, null, 'wger', '06968051-a818-489c-9fbb-ddb94a001245', 'CC-BY-SA 4', 'aahuja'),
  ('Cable Tricep Kickback', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Cable machine"}', 'Grab onto the handle, and pull your elbow up and back slightly above
your torso. Keep your upper arm to be parallel to the ground for the
duration of the set', null, null, 'wger', '1ea73578-08a5-4f3e-9255-3c58b29b170d', 'CC-BY-SA 4', 'Expenses7000'),
  ('Butchers Block Stretch', 'push_v', false, false, false, 'Shoulders', '{"Lats"}', '{"Trapezius"}', '{"Bench"}', 'Kneel down with the hands together
Rest the elbows on a bench in front of you and lower the chest down
Keep the elbows bent with good posture and hold', null, null, 'wger', '4885c051-154b-4a9b-a0fe-ccb70a652fa4', 'CC-BY-SA 4', 'Croak6728'),
  ('Clap Push-UP', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Abs","Triceps"}', '{"Bodyweight"}', 'The clap push-up is an explosive upper body movement that builds power and fast-twitch muscle strength. It adds a plyometric challenge to the traditional push-up by requiring the hands to leave the ground mid-rep.

Start in a strong push-up position with your hands slightly wider than shoulder-width and core engaged
Lower your body explosively and push off the ground with enough force to lift your hands.
Quickly clap your hands together at chest level before returning them to the floor.
Land with soft elbows to absorb the impact and immediately move into the next rep', 'https://wger.de/media/exercise-images/1554/49207a62-8799-4b47-8c0b-7bde02926f3d.png', null, 'wger', 'fdeb0973-121f-494d-8b94-54f1d7ba003f', 'CC-BY-SA 4', 'Settebello'),
  ('Sleeper Stretch', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{"Trapezius"}', '{"Bodyweight"}', 'Lie on your side so that you are resting a little weight on your shoulder blade to keep it still
Extend your arm to 90 degrees in front of you, resting on the floor/mat
Lift your hand with your elbow so that your fingers point to the ceiling and your palm points towards your feet
Keeping your elbow still, gently lower your palm toward the floor', null, null, 'wger', '90f12b1b-b33e-4d83-9f9e-e26d3a4b8e0b', 'CC-BY-SA 4', 'Croak6728'),
  ('Neutral Grip Lat Pulldown', 'pull_v', false, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine"}', 'Lat pull downs with a neutral grip on the bar.', null, null, 'wger', '3cad7b92-a16b-45dc-a53e-d6a01a158f8e', 'CC-BY-SA 4', 'Expenses7000'),
  ('Devil’s Press', 'push_v', false, false, true, 'Shoulders', '{"Shoulders","Glutes","Chest"}', '{"Hamstrings","Lats","Obliquus externus abdominis","Triceps"}', '{"Dumbbell"}', 'The Devil’s Press is a hybrid movement combining a dumbbell burpee and a double dumbbell snatch. It’s a full-body, high-intensity exercise that develops strength, power, and metabolic conditioning.

Start with a dumbbell in each hand and perform a burpee, letting your chest touch the ground while holding the dumbbells.
Explosively jump your feet forward and swing the dumbbells between your legs.
Drive the dumbbells overhead in one continuous motion, locking out your arms.
Lower the dumbbells with control to return to the starting position and repeat', 'https://wger.de/media/exercise-images/1556/a23c820b-e08b-4911-a6a4-80f16c15d2e0.png', null, 'wger', 'bb9b994e-426f-4693-9d16-3f8d5a9c72b8', 'CC-BY-SA 4', 'Settebello'),
  ('Overhead Cable Tricep Extension', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Cable machine"}', 'Use rope handle with your back against the cable machine. Straighten your arms until they are filly extended and reverse the motion resisting on the negative.', null, null, 'wger', 'f2e17c8d-7285-4fd5-bfe8-26f407802850', 'CC-BY-SA 4', 'Expenses7000'),
  ('Cable Curls', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Cable machine"}', 'Bicep Curls using cables. Can be seated or standing', null, null, 'wger', '479ef6f0-5274-4da7-b5ad-67528ff3c8fd', 'CC-BY-SA 4', 'Brigade7938'),
  ('Cable Fly Middle Chest', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Cable machine"}', 'Execution

Start position: Arms extended out to your sides (a big “T” shape), feeling a stretch in your chest.

Movement: Bring your hands together in front of your chest in a wide hugging motion.

Focus on squeezing your chest at the center.
Do not lock your elbows or turn it into a press.

Return: Slowly open your arms back to the start, maintaining tension on the chest.', null, null, 'wger', '5b4fb3ec-53a1-4525-a58a-c070798ea86e', 'CC-BY-SA 4', 'daiben'),
  ('Cable Fly Upper Chest', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Cable machine"}', 'Execution

Start position:

Arms down and slightly behind your body, elbows slightly bent.
Feel a light stretch across your chest.

Movement:

Bring your hands upward and together in front of your upper chest — roughly at chin to collarbone level.
Use a smooth, controlled motion (avoid jerking).
Squeeze your chest at the top for 1–2 seconds.

Return:

Slowly let your arms move back down and out to the sides, keeping control and tension.', null, null, 'wger', 'b16a28c4-40bf-42d4-94b3-bf3f56fab743', 'CC-BY-SA 4', 'daiben'),
  ('Cable Fly Lower Chest', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Cable machine"}', 'Execution

Start position:

Arms extended out to your sides in a “Y” shape.
Feel a stretch in your chest (slight bend in elbows — don’t lock them).

Movement:

Bring your hands downward and together in front of your lower chest or upper abs, in a smooth arc motion.
Squeeze your chest hard at the bottom for 1–2 seconds.

Return:

Slowly raise your arms back up along the same path until you feel a good stretch in your chest.
Maintain control — don’t let the weights pull you back too quickly.', null, null, 'wger', 'ae695660-7cee-4601-8241-edd3e2a6d896', 'CC-BY-SA 4', 'daiben'),
  ('Jalón al pecho con agarre ancho', 'pull_h', false, false, true, 'Back', '{"Lats","Trapezius"}', '{"Biceps","Brachialis"}', '{"Cable machine"}', 'The lat pulldown is a pulling exercise that primarily targets the latissimus dorsi muscles (commonly known as “lats”) in your back. It involves pulling a cable bar or handle down towards your chest while seated on a machine specifically designed for this exercise. The lat pulldown is typically performed with a wide grip, but can also be done with a narrow grip or underhand grip to target different muscle groups in the back and arms. It is a popular exercise for building upper body strength and improving posture.', null, null, 'wger', 'c9de4551-f1bc-4490-98f4-c9f87c2a2cac', 'CC-BY-SA 4', 'Mariano_O'),
  ('DB Single-Arm Row (5kg)', 'pull_h', true, false, true, 'Back', '{"Lats"}', '{"Biceps","Brachialis"}', '{"Dumbbell"}', 'Vasco custom single-arm DB row for 5kg dumbbell home training. Unilateral horizontal pull. Part of Tuesday Pull day.', null, null, 'wger', 'ef7d621e-ddb2-490f-ae2b-e73dd509d396', 'CC-BY-SA 4', 'Vasco Custom'),
  ('Bird Dog', 'isolation', false, false, true, 'Abs', '{"Abs"}', '{"Shoulders","Glutes"}', '{"Bodyweight"}', 'The Bird Dog is a core stability exercise that enhances balance, coordination, and spinal alignment. It’s a low-impact movement ideal for strengthening the posterior chain and improving overall functional control.

Begin on all fours with hands under shoulders and knees under hips, keeping your spine neutral.
Extend your right arm forward and left leg backward simultaneously, keeping hips square.
Pause briefly at full extension while engaging your core and glutes.
Return to the starting position and repeat on the opposite side', 'https://wger.de/media/exercise-images/1572/3d14e761-a73d-49da-8804-f3016a7573ff.png', null, 'wger', '6349365e-e901-4280-a1b7-65734986f47d', 'CC-BY-SA 4', 'Settebello'),
  ('Ab wheel', 'isolation', false, false, true, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis","Serratus anterior"}', '{"Bodyweight"}', 'Starting Position: Kneel on the floor with the ab wheel in front of you.
Grip the Wheel: Hold the handles firmly.
Roll Out: Slowly roll the wheel forward, extending your body while keeping your core tight.
Return: Pull the wheel back towards your knees, maintaining tension in your core.', 'https://wger.de/media/exercise-images/1573/a9ab402b-61ef-4d60-b91a-df52bf7f41a9.jpg', null, 'wger', '203a6fee-7436-4313-858f-c1e364136793', 'CC-BY-SA 4', 'lhegedus'),
  ('Snap Down', 'squat', false, true, true, 'Legs', '{"Hamstrings","Glutes","Quads"}', '{"Calves","Abs"}', '{}', 'Begin in a standing position with your
arms up over your head and your toes pushing into the ground raising
your heels up becoming as tall as you can. From this position, perform a
small hop with both feet slightly coming off of the ground. As you
land, bend your knees and begin to hinge forward at your hips absorbing
the landing. Return to the starting position and repeat. 
You should feel the muscles in your lower body working. 
Start with your arms and knees fully
straightened out. Keep a stable balance as you land and briefly hold
that end position, don’t go too fast and become off balanced. Keep your
chest up. 
For a detailed video on landing mechanics, click here: https://youtu.be/RThUCYRDyZw', null, null, 'wger', 'c8f951dd-94e0-4548-bbed-3b7bc883f7ba', 'CC-BY-SA 4', 'mountain.potato'),
  ('Hip hinge', 'squat', false, true, true, 'Legs', '{"Hamstrings","Glutes"}', '{"Calves","Quads","Abs"}', '{"Barbell"}', 'Hip Hinge Exercise DescriptionThe hip hinge is a fundamental movement pattern that involves bending at the hips while keeping the spine neutral. It is commonly used in exercises like deadlifts, kettlebell swings, and good mornings. To perform a hip hinge: Starting Position: Stand with your feet hip-width apart and a slight bend in your knees. Hinge at the Hips: Push your hips back while maintaining a straight back. Your torso should lean forward, and your chest should stay up. Lowering Phase: Continue to hinge until your torso is nearly parallel to the ground, or until you feel a stretch in your hamstrings. Return to Standing: Drive through your heels and thrust your hips forward to return to the starting position.', null, null, 'wger', 'e4c9bfde-cf06-4c24-9c56-c0bbc13c49b5', 'CC-BY-SA 4', 'mountain.potato'),
  ('Perpendicular Unilateral Landmine Row', 'pull_h', true, false, false, 'Shoulders', '{"Shoulders","Trapezius"}', '{}', '{"Barbell"}', 'Using a landmine attachment with the barbell running at 90 degrees to either side, hinge slightly at the hips and grip the barbell by the plate sleeve. Raise the barbell to chest height, with your upper arm parallel to the floor at the top of the movement.', null, null, 'wger', '7ae1aca7-cdd4-4a81-b22c-f31778462b6b', 'CC-BY-SA 4', 'CptnFatbeard'),
  ('Trap press', 'push_v', false, false, false, 'Shoulders', '{"Trapezius"}', '{}', '{"Barbell","Bench","Dumbbell"}', 'Laying flat with arm pointing straight upwards, elbow fully extended, use only your shoulder to raise the weight as high as comfortable and back to rest.', 'https://wger.de/media/exercise-images/1581/b71a6710-5798-4639-ac5a-22a2cdae2036.jpg', null, 'wger', '41b9f5a5-73de-414d-b08a-54025eccedc6', 'CC-BY-SA 4', 'CptnFatbeard'),
  ('Side-laying interior rotation', 'push_v', false, false, false, 'Shoulders', '{"Trapezius"}', '{}', '{"Barbell","Bench","Dumbbell"}', 'Laying on your side and using the arm closest to the bench, maintain a 90 degree bend at the elbow and allow the weight to fall towards the ground past the bench as low as comfortable. Bring the weight up using only rotation of the shoulder to the opposing shoulder.', 'https://wger.de/media/exercise-images/1582/5094fe30-eea2-4269-b0de-4b8a20558fd7.png', null, 'wger', 'd9c1f78c-7bf6-4e6a-92e4-7bf4ed4a0a67', 'CC-BY-SA 4', 'CptnFatbeard'),
  ('Supine press', 'pull_h', false, false, false, 'Back', '{"Trapezius"}', '{}', '{"Barbell","Bench"}', 'Take a close grip and push perpendicular to the bench. Keep back flat.', null, null, 'wger', '2c31daac-17b1-4cc9-b1c1-f34266ee2038', 'CC-BY-SA 4', 'CptnFatbeard'),
  ('March or jog in place', null, false, false, true, 'Cardio', '{"Hamstrings","Calves","Glutes","Quads"}', '{"Shoulders","Biceps","Obliquus externus abdominis","Abs","Triceps"}', '{"Bodyweight"}', 'Low-impact cardiovascular exercise that simulates running without moving, ideal for warming up, improving endurance, or training in small spaces.', null, null, 'wger', '564dc73e-e8d4-4fd1-85ab-64dce4dd3ea0', 'CC-BY-SA 4', 'MrAlfaRobot'),
  ('Leg and hip stretch', 'squat', false, true, true, 'Legs', '{"Hamstrings","Glutes","Quads"}', '{"Lats"}', '{"Bodyweight"}', 'Gentle movements to improve the flexibility of the lower body and release tension in the hips.', null, null, 'wger', '505d6a28-1e24-4349-ab2b-49af3300e08e', 'CC-BY-SA 4', 'MrAlfaRobot'),
  ('Arm and neck stretch', 'isolation', false, false, true, 'Abs', '{"Shoulders","Trapezius","Triceps"}', '{"Lats","Serratus anterior"}', '{"Bodyweight"}', 'Relieves tension in the upper body, especially useful for people with office jobs or prolonged postures.', null, null, 'wger', 'b48cd640-dd9f-4557-a4db-8cd33d5655a6', 'CC-BY-SA 4', 'MrAlfaRobot'),
  ('Deep breathing (standing or seated)', 'push_h', false, false, false, 'Chest', '{"Obliquus externus abdominis","Abs"}', '{}', '{"Bodyweight"}', 'A conscious breathing technique to improve oxygenation, reduce stress and connect with the present moment.', null, null, 'wger', 'fae44c34-2e85-4d22-8fb8-7b14faf14719', 'CC-BY-SA 4', 'MrAlfaRobot'),
  ('Smith Machine Split Squat', 'squat', true, true, false, 'Legs', '{"Hamstrings","Quads"}', '{}', '{"Barbell"}', 'The "Smith Machine Split Squat" is a strength exercise
performed on the Smith machine, ideal for targeting the legs and glutes.
It involves placing one foot forward and the other back, lowering the
body until the front thigh is parallel to the ground while the bar
slides vertically along the machine. This exercise helps improve
stability, correct muscle imbalances, and reduces stress on the back,
providing a safe environment for strength training.', 'https://wger.de/media/exercise-images/1593/9815fcd6-cf40-4ddd-9b38-2eac25973de1.gif', null, 'wger', 'b382dcb2-60a8-412d-b0ee-6afe9c9f36d7', 'CC-BY-SA 4', 'workout@rooven.anonaddy.me'),
  ('Pull-Ups (Neutral Grip)', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{}', 'Execution

Pulling phase (concentric):

Drive your elbows down and back, pulling your chest toward your hands.
Keep your shoulders depressed and retracted (avoid shrugging).
Focus on squeezing your lats and upper back at the top.

Top position:

Chin should clear or reach the level of your hands.
Pause briefly and contract your lats hard.', null, null, 'wger', '1f490456-b426-4b89-b70c-e155c3571422', 'CC-BY-SA 4', 'daiben'),
  ('Horizontal Shoulder Flexion Stretch', 'push_v', false, false, false, 'Shoulders', '{"Chest"}', '{"Shoulders"}', '{"Bodyweight"}', 'Raise your arm out to the side, placing your hand on a wall or doorway beside you at shoulder height
Turn your body away from your arm to stretch the chest, as far as is comfortable', null, null, 'wger', 'ca4c8872-e53c-47ca-bc33-448b9ba9360f', 'CC-BY-SA 4', 'Croak6728'),
  ('Jalon caballero unialteral', 'pull_h', false, false, false, 'Back', '{"Brachialis","Obliquus externus abdominis"}', '{}', '{"Dumbbell"}', 'Pull performed in knight''s stance', null, null, 'wger', 'dcd81ab4-1e6f-4123-b4a5-3364195faf7b', 'CC-BY-SA 4', 'polloperro'),
  ('Reverse Fly Standing', 'push_h', false, false, false, 'Shoulders', '{"Shoulders","Trapezius"}', '{}', '{"Cable machine"}', 'Stand with a good posture holding a cable in each hand opposite the machine
Starting with the hands in front of your chest pull the arms out to
your side into the shape of a T with the elbows nearly straight
Slowly release the arms forward to the start
Repeat with the arms moving into the shape of a Y
Repeat with the arms in the shape of a W
Repeat with the arms in the shape of an L by your side', null, null, 'wger', '440cf10c-effb-4b63-a6e0-182fe47376f6', 'CC-BY-SA 4', 'Croak6728'),
  ('Dumbbell Scaption', 'push_v', false, false, false, 'Shoulders', '{"Trapezius"}', '{"Shoulders"}', '{"Dumbbell"}', 'Starting position:

Stand upright with your feet shoulder-width apart.

Hold a dumbbell in each hand with a neutral grip (palms facing each other).

Keep a slight bend in your elbows, shoulders relaxed and shoulder blades pulled back.

Execution:

Slowly raise the dumbbells forward and slightly to the side, at about a 30–45° angle from your body (between a front raise and a lateral raise).

Lift until your arms are about shoulder height (do not go overhead).

Pause for a second at the top and feel the activation in your shoulders and scapular stabilizers.

Lower the dumbbells back down under control to the starting position.

Breathing:

Inhale as you lower the dumbbells.

Exhale as you lift them.

Common mistakes:

Using dumbbells that are too heavy (causing jerky movements).

Lifting above shoulder height (puts unnecessary stress on the shoulder joint).

Arching the lower back instead of keeping the movement controlled at the shoulders.

Purpose of the exercise:

Activates the lower trapezius, serratus anterior, and scapular stabilizers.

Helps correct posture and improve shoulder balance.', null, null, 'wger', 'd420baf8-977b-499e-8f91-416374227b91', 'CC-BY-SA 4', 'zdelko'),
  ('Leg curl with elastic', 'isolation', false, true, false, 'Calves', '{"Calves"}', '{"Hamstrings"}', '{"Resistance band"}', 'Standing position: Place the band under your feet in the middle of your foot and grasp it with a hammer grip.', null, null, 'wger', 'ca514fad-c6ce-47b0-93a0-dc73a3507099', 'CC-BY-SA 4', 'clafal'),
  ('Sliding Lateral Lunge', 'squat', true, true, true, 'Legs', '{"Hamstrings","Glutes","Quads"}', '{"Calves","Obliquus externus abdominis"}', '{"Barbell"}', 'Stand upright with your feet hip-width apart, holding a kettlebell close to your chest in goblet position. Place one foot on a slider, gliding disc, or towel. Keep your chest tall and core engaged. Slowly slide the foot outward to the side while bending the opposite knee, lowering your hips into a lateral lunge. Keep the working leg’s knee aligned with the toes and avoid letting it collapse inward. The non-working leg remains straight and slides smoothly along the floor. Push through the heel of the bent leg to return to the starting position while maintaining control of the kettlebell.', 'https://wger.de/media/exercise-images/1604/7695428e-bfed-4021-b987-498d93153995.png', null, 'wger', '55bb8725-a7c9-48a0-b192-ec6c9db6f9bc', 'CC-BY-SA 4', 'RiccaBaro'),
  ('Copenhagen Adduction Exercise', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Obliquus externus abdominis","Serratus anterior","Trapezius"}', '{"Bench"}', 'Lie on your side with the elbow placed directly under the shoulder, similar to a side plank position. Place the upper leg on a bench with the inside of the foot or ankle resting on it. Lift your hips and hold your body in a straight line while keeping the lower leg off the floor. The exercise strongly activates the adductors of the upper leg while also challenging the core and hip stabilizers.', null, null, 'wger', 'dbed4613-e1d5-483f-90ae-6db5d593911e', 'CC-BY-SA 4', 'RiccaBaro'),
  ('Arm Raises (T/Y/I)', 'isolation', false, false, true, 'Arms', '{"Shoulders","Lats","Serratus anterior","Trapezius"}', '{"Obliquus externus abdominis"}', '{"Bodyweight"}', 'Stand upright with feet hip-width apart, core engaged, and arms relaxed at your sides. From this position, perform three different arm raises to target the shoulders and upper back:

T Raise: Lift your arms straight out to the sides until they are parallel to the floor, forming a “T” shape.
Y Raise: Lift your arms upward at about a 45° angle from your body to form a “Y” shape.
I Raise: Raise your arms straight overhead, close together, forming an “I” shape.

Maintain a neutral spine, avoid arching your lower back, and move slowly with control. Focus on squeezing your shoulder blades together and keeping your shoulders down away from your ears.', null, null, 'wger', 'e62d52fa-32f9-4747-9005-f88f05dc8334', 'CC-BY-SA 4', 'WiNNiE'),
  ('Typewriter Pull-ups', 'pull_h', false, false, true, 'Back', '{"Biceps","Lats"}', '{"Trapezius"}', '{"Bodyweight"}', 'Hang from a pull-up bar with an overhand grip, slightly wider than shoulder-width. Pull yourself up until your chin is above the bar. At the top position, instead of going straight down, shift your body to one side by extending one arm while keeping the other arm bent. Move smoothly from one side to the other, like a typewriter motion, before lowering yourself back down. This exercise increases time under tension and strengthens the lats, biceps, and shoulders while building unilateral pulling strength.', null, null, 'wger', '075bff87-f676-4d9d-92b4-39d557453fc7', 'CC-BY-SA 4', 'tenebrizz'),
  ('Bodyweight Biceps Curl', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Bodyweight"}', 'Set up under a straight bar (around waist or chest height). Grip the bar with your palms facing you (supinated grip), hands about shoulder-width apart. Lean back with straight arms so that your body is at an angle to the ground. Keeping your elbows high and close to the bar, pull your upper body toward the bar by flexing your elbows, similar to a biceps curl. Lower yourself back down in a controlled manner. Keep your core tight and movement slow to maximize tension on the biceps.', null, null, 'wger', 'a94623fc-518f-4a74-947b-febd086264bf', 'CC-BY-SA 4', 'tenebrizz'),
  ('Glute Kickback (Machine)', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{}', 'Drive through your heel, not your toes, to hit the glute.

Don’t hyperextend your lower back at the top.', null, null, 'wger', '66ed6788-a1d8-49a2-af4d-397107fbf5fb', 'CC-BY-SA 4', 'barry'),
  ('Seated Row (Machine)', 'pull_h', false, false, true, 'Back', '{"Lats"}', '{"Shoulders","Trapezius"}', '{}', 'Keep your chest up and squeeze your shoulder blades at the end.

Don’t hunch forward or round your back during the pull.', 'https://wger.de/media/exercise-images/1725/f0ebd44e-b8e1-400c-b598-ca371f3a07af.png', null, 'wger', '9bcc7b4f-4172-4db7-be95-d7b659c486f5', 'CC-BY-SA 4', 'barry'),
  ('Kettlebell sumo deadlift', 'hinge', false, true, true, 'Legs', '{"Hamstrings","Glutes","Quads"}', '{}', '{"Kettlebell"}', 'Place your feet wider than shoulder-width apart, pointing your toes outward.
Keep your back straight, shoulders back, and chest up.
The knees must follow the same direction as the toes and not move forward.
When going up, it is advisable to contract your glutes to maximize the effectiveness of the exercise..', 'https://wger.de/media/exercise-images/1612/3dc33f57-2786-4305-8b91-e011d7055923.jpg', null, 'wger', '5cbaa028-114d-4a15-9a95-70d9b3146f30', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Rubber band glute kickback', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Resistance band"}', 'A rubber band glute kickback is an exercise performed on hands and knees, where you anchor a resistance band to your foot and kick your heel back and up, squeezing your glute at the top of the movement, while maintaining a stable core and flat back to target and strengthen the gluteal muscles.', 'https://wger.de/media/exercise-images/1613/a851fe9d-771f-44da-82f0-799e02ae3fd1.jpg', null, 'wger', '4221c8af-b3ca-4a53-9176-bd66e46d10f2', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Dumbbell donkey kick', 'squat', false, true, false, 'Legs', '{"Hamstrings","Glutes"}', '{}', '{"Dumbbell"}', 'The dumbbell donkey kick is an effective exercise for working the glute and hamstring muscles. This exercise is usually performed on all fours, using a dumbbell to add resistance. The steps for performing it correctly are described below.
Starting position: Get on all fours on a mat, with your hands aligned under your shoulders and your knees aligned under your hips.
Placing the dumbbell: Take a dumbbell and place it behind the knee of the leg you are going to lift. Make sure it is held securely to prevent it from falling during the exercise.
Exercise:
Inhale and, as you exhale, lift the leg with the dumbbell upward, keeping the knee bent at a 90-degree angle.
Raise the leg until it is parallel to the floor, feeling the contraction in the glutes.
Hold the position for one second at the top and then slowly lower the leg back to the starting position.
Repetitions: Perform 10 to 15 repetitions per leg, making sure to maintain good form throughout the exercise.
Sets: Complete 2 to 3 sets, depending on your fitness level.', 'https://wger.de/media/exercise-images/1616/97e6fd98-2ca6-486f-b9b2-f0499fe38044.jpg', null, 'wger', '2539f907-0c10-4af5-807c-48cd15fd0878', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Seated Dumbbell Calf Raise', 'isolation', false, true, false, 'Calves', '{"Calves"}', '{}', '{"Dumbbell"}', 'The seated dumbbell calf raise is a targeted exercise for strengthening the lower leg muscles. It follows the same movement pattern as the machine version: you place the weight on your knees, and by extending and flexing your ankles, you move the weight.', 'https://wger.de/media/exercise-images/1620/edd40e39-e337-4460-a8dd-6127d40ddd16.jpeg', null, 'wger', '6995c30a-037f-4de3-ac4a-45384a1f38f9', 'CC-BY-SA 4', 'AlucardEvil40'),
  ('Face pulls with yellow/green band', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{"Trapezius"}', '{"Resistance band"}', 'Face pulls with band – standing horizontal pull. Grab the band at face height, pull elbows high and wide towards your face while squeezing shoulder blades together. Trains upper back, rear shoulders and improves posture.', 'https://wger.de/media/exercise-images/1732/d13b9adb-968e-4f73-95e6-b16690bcf616.jpg', null, 'wger', '7bf4e131-d4a3-44c0-8fca-9e10002492e7', 'CC-BY-SA 4', '54str'),
  ('Isometric Squat to Failure', 'squat', false, true, false, 'Legs', '{"Glutes","Quads"}', '{}', '{"Bodyweight"}', 'sometric Squat to Failure: A Strength Training Technique

Definition

The isometric squat to failure is a variation of the squat exercise where you hold a static squat position at a specific angle, maintaining the position until your muscles can no longer sustain the contraction.', 'https://wger.de/media/exercise-images/1733/4ef77069-beb2-4504-a4f3-b181d5f35212.png', null, 'wger', '06cb77ba-e56d-4422-bc14-77cc367c9fd8', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Single-Leg Lunge with Kettlebell:', 'squat', true, true, true, 'Legs', '{"Calves","Glutes","Quads"}', '{}', '{"Kettlebell"}', 'How to do a single-leg kettlebell lunge

Preparation: Stand with your feet together. Hold the kettlebell with both hands by the handle, keeping it close to your chest, or hold it with one hand (on the same side as the working leg).

Step and Lower: Take a large step forward (or backward, which is safer for your knees) with one leg, lowering your hips until both knees form a 90-degree angle.

Focus: Shift your weight onto your front (or bent) leg, keeping your back straight and your torso upright.

Return: Push off with your front leg to return to the starting position.', 'https://wger.de/media/exercise-images/1734/782e2fbb-1267-476d-a817-14f3b83e0564.png', null, 'wger', 'ff6c2fb1-5105-49ba-babe-c0d403940269', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Single-leg side glute press', 'squat', true, true, true, 'Legs', '{"Calves","Glutes","Quads"}', '{}', '{"Incline bench"}', 'The Single-Leg Side Glute Press is a leg press machine variation where you angle your body sideways on the pad, placing one foot high and slightly angled to press the weight, powerfully targeting the outer glute (gluteus medius/minimus) and hamstrings for balanced leg development and stability, requiring focus on pushing through the heel and maintaining control without locking out.

How to Perform:

Setup: Sit in the leg press machine, rotate your body to one hip, placing one foot high on the platform at about a 45-degree angle with toes pointed slightly out/forward.

Positioning: Keep your hip, knee, and ankle aligned, and ensure your lower back stays on the pad.

Descent: Slowly lower the weight, allowing your knee to bend deeply (near 90 degrees), feeling a stretch in your glute and hamstring.

Press: Drive through your heel (not your toes) to press the weight back up, squeezing your glutes and hamstrings, stopping just before your leg fully extends.

Control: Avoid bouncing and don''t let your lower back lift off the pad; maintain tension throughout the movement.', 'https://wger.de/media/exercise-images/1735/43bca7d9-2333-43f3-8554-2d0b39fa2a07.png', null, 'wger', 'd28cf04f-4077-484b-82ed-abaea8d4053d', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Straight-Arm Pulldown (Cable)', 'pull_v', false, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine"}', 'Keep arms straight but not locked, pulling with your lats, not your shoulders.

Don’t let your shoulders shrug up during the movement.', 'https://wger.de/media/exercise-images/1726/2e7e541b-5f55-405a-ae78-3e71b3f42db4.png', null, 'wger', 'a45123c6-34c2-43cf-b6bf-914a8f40995a', 'CC-BY-SA 4', 'barry'),
  ('Neutral-grip pull-ups or TRX rows', 'isolation', false, false, false, 'Arms', '{"Lats"}', '{"Biceps"}', '{"Pull-up bar"}', 'Pull-Up: Vertical Pull — Focuses more on the Lats (back width).

TRX Row: Horizontal Pull — Focuses more on the Rhomboids/Traps (mid-back thickness and posture).', 'https://wger.de/media/exercise-images/1738/0529acdf-ede8-42a2-a3e5-8d0c57b7a0e1.jpg', null, 'wger', '15fda45b-108b-4b28-bfe5-d0e55a0914bf', 'CC-BY-SA 4', '54str'),
  ('Machine Side Lateral Raises', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{}', 'Machine side lateral raises are an isolation exercise for the side (lateral) deltoids, performed on a machine for stability, targeting the outer shoulder by lifting pads or handles out to the sides to shoulder height, then lowering slowly, keeping elbows slightly bent and traps down to focus on the delts. This exercise helps build shoulder width by preventing swinging and providing constant tension, making it great for beginners or as a finisher.

How to Perform Machine Lateral Raises

Setup: Adjust the seat so your shoulders align with the machine''s pivot point, your chest is against the pad (or back if facing out), and your arms are at a 90-degree angle with the pads/handles.

Starting Position: Grip the handles with a relaxed grip, elbows slightly bent, and shoulders down (depressed) away from your ears.

Lifting Phase: Exhale and lift your arms out to the sides, moving your upper arms laterally, until they are parallel to the floor.

Peak Contraction: Pause briefly at the top, squeezing the side delts, but don''t shrug your shoulders up.

Lowering Phase: Inhale and slowly lower the weight back down with control, resisting the weight on the way down.', 'https://wger.de/media/exercise-images/1744/cb9263c4-39fc-4261-8d30-a5d6d57841c1.jpg', null, 'wger', 'dc87b735-016c-410b-915c-e3521fea4be7', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Side Straight-Arm Pulldown (Cable)', 'pull_v', false, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine"}', 'Keep your torso still, pulling the handle down along your side using the outer lat.

Don’t twist your body or rotate your torso to cheat the rep.', null, null, 'wger', '0dd4dde7-9712-4c06-8ebe-16bc7a0b1917', 'CC-BY-SA 4', 'barry'),
  ('Smith machine squat', 'squat', false, true, false, 'Legs', '{"Glutes","Quads"}', '{}', '{}', 'Technique and Execution

The Smith machine squat is a variation of the traditional barbell squat that uses a guided, fixed-path barbell. Here''s a detailed breakdown of the proper technique:

Starting Position

Foot Placement: Position feet slightly forward of the bar, about shoulder-width apart

Bar Position: Rest the bar on your upper trapezius/shoulders, similar to a traditional back squat

Stance: Feet can be slightly angled outward for natural hip rotation

Squat Movement

Unrack the bar by rotating it to release from the safety hooks

Slowly lower your body by bending knees and hips

Descend until thighs are parallel to the ground (or slightly below)

Pause briefly at the bottom of the movement

Drive through your heels to return to the starting position

Benefits and Considerations

Advantages

Reduced Balance Requirements: Fixed bar path makes it easier for beginners

Controlled Movement: Less risk of improper form compared to free weight squats

Isolation: Allows focused leg muscle development', 'https://wger.de/media/exercise-images/1747/af9647dd-04ec-4adf-9c07-4e33edb77277.jpg', null, 'wger', 'f3ef220b-a070-449c-a463-876d30cd9b14', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Windshield Wipers', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis","Abs"}', '{}', '{"Pull-up bar"}', 'Hang from a pull-up bar, raise your legs to the ceiling. Move lower body from left to right with straight legs like a windshield wiper', null, null, 'wger', '026d2939-9156-408b-bf11-21cfa8278851', 'CC-BY-SA 4', 'Happy'),
  ('Assisted chin-ups', 'pull_h', false, false, true, 'Back', '{"Biceps","Lats"}', '{"Brachialis","Trapezius"}', '{}', 'Chin-ups with machine assistance (counterweights)', null, null, 'wger', 'e4bbd8d8-20e1-4174-b785-2590d2a1a7ad', 'CC-BY-SA 4', null),
  ('Shrimp Squad', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings","Calves"}', '{"Bodyweight"}', 'Single leg squad where one leg is behind you.', null, null, 'wger', '43eeec70-df51-4cad-9bef-a35261b0caaf', 'CC-BY-SA 4', 'Happy'),
  ('L-Sit Pull-ups', 'isolation', false, false, true, 'Arms', '{"Lats"}', '{"Biceps","Brachialis","Abs"}', '{"Bodyweight"}', 'L-Sit Pull-ups train both upper body and core muscles.', null, null, 'wger', '547217ec-cb9e-4713-8bab-2d8bfb160667', 'CC-BY-SA 4', 'Happy'),
  ('Plank Reach', 'isolation', false, false, true, 'Abs', '{"Abs"}', '{"Shoulders","Obliquus externus abdominis"}', '{"Bodyweight"}', 'Position your body in plank position, keeping your eyes on the ground. Raise one arm in front of you and return it. Repeat with the other arm. Raise and return slowly while keeping your body as still as possible.', null, null, 'wger', '12418067-6cb5-44db-8973-b5be25c0146b', 'CC-BY-SA 4', null),
  ('Chair dips', 'push_v', false, false, true, 'Shoulders', '{"Triceps"}', '{"Shoulders","Chest"}', '{"Bodyweight"}', 'Starting position:

Sit down on the front edge of a chair, back straight, hands holding the front edge. Still holding the edge of the chair, arms extended, lift your butt and walk forward slightly so that it is a few inches from the chair.

Steps:

Slowly lower your body, keeping the back straight, until your arms are at a right angle.

Raise your body again to the initial position, arms extended.

Repeat.', null, null, 'wger', 'aa22b0b7-795d-47a6-8c0b-fdd0f6b9c8fc', 'CC-BY-SA 4', 'tinman'),
  ('Unilateral Cable row', 'pull_h', true, false, false, 'Back', '{"Lats","Serratus anterior"}', '{}', '{"Bench","Cable machine"}', 'Put a vertical seated bench in front of the cable row machine.position it so that you can focus on one side, and then do slow pulls focusing on the lateral muscles and ensuring tention in those muscles when in a stretched position.', 'https://wger.de/media/exercise-images/1621/ca1bc68d-9c36-4dd3-8ec4-496c57b5c564.jpg', null, 'wger', 'c1a9297d-6786-45dc-9047-5539fb61db9c', 'CC-BY-SA 4', 'Rottekongen')
on conflict (name) do update set
  category          = excluded.category,
  primary_muscles   = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  equipment         = excluded.equipment,
  description       = excluded.description,
  image_url         = excluded.image_url,
  video_url         = excluded.video_url,
  source            = excluded.source,
  source_id         = excluded.source_id,
  license           = excluded.license,
  license_author    = excluded.license_author;
