-- Migration: seed the exercise library from wger (part 7 of 7)
--
-- GENERATED by scripts/build-exercise-seed.mjs — do not hand-edit. Re-run the
-- script to regenerate.
--
-- Source: https://wger.de (open exercise database, fetched via its public API)
-- Licences present: CC-BY-SA 4, CC0, CC-BY-SA 3
-- Each row carries its own license and license_author, which must be honoured
-- wherever its description or image is displayed. CC-BY-SA in particular
-- requires attribution and share-alike on the text.
--
-- NOT sourced from ExRx.net: that content is copyrighted and the site refuses
-- automated access. Its taxonomy — browse by body part, narrow by equipment —
-- is a structure rather than an expression, and is what this follows.
--
-- Split into 7 parts because the Supabase SQL editor truncates a
-- very large paste, and a cut inside a description leaves an unterminated
-- string literal. Run the parts in order; each is independent and re-runnable.
-- This part: 2 exercises.
--
-- Exercises kept: 722 of 863 fetched
-- With a description: 700 · with an image: 232 · with a video: 45
-- By category: Legs 166, Back 128, Arms 121, Abs 102, Shoulders 90, Chest 75, Cardio 31, Calves 9
-- Skipped 128: no primary muscle
-- Skipped 13: no usable name
--
-- pattern and unilateral are INFERRED from the exercise name, because wger
-- records neither. Both feed real maths — §4.3 picks the load increment from
-- pattern, §4.4 totals volume by it, and §4.1 keeps unilateral sets out of
-- bilateral PR comparisons — so check the ones you actually train. They are
-- heuristics over names, not facts from the source.
-- Inferred unilateral: 42

insert into public.exercises
  (name, pattern, unilateral, lower_body, compound,
   category, primary_muscles, secondary_muscles, equipment,
   description, image_url, video_url, source, source_id, license, license_author)
values
  ('Kickstand RDL', 'hinge', false, true, false, 'Legs', '{"Hamstrings"}', '{}', '{"Barbell"}', 'use non-working leg''s toes to help with balance and perform an RDL.', null, null, 'wger', '107ea68a-d976-49ed-be75-3b0cf253c36a', 'CC-BY-SA 4', 'eriktrinkle'),
  ('Single Leg Extension', 'squat', true, true, false, 'Legs', '{"Quads"}', '{}', '{}', null, null, null, 'wger', '046fce45-69f2-46f7-a5b6-79a25a485af1', 'CC-BY-SA 3', 'wger.de')
on conflict (name) do update set
  category          = excluded.category,
  primary_muscles   = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  equipment         = excluded.equipment,
  description       = excluded.description,
  image_url         = excluded.image_url,
  video_url         = excluded.video_url,
  source            = excluded.source,
  source_id         = excluded.source_id,
  license           = excluded.license,
  license_author    = excluded.license_author;
