-- Migration: seed the exercise library from wger (part 5 of 7)
--
-- GENERATED by scripts/build-exercise-seed.mjs — do not hand-edit. Re-run the
-- script to regenerate.
--
-- Source: https://wger.de (open exercise database, fetched via its public API)
-- Licences present: CC-BY-SA 4, CC0, CC-BY-SA 3
-- Each row carries its own license and license_author, which must be honoured
-- wherever its description or image is displayed. CC-BY-SA in particular
-- requires attribution and share-alike on the text.
--
-- NOT sourced from ExRx.net: that content is copyrighted and the site refuses
-- automated access. Its taxonomy — browse by body part, narrow by equipment —
-- is a structure rather than an expression, and is what this follows.
--
-- Split into 7 parts because the Supabase SQL editor truncates a
-- very large paste, and a cut inside a description leaves an unterminated
-- string literal. Run the parts in order; each is independent and re-runnable.
-- This part: 120 exercises.
--
-- Exercises kept: 722 of 863 fetched
-- With a description: 700 · with an image: 232 · with a video: 45
-- By category: Legs 166, Back 128, Arms 121, Abs 102, Shoulders 90, Chest 75, Cardio 31, Calves 9
-- Skipped 128: no primary muscle
-- Skipped 13: no usable name
--
-- pattern and unilateral are INFERRED from the exercise name, because wger
-- records neither. Both feed real maths — §4.3 picks the load increment from
-- pattern, §4.4 totals volume by it, and §4.1 keeps unilateral sets out of
-- bilateral PR comparisons — so check the ones you actually train. They are
-- heuristics over names, not facts from the source.
-- Inferred unilateral: 42

insert into public.exercises
  (name, pattern, unilateral, lower_body, compound,
   category, primary_muscles, secondary_muscles, equipment,
   description, image_url, video_url, source, source_id, license, license_author)
values
  ('Shoulder Internal Rotation (Cable)', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Cable machine"}', 'Keep your elbow tucked to your side like it''s superglued there.

Don’t rotate your torso — only your forearm should move.', null, null, 'wger', 'dadecc94-6322-4c66-93b5-9cb44ec79e46', 'CC-BY-SA 4', 'barry'),
  ('Shoulder External Rotation (Cable)', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Cable machine"}', 'Keep elbow fixed at your side and rotate forearm outward smoothly.

Don’t let your wrist or elbow drift upward — stay in one plane.', null, null, 'wger', 'b283cd47-9a1c-4004-9bf5-220560ef0a16', 'CC-BY-SA 4', 'barry'),
  ('Side Lateral Raise (Cable)', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine"}', 'Lift with your elbows leading, not your hands.

Don’t shrug your shoulders; keep traps quiet.', null, null, 'wger', 'dba57084-d148-4b22-bb90-2fdd3a845ca4', 'CC-BY-SA 4', 'barry'),
  ('Front Raise (Cable)', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Cable machine"}', 'Raise the handle in a slight arc with controlled movement.

Don’t swing your torso to start the rep.', null, null, 'wger', 'be9dfe16-9fc3-463d-a9cd-7aade27ef571', 'CC-BY-SA 4', 'barry'),
  ('Cable Front Raise with a small bar', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Cable machine"}', 'The Cable Front Raise with a small bar isolates your anterior deltoids (front shoulders) by providing constant tension, requiring you to stand facing away from a low pulley, grab the bar with an overhand grip, and lift it in front of you to shoulder height with slightly bent arms, avoiding swinging and keeping your core tight for controlled movement up and down. Use a light-to-moderate weight, focusing on slow, controlled reps to feel the muscle work, not momentum.

How to Perform the Cable Front Raise (Bar)

Setup: Attach a small straight bar to a low cable pulley. Set the weight to a light or moderate setting.

Starting Position: Stand with your back to the machine, holding the bar with an overhand grip (palms facing down) at hip level, arms extended but not locked. Feet shoulder-width apart, core braced, shoulders back and down.

The Lift: Exhale and slowly raise the bar straight up in front of you, keeping a slight bend in your elbows, until your hands reach shoulder height (or slightly below).

The Hold: Pause briefly at the top, squeezing your front delts.

The Lower: Inhale as you slowly and controllably lower the bar back to the starting position, maintaining tension.', 'https://wger.de/media/exercise-images/1745/9c92843a-6b90-428b-a868-9af4b11bad38.jpg', null, 'wger', '6e03ecb3-6bfe-4b34-be9d-e5c33e820cc6', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Cable pull through', 'hinge', false, true, true, 'Legs', '{"Glutes"}', '{"Hamstrings","Calves","Quads","Soleus"}', '{"Cable machine"}', 'The Cable Pull Through is a lower-body exercise that targets the glutes and hamstrings using a "hip hinge" motion. To perform it, attach a rope to the lowest pulley setting, face away from the machine with the rope between your legs, and step forward to create tension. Keeping your back flat and knees slightly soft, push your hips backward as if trying to close a door behind you until you feel a deep stretch in your hamstrings.

To finish the rep, explosively drive your hips forward to return to a standing position, squeezing your glutes hard at the top. It is vital to remember that this is not a squat; your knees should not bend deeply, and your arms should remain straight and relaxed, acting only as hooks for the rope. This movement provides constant tension on the glutes while placing less stress on the lower back than a traditional deadlift.', null, null, 'wger', '821e289e-bd39-4410-b436-6f2a43bc3649', 'CC-BY-SA 4', 'manuher89'),
  ('Side lateral raise - Front (Cable)', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Cable machine"}', 'in a cablerack do a side lateral raise with cable in front of you, with focus in tension on the back of your shoulder.', null, null, 'wger', '7f9c13ab-1718-4f8a-8636-232f05f5f640', 'CC-BY-SA 4', null),
  ('Side lateral raise - Back (Cable)', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Cable machine"}', 'on a cable rack do a side lateral raise with the cable behind you. focus on tension in the front of the shoulder.', null, null, 'wger', '065ff3ca-a9e8-4339-997e-d65556d9ebf3', 'CC-BY-SA 4', null),
  ('Reverse crunch', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'Lay down
Place your hands near your butt (often slightly in front or under or both)
Raise your legs, but about 70% of the way you should be able to also raise your pelvis
(optional/variable) Hold 1/2 seconds at the top
Go back to starting position', null, null, 'wger', '5d8d3581-bce5-4a28-868f-8b299eaedbdd', 'CC-BY-SA 4', 'eufvksruh'),
  ('Legend Incline Bench Press', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Triceps"}', '{}', 'incline bench press on LeverEdge machine.', null, null, 'wger', 'e4804b7c-50af-4947-821f-3750718ffe65', 'CC-BY-SA 4', null),
  ('Face Pulls (Bodyweight Doorframe/Towel)', 'pull_h', false, false, true, 'Back', '{"Shoulders","Trapezius","Triceps"}', '{}', '{"Bodyweight"}', 'Vasco custom face pull variation using doorframe or towel for rear delt development. Zero equipment. Part of Tuesday Pull day.', null, null, 'wger', '52093ce1-2544-4b48-ad15-6e02de9b576d', 'CC-BY-SA 4', 'Vasco Custom'),
  ('Single-Leg Deadlift with Dumbbell', 'hinge', true, true, false, 'Legs', '{"Hamstrings","Glutes"}', '{}', '{"Dumbbell"}', 'Starting Position: Stand upright with a slight bend in your knees, holding a dumbbell in one or both hands. Shift your weight onto your supporting leg (e.g., your right leg) and lift your non-supporting foot slightly off the floor.

The Hinge: Keeping your back flat and core engaged, hinge at your hips, pushing your glutes backward. As your torso lowers, extend your non-supporting leg straight back behind you for balance, keeping your hips square to the floor. The dumbbell(s) should lower toward the ground along the line of your supporting leg.

Range of Motion: Continue lowering your torso until it is nearly parallel to the floor, or you feel an intense stretch in your supporting hamstring, ensuring your back remains neutral throughout the movement.

Return to Start: Pause at the bottom, then contract your glutes and hamstrings to slowly raise your torso back to the starting position. Your non-supporting leg should return in line with the supporting one.

Switch Sides: After completing your desired number of repetitions on one side, switch your weight and repeat the movement on the other leg.', 'https://wger.de/media/exercise-images/1736/aa724cc5-c485-4f3e-9d2a-0c6ae4baefbe.png', null, 'wger', 'a630de17-9170-434c-b486-96a6b8705506', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Single Leg Glute Bridge', 'hinge', true, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bodyweight"}', 'A glute bridge, where you use just one leg at a time.', null, null, 'wger', '68f1efb8-e7d2-4a79-99bb-65f128e10a11', 'CC-BY-SA 4', 'Happy'),
  ('Machine Hip Abduction', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{}', 'Technique and Execution

Starting Position

Seated Positioning: Sit in the machine with back against the pad

Leg Placement: Inner thighs against the machine''s padded resistance points

Adjust Machine: Set seat position to align your hip joint with the machine''s pivot point

Movement Technique

Start with legs together or slightly pressed against the inner pads

Slowly push legs outward, spreading them apart

Move until maximum comfortable lateral range is reached

Pause briefly at the outer point of the movement

Slowly return to the starting position with controlled movement

Biomechanical Breakdown

Muscle Engagement

Primary Activation: Gluteus Medius (side hip muscle)

Stabilization: Engages core and lower back muscles

Functional Movement: Mimics lateral leg movement used in walking, sports, and daily activities

Benefits

Strength and Stability

Improves Hip Stability

Reduces Risk of Knee Injuries

Enhances Lateral Movement Capabilities

Targets Often-Neglected Muscle Groups', 'https://wger.de/media/exercise-images/1748/923a3ff7-c269-49bd-9f03-697151a40f06.jpg', null, 'wger', 'b5726562-82ed-451a-89d8-8c8b13c5019a', 'CC-BY-SA 4', 'Tierrasverdes'),
  ('Deficit Push ups', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Triceps"}', '{"Bodyweight"}', 'Pushup on blocks or grips, so you can dip lower than the hands in the decent.', null, null, 'wger', 'b7dd3766-f660-45dc-bbe1-10e15e2f7cee', 'CC-BY-SA 4', 'Rottekongen'),
  ('Frog Stretch', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bodyweight"}', 'Get on your hands and knees.
Widen your knees outwards, and drop to your elbows.
Without moving your elbows or knees, start to rock forwards and backwards, trying to get your bum closer to your feet.', null, null, 'wger', 'a37001e9-b4b3-45db-8ee3-046f40350efa', 'CC-BY-SA 4', 'Croak6728'),
  ('Landmine Rotation', 'isolation', false, false, true, 'Abs', '{"Obliquus externus abdominis"}', '{"Shoulders","Abs"}', '{"Barbell"}', 'Start with landmine barbell straight up by using your shoulders to push it up above you. Then, from that position, bring it your side to target your abdominals and return to starting position.', null, null, 'wger', '73c1e130-fba9-473b-a093-a5712e2ae34d', 'CC-BY-SA 4', 'aboksz'),
  ('Floor Glider Hamstring Curls', 'push_v', false, false, true, 'Shoulders', '{"Hamstrings"}', '{"Calves","Glutes"}', '{}', 'Lie on back with heels on floor gliders or towels. Lift hips into a bridge, then slide heels toward glutes while keeping hips elevated. Slowly return to the starting position while maintaining the hip bridge.', null, null, 'wger', 'd6b2ac1d-4363-45e9-8fdb-9fba0a47b27d', 'CC-BY-SA 4', null),
  ('Double-Leg Abdominal Press', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Gym mat"}', 'Lie on your back with knees and hips bent at 90 degrees (tabletop).

Place your hands on your thighs just above your knees. Push your hands against your knees as hard as possible while using your abs to pull your knees toward your hands.

Hold for 10 seconds of maximum effort. Your abs should be shaking.', null, null, 'wger', 'f0823bb5-3f18-48d4-98de-cbe38f9fd8ff', 'CC-BY-SA 4', 'beagle'),
  ('Suitcase Carry', 'carry', true, false, true, 'Abs', '{"Obliquus externus abdominis"}', '{"Abs","Trapezius"}', '{"Dumbbell"}', 'Walk forward and backward with holding dumbbell on one side without leaning to counter the weight.', null, null, 'wger', 'b6c19c36-34be-4d9f-8c07-8bdf9ab3ba1a', 'CC-BY-SA 4', 'aboksz'),
  ('Supino inclinado', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Triceps"}', '{}', 'Inclinado 90 graus e movimentos leves e precisos', null, null, 'wger', '86237d20-f4e3-49a6-bf28-9e4660377bc9', 'CC-BY-SA 4', null),
  ('Unilateral cross body cable pull down', 'pull_v', true, false, false, 'Shoulders', '{"Lats"}', '{"Shoulders"}', '{"Cable machine"}', 'on a cable rack place cable high, and with a straight arm pull that cable across you from high to low. focus on tension in back shoulder.', null, null, 'wger', 'd788811b-be46-485a-b8a0-0d9ba7f4cf85', 'CC-BY-SA 4', null),
  ('Behind the Back Cable Lateral Raise', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{"Trapezius"}', '{"Cable machine"}', 'Lateral raises have long been a staple for building capped delts, and lifters use everything from dumbbells and bands to machines and single-arm variations to make them grow.', null, null, 'wger', '57018827-f344-4627-88e5-03e4f2f49859', 'CC-BY-SA 4', 'LEBRERO'),
  ('High-Cable Lateral Raise', 'push_v', false, false, true, 'Shoulders', '{"Shoulders"}', '{"Lats","Serratus anterior"}', '{"Cable machine"}', 'Stand next to a cable machine with the pulley set to waist height.

Grab the opposite-side handle with the hand farthest from the
pulley, keeping your palm facing in.

Keep your core engaged, chest lifted, and shoulders relaxed. Maintain a slight bend in the elbow throughout the lift.

Lift your arm out to the side until your elbow reaches shoulder height, keeping your wrist aligned with your elbow.

Briefly pause at the top, then slowly lower the handle back to your side with control. Repeat for the desired reps.', null, null, 'wger', '47b244f0-ebc6-4498-9d9f-7e7bff47322e', 'CC-BY-SA 4', 'Deflation'),
  ('DB Hammer Curls (5kg)', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{"Brachialis"}', '{"Dumbbell"}', 'Vasco custom single-arm hammer curl for 5kg dumbbell. Targets brachialis for arm thickness. Part of Tuesday Pull day.', null, null, 'wger', '6e5e15f0-5722-46d6-ad89-719c581da436', 'CC-BY-SA 4', 'Vasco Custom'),
  ('Trap Bar Squat', 'squat', false, true, false, 'Legs', '{"Quads"}', '{"Hamstrings"}', '{}', 'A combination of squat and deadlift principles with the use of a hex/trap bar, easing stress on the lower back by better centering the weight.', null, null, 'wger', 'd18407c2-75d0-43d8-8bbc-dfbb256b6b2f', 'CC-BY-SA 4', 'kmcalderwood'),
  ('Ankle dorsiflexion rocks', 'squat', false, true, false, 'Legs', '{"Calves","Soleus"}', '{}', '{"Bodyweight"}', 'Move your knee forward, keeping your heel on the ground. Hold the position for a couple of seconds and return to the starting position.', 'https://wger.de/media/exercise-images/1804/691c69b8-c3db-4177-8435-dd3a97d88542.webp', null, 'wger', 'fa5252d3-973c-4b35-9324-a02460545283', 'CC-BY-SA 4', 'Davidgj32'),
  ('Parallel Bar Hold', 'isolation', false, false, true, 'Arms', '{"Shoulders","Chest","Triceps"}', '{"Lats","Obliquus externus abdominis","Abs"}', '{}', 'Stand between a set of parallel bars.
Place your hands, knuckles outwards, on the bars.
Push down on your hands to lift yourself off the floor.
Hold yourself in this position with your arms straight for the required time.', null, null, 'wger', '934856f3-6eb3-4b37-9536-0ff67a6aa036', 'CC-BY-SA 4', 'Croak6728'),
  ('Reverse Hyperextension', 'hinge', false, true, false, 'Legs', '{"Hamstrings","Glutes"}', '{}', '{"Bench"}', 'Lie face-down on a bench with your legs hanging off the edge.

Bend your hips so your thighs are vertical, bending your knees at the same time so your shins stay horizontal.
Straighten out your legs so they are not bent and your toes are pointing backwards horizontally.
Return to the original position, and repeat.', null, null, 'wger', '682ea312-af02-450a-9880-fea7bf8e854a', 'CC-BY-SA 4', 'Croak6728'),
  ('Sphinx', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'Lie on your stomach flat, legs extended and the backs of your feet on
the ground. Bring your forearms under your shoulders, elbows directly
underneath. Then press your hands into the floor to lift your chest.
Draw your shoulder blades together, open your collarbones, and direct
your gaze forward, while keeping the lower back relaxed.', null, null, 'wger', '23d2b2ce-4ae7-441a-a122-9f6784f15aa6', 'CC-BY-SA 4', 'Joculari'),
  ('Dumbell Tate Press', 'isolation', false, false, true, 'Arms', '{"Triceps"}', '{"Shoulders","Chest"}', '{"Bench","Dumbbell"}', 'Set Up: Lie flat with a dumbbell in each hand. Extend your arms straight up over your chest as if you were at the top of a dumbbell bench press
Starting Position: Position the dumbbells so they are touching or very close together with a pronated grip (palms facing your feet and thumbs facing each other)
Lowering: Without moving your upper arms or shoulders, bend your elbows and flare them outward to the sides. Lower the inner ends of the dumbbells toward the center of your chest
Touch and Pause: Gently touch the dumbbells to your chest. Do not rest the weight on your body; maintain constant tension in your triceps
Press: Forcefully extend your elbows to return the dumbbells to the starting position. Focus on "pushing your pinkies toward the sky" to maximize triceps engagement

https://www.youtube.com/watch?v=IgSjoXbpy1M&t=2', null, null, 'wger', '2affa71f-7308-4448-af57-dc44b424090e', 'CC-BY-SA 4', 'beagle'),
  ('Chest-Supported Rear Delt Raise', 'pull_h', false, false, false, 'Shoulders', '{"Shoulders"}', '{"Trapezius"}', '{"Bench","Dumbbell"}', '"The Y"Position: Set an incline bench to 30-45 degrees. Lie face-down with your chest supported, keeping your head neutral or looking slightly down to avoid neck strain.Grip: Hold light dumbbells with a neutral or thumbs-up grip (thumb pointing to the ceiling).Movement: With straight or slightly bent elbows, raise the dumbbells up and out in a "Y" shape. Focus on moving the shoulders and shoulder blades rather than just lifting the arms.Top Position: Squeeze the shoulder blades together and reach high, ensuring the arms are angled to form a "Y".Control: Lower the dumbbells slowly to the starting position.', null, null, 'wger', '25cbc266-aa84-44f5-989b-53c9cc8fdc77', 'CC-BY-SA 4', 'beagle'),
  ('Band pull-apart with external rotation', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Resistance band"}', 'Stand tall with your feet shoulder-width apart, chest out, and shoulders back.

Hold the resistance band with both hands, palms facing up or facing each other, depending on the band type.

Bend your elbows at a 90-degree angle and glue your upper arms to your sides.

The band should have some tension in the starting position, with your hands closer together in front of your stomach.

Rotate Outward: While keeping your elbows tucked into your sides, slowly move your hands away from each other, stretching the band.

Squeeze: Squeeze your shoulder blades together and down as you rotate your hands outward.

Range of Motion: Rotate your hands as far outward as you comfortably can without allowing your elbows to leave your sides.

Hold: Hold the end position for 1–2 seconds to maximize muscle engagement.

Return: Slowly and with control, bring your hands back to the starting position.', null, null, 'wger', '83650b79-add8-4846-b114-b4f28d96495a', 'CC-BY-SA 4', 'beagle'),
  ('Abdominal Draw-In', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'Lie
on your back with knees bent. Gently pull your belly button toward your
spine without moving your hips or holding your breath.', null, null, 'wger', '793b0e5f-8dea-48a6-84c8-9123b59c2721', 'CC-BY-SA 4', 'beagle'),
  ('Landmine Squat to Press', 'squat', false, true, true, 'Legs', '{"Shoulders","Glutes","Quads"}', '{"Hamstrings","Abs"}', '{"Barbell"}', 'Bar Position: Anchor one end of a barbell in a landmine attachment or a secure corner.
Stance: Stand facing the barbell with feet slightly wider than shoulder-width. Turn your toes out 10–35 degrees to allow for better pelvic movement and depth.
Grip: Cup the free end of the barbell with both hands (fingers interlaced or overlapping) and hold it at mid-chest level, just below the collarbone.

Descent: Brace your core and sit back into a squat, keeping your chest up and weight on your heels.
Depth: Lower until your thighs are at least parallel to the floor. A good reference is when your elbows touch the tops of your thighs or just inside your knees.
Posture: Ensure your back remains flat and your spine neutral throughout the movement.

Drive: Powerfully drive through your heels to stand up. Use the momentum from your legs to "thrust" the weight upward.
Extension: In one fluid motion, press the bar overhead until your arms are fully extended. At the top, your biceps should be near your ears.
The "Lean": As you reach the top of the press, lean slightly forward into the bar to encourage proper upward rotation of the shoulder blades and avoid lower back arching.

Slowly lower the barbell back to chest height in a controlled manner before immediately beginning the next repetition.', null, null, 'wger', '67bca611-d9f1-4855-9e02-ecc8d7d688e9', 'CC-BY-SA 4', 'beagle'),
  ('Barbell Step Back Lunge', 'squat', true, true, false, 'Legs', '{"Quads"}', '{}', '{"Barbell"}', 'Step 1: Stand with your feet hip-width apart, holding a barbell on your upper back.
Step 2: Keep your back straight, chest up, and core engaged.
Step 3: Take a step back with one leg and lower your body by bending both knees. Ensure that your back knee nearly touches the ground.
Step 4: Push off your back foot to return to the starting position.
Step 5: Repeat the movement with the other leg.
Continue alternating between legs for the desired repetitions.', 'https://wger.de/media/exercise-images/1830/3b6c547c-ab3d-4472-93cf-561710279eab.jpg', null, 'wger', '928eeae3-d849-4605-a470-048ca259a8c5', 'CC-BY-SA 4', null),
  ('Hammerstrength Decline Chest Press', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Triceps"}', '{}', 'Sit upright in a hammerstrength decline chest press machine while squeezing your shoulder blades together and placing your heels firmly on the ground underneath your knees.
The back pad should be contact with your head, shoulders, and butt at all times.
Grab ahold of the handles with an overhand grip just outside shoulder-width apart just below your chest.
Keeping your core braced by breathing into your stomach and flexing the abdominal muscles, push through your palms to extend your elbows while keeping them at a 45 degree angle from your torso.
Once your arms are fully extended, return to the starting position.', 'https://wger.de/media/exercise-images/1831/2d9d509f-707b-4132-961e-91a2459ca198.jpg', null, 'wger', '920692b2-0842-428a-b925-ba0daf6b41db', 'CC-BY-SA 4', null),
  ('Trap-3 Raise', 'pull_h', false, false, false, 'Back', '{"Trapezius"}', '{}', '{"Bodyweight"}', 'Hinge forwards and bend your knees slightly. Depress and retract the shoulder you will use. Rest the other hand on your knee.
Raise your hand about 15 degrees overhead, maintaining the position of your shoulder.', null, null, 'wger', '62f90b5c-7451-4fd0-91ae-4dd93c51aa41', 'CC-BY-SA 4', 'Croak6728'),
  ('External Rotation Stretch', 'push_v', false, false, false, 'Shoulders', '{"Shoulders","Trapezius"}', '{}', '{"Barbell"}', 'Sit with your feet pressed against each other, and one knee raised all the way out to the side of your body.
Place your elbow on your raised knee, bend it at 90 degrees, and point your hand directly forward, holding your barbell/dumbbell.
Keep your shoulder depressed and retracted, raise your hand until your forearm is vertical, as if you were about to wave at someone like a robot.
Lower your hand to the original position and repeat.', 'https://wger.de/media/exercise-images/1835/ca4a0b7e-9fdd-4173-843a-f0392824abe1.jpg', null, 'wger', 'a4413bcc-dcd1-4332-a09a-fee94a265e22', 'CC-BY-SA 4', 'Croak6728'),
  ('Banded Shoulder Drills', 'push_v', false, false, true, 'Shoulders', '{"Shoulders","Chest","Trapezius"}', '{}', '{"Resistance band"}', 'Attach a resistance band to something solid behind you. Stand away from it, holding it in your hand so it is taut.
See the attached youtube video: https://www.youtube.com/watch?v=zdwEWchSjrI .', null, null, 'wger', '4c317795-c301-4081-9f96-6036682f80c1', 'CC-BY-SA 4', 'Croak6728'),
  ('Seated Shoulder Extension Stretch', 'push_v', false, false, false, 'Shoulders', '{"Lats","Chest"}', '{}', '{"Bodyweight"}', 'Sit with your hands behind you, shoulder width apart.
Lock your elbows.
Scoot your feet and hips out forwards, lowering your shoulders down towards ground.
Go as far as possible to obtain a good stretch.

See the video: https://www.youtube.com/watch?v=ihUAbG0e8zw', null, null, 'wger', 'a00b852c-0d2b-4b4a-bbc2-ef538f211b6c', 'CC-BY-SA 4', 'Croak6728'),
  ('Horse Stance (Side Splits)', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bodyweight"}', 'Stand as for a squat, with your feet wide and your toes pointed slightly outwards.
Gently squat into a deep, wide squat - your hips should be below your knees.
Hold for 3 to 5 seconds.
Come up under control, and repeat as needed.', null, null, 'wger', '36411665-4a87-4ab5-b5d3-e4eaa2802a62', 'CC-BY-SA 4', 'Croak6728'),
  ('Calves foam roller', 'squat', false, true, false, 'Legs', '{"Calves"}', '{}', '{"Bodyweight"}', 'Move your calves slowly over the foam roller', 'https://wger.de/media/exercise-images/1854/ccd3c18e-c864-426f-8176-15dce14305e3.webp', null, 'wger', '05b36227-a331-45b8-b1d5-5c7293c2df17', 'CC-BY-SA 4', 'Davidgj32'),
  ('Foam Roller Iliotibial band', 'squat', false, true, false, 'Legs', '{"Quads"}', '{}', '{"Bodyweight"}', 'Slide on the Foam Roller over your iliotibial band. Is english terrible checker', 'https://wger.de/media/exercise-images/1857/92291128-cc7e-4f70-9663-80840c516fc9.jpg', null, 'wger', '4d96e62c-e4ac-45be-9428-b97f18ca26d9', 'CC-BY-SA 4', 'Davidgj32'),
  ('Foam Roller quadriceps', 'squat', false, true, false, 'Legs', '{"Quads"}', '{}', '{"Bodyweight"}', 'Slide the Foam Roller over your quadriceps. Is english, please', 'https://wger.de/media/exercise-images/1858/058b6fdb-8093-4b6d-a504-cbf869f3e3d3.jpg', null, 'wger', 'b8ffa641-55e7-4761-ad5d-8336bb3ab3d4', 'CC-BY-SA 4', 'Davidgj32'),
  ('Foam Roller Gluteus', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bodyweight"}', 'Slide on the Foam Roller over your gluteus. Is english please', 'https://wger.de/media/exercise-images/1859/2465d5eb-c249-454d-93eb-58aa13bdc080.webp', null, 'wger', '164a31e9-ce70-4339-aee5-4ea7a3bdd246', 'CC-BY-SA 4', 'Davidgj32'),
  ('Banded Scapular Retraction', 'pull_h', false, false, false, 'Back', '{"Shoulders","Trapezius"}', '{}', '{"Resistance band"}', 'Attach one end of resistance band to wall/upright/... at shoulder height. Insert arm into the loop, at the tricep. Step back until band is pulled straight. Pull back elbow and shoulder against the resistance of the band.', null, null, 'wger', 'add364ed-4444-4752-9a22-d85d58199fe5', 'CC-BY-SA 4', 'hurr99'),
  ('Incline DB Y-Raise', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{"Trapezius"}', '{"Dumbbell"}', 'Set
an incline bench to a 45-degree angle and sit facing the bench, chest
against the pad, with a dumbbell in each hand, palms facing each other.
Position your feet firmly on the ground for stability and let your arms hang down naturally with a slight bend in your elbows.
Engage your core and keep your back straight throughout the movement.
Raise your arms forward and out to form a Y shape, keeping the movement controlled and your elbows slightly bent.
Lift until your arms are roughly parallel to the floor and in line with your ears.
Pause
briefly at the top of the movement to engage your shoulder muscles
fully, then slowly lower your arms back down to the starting position.
Ensure
the movement is slow and controlled during both the ascent and descent
to maximize engagement of the deltoids and supporting muscles.
Repeat for the desired number of repetitions, maintaining proper form throughout.', null, null, 'wger', '16bd91ca-a9fe-47fc-b3a8-a9d70549e929', 'CC-BY-SA 4', 'Deflation'),
  ('Clamshell', 'isolation', false, false, false, 'Abs', '{"Glutes","Abs"}', '{}', '{"Bodyweight"}', 'Position
Side plank with the elbow and the forearm on the ground and the legs slightly bent.

Execution
Lift your upper knee while keeping your feet close together, like a “shell opening,” then slowly return to the starting position. Keep your core stable and your hips aligned.', null, null, 'wger', 'ca3ca5d0-5231-4420-ad06-fa3d32693a1b', 'CC-BY-SA 4', 'teus_ergaster'),
  ('Banded Clamshell', 'squat', false, true, true, 'Legs', '{"Glutes","Abs"}', '{"Quads"}', '{"Resistance band"}', 'Position
Side plank with the elbow and the forearm on the ground and the legs slightly bent. Stretch a doubled-up resistance band between your thighs, just above the knee.

Execution
Lift
your upper knee while keeping your feet close together, like a “shell
opening,” then slowly return to the starting position. Keep your core
stable and your hips aligned.', null, null, 'wger', '8cc84753-e638-4c43-91c6-51c097813ca4', 'CC-BY-SA 4', 'Croak6728'),
  ('Standing Pancake Good Morning', 'hinge', false, true, false, 'Legs', '{"Hamstrings"}', '{}', '{"Bodyweight"}', 'Stand with your feet wider than shoulder-width apart and toes pointed slightly outward. Place your hands on the back of your head. Hinge at your hips and lower your upper body towards the ground, keeping your back straight and chest open.', null, null, 'wger', 'aa3c2791-74f7-4fed-a812-297ff454e2f9', 'CC-BY-SA 4', 'captive0592'),
  ('Seated Pancake Good Morning', 'hinge', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bodyweight"}', 'Sit with your legs completely straight (knees locked), spread wide in a straddle position.
Place your hands on the back of your neck.
Hinge your torso and head towards the floor.', null, null, 'wger', '96583e33-e643-486d-95e9-67d0d5935b05', 'CC-BY-SA 4', 'Croak6728'),
  ('Shinbox IR Stretch', 'squat', false, true, false, 'Legs', '{"Glutes","Obliquus externus abdominis"}', '{}', '{"Bodyweight"}', 'Starting Position: Sit on the floor with both hips and knees bent at 90-degree angles.
Leg Placement:
Place one leg in front of you (external rotation) and the other leg out
to the side/behind you (internal rotation). The shins and knees should
remain flat on the ground.
The Movement:
Keeping your hips square, hinge your torso forward or tilt it laterally
(side-to-side) toward the front leg to deepen the stretch.
Target Areas:
Stretches the glutes and piriformis (front leg) and the hip flexors and
quads (back leg). Engages the core and obliques during lateral flexion.
Goal: Improves hip mobility, specifically internal and external rotation, and relieves lower back tension.', null, null, 'wger', 'ceb58be5-2927-48c5-bb2d-4cc42b0a60e2', 'CC-BY-SA 4', 'teus_ergaster'),
  ('YTWL Exercise', 'push_v', false, false, false, 'Shoulders', '{"Shoulders","Trapezius"}', '{}', '{"Dumbbell","Incline bench"}', 'Purpose: Improves shoulder stability, posture, and scapular (shoulder blade) control. Often used in physical therapy and warm-ups.
Starting Position:
Stand with feet shoulder-width apart. Hinge forward at the hips (like a
deadlift) keeping your back flat, or lie face down on an incline bench.
Keep your thumbs pointing up throughout.
Y (Arms up):
Extend both arms straight forward and upward at a 135-degree angle from
your body, forming a "Y". Squeeze your shoulder blades together at the
top.
T (Arms out): Open your arms straight out to the sides, perpendicular to your body, forming a "T". Focus on pinching your shoulder blades.
W (Arms bent): Pull your elbows back, bending them to 90 degrees, and squeeze your shoulder blades to form a "W". Keep your wrists firm.
L (Arms rotated):
Start with elbows bent at 90 degrees and close to your body. Rotate
your forearms outward (external rotation) like a goalpost, forming an
"L" or a gate.
Key Focus:
Movements should be slow and controlled. Always lead with the thumbs
and think about moving the shoulder blades, not just the arms.', null, null, 'wger', '5986cd29-11ff-43f4-af65-fc48dec62156', 'CC-BY-SA 4', 'teus_ergaster'),
  ('Supine Hip Abduction', 'squat', false, true, false, 'Legs', '{"Glutes","Quads"}', '{}', '{"Dumbbell"}', 'Starting Position:
Lie on your back (supine) on a mat, with your legs extended and
relaxed. Arms can be placed alongside your body or out to the sides for
stability.
The Movement:
Slightly lift one leg off the floor (keeping it straight or with a
slight bend). Move it laterally outward, away from the other leg, as if
stepping over a small obstacle.
Range of Motion:
Move the leg as far as comfortable without lifting your pelvis or
rotating your torso, feeling a stretch in the inner thigh and hip.
Return: Slowly bring the leg back to the starting position with controlled movement.
Goal: Improves lateral hip mobility (abduction) and strengthens the pelvic stabilizer muscles.', null, null, 'wger', '2fe15ae4-085b-4116-8d73-2a120cc2a231', 'CC-BY-SA 4', 'teus_ergaster'),
  ('Dumbbell snatch', 'squat', false, true, true, 'Legs', '{"Hamstrings","Glutes","Quads"}', '{}', '{"Dumbbell"}', 'Key Steps to Execute Correctly:

Setup: Place the dumbbell between your feet, with your shoulders above your hips, chest up, and back flat.

The Pull: Explosively extend your hips, knees, and ankles (triple extension) to drive the dumbbell upward, keeping your elbow high and the dumbbell close to your body.

The Catch: Quickly flex your hips and knees to drop under the dumbbell and receive it overhead with your arm locked in position, landing in a half-squat stance.

Common Mistakes: Using your arms too much to lift the weight instead of your legs, having a low elbow during the pull phase, and misaligning your shoulder, elbow, and wrist in the final position. For beginners, it’s recommended to start with light loads, focus on technique, and perform 3 to 5 sets of 3 to 5 reps per arm.', 'https://wger.de/media/exercise-images/1947/4201a9c0-f9e4-48ca-80f1-b46c7ffe5640.webp', null, 'wger', '51fe0871-1390-4755-bd04-01a93e32f533', 'CC-BY-SA 4', 'Aleid'),
  ('1 Leg Box Squat', 'squat', false, true, false, 'Legs', '{"Hamstrings","Quads"}', '{}', '{"Bodyweight"}', 'This exercise requires a sturdy box or a chair. Simple stand ~6 inches in front of it and balance yourself on one leg. From here, begin squatting down in a smooth controlled motion while keeping your other leg straight out in front of you for balance. Slowly sit down on the box, pause for a 1 count and push back up with the working leg, while never letting your other leg touch the ground.', null, null, 'wger', 'c463f618-2777-4836-9c57-92a46d87cf1b', 'CC-BY-SA 4', 'jesusd'),
  ('Overhead Barbell Press', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Barbell"}', 'Setup: Stand with feet together and grip the bar slightly wider than shoulders.
Position: Rest the bar on your upper chest.
Press: Brace your core and push the bar straight up until your arms lock out.
Finish: Control the bar back down to your chest.
https://youtu.be/ZXpdJOLNoWw?si=u27cGyODoblXHBu1', 'https://wger.de/media/exercise-images/1893/7dbad19e-0616-41fd-9d7d-3e21649c0eea.png', null, 'wger', '2500c212-6f14-4a8d-a997-04e9e7c04116', 'CC-BY-SA 4', 'nishant0712'),
  ('Clean and Press', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{"Quads"}', '{"Barbell"}', 'The First Pull: Lift the bar from the floor to knee-height by driving with the legs, keeping the angle of your back constant.
The "Power" Position: As the bar reaches mid-thigh, explosively shrug and extend your hips to create vertical momentum.
The Quick Elbow Turnover: In the catch phase, rotate your elbows rapidly under the bar to create a "shelf" on your front deltoids.
The Vertical Press: Press the bar in a straight line; your head should shift slightly forward once the bar clears your forehead to reach full lockout.', 'https://wger.de/media/exercise-images/1901/046f0f42-0ed5-48c5-a9ee-41de25e3b6a0.png', null, 'wger', '2a125f64-1d10-4926-95ad-33a48e61b3d6', 'CC-BY-SA 4', 'nishant0712'),
  ('Weighted push-ups', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Triceps"}', '{"Bodyweight"}', 'Setup: Begin in a standard plank position with a weight plate balanced securely on your upper back.
Alignment: Maintain a straight line from your head to your heels, engaging your core to prevent your back from sagging.
Execution: Lower your body until your chest nearly touches the floor, keeping your elbows at a forty-five degrees.
Ascent: Press through your palms to return to the starting position, fully extending your arms.', 'https://wger.de/media/exercise-images/1902/d0c3f170-543c-4be4-bc70-5c6dc606406c.png', null, 'wger', '37abbe32-2fab-4818-8355-fffcff2dc3e3', 'CC-BY-SA 4', 'nishant0712'),
  ('Pec Deck', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{}', 'Pectoral issolation exercise - full range of motion is best with full contraction and slow negative', null, null, 'wger', '71b9da1a-ac07-49c8-8b2d-7179032181fd', 'CC-BY-SA 4', null),
  ('Hip Bridge', 'squat', false, true, true, 'Legs', '{"Glutes","Abs"}', '{"Obliquus externus abdominis"}', '{"Bodyweight"}', 'Get into bridge position, balance yourself on heels and start extending legs unilaterally.

Keep hip extended as much as possible.', null, null, 'wger', '6b127132-cc0b-4b40-ac8c-177a28ccb6e2', 'CC-BY-SA 4', 'cybro'),
  ('Unilateral Lunges', 'squat', true, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings"}', '{"Bodyweight"}', 'No stops during movement, hands on the hips.', null, null, 'wger', '2dd1cf54-b8e3-4769-9455-48120d7cc427', 'CC-BY-SA 4', 'cybro'),
  ('Butterfly Superman', 'pull_h', false, false, false, 'Back', '{"Trapezius"}', '{}', '{"Bodyweight"}', 'Lie on stomach, intertwine fingers behind the head and start raising your head and raise elbows as far as they go.', null, null, 'wger', 'de06856d-109d-4bef-acab-0918028cea36', 'CC-BY-SA 4', 'cybro'),
  ('Leg Wheel', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'Lay on the back and lift legs in perpendicular fashion, keeping the knees together.

Start making small circles in one direction with both of your knees with very small range of motion, focusing on abs and keeping your back in contact with the floor.', null, null, 'wger', '19d10f51-3e53-4d8f-b283-1d8d9a7d3543', 'CC-BY-SA 4', 'cybro'),
  ('Kneeling Superman', 'pull_h', false, false, true, 'Back', '{"Hamstrings","Trapezius"}', '{"Abs"}', '{"Bodyweight"}', 'Push one foot back until leg fully extended, concentrating on the having the foot high and pushed back as if pulled.

Extend arm forward with focus having the shoulder high up.

Unilateral and static hold.', null, null, 'wger', '00f4a2b1-b1ac-49e6-a657-1d27e46522fd', 'CC-BY-SA 4', 'cybro'),
  ('Cat Plank', 'squat', false, true, true, 'Legs', '{"Quads","Abs"}', '{"Shoulders"}', '{"Bodyweight"}', 'On your fours and raise the knees of the floor ever so slightly. 
Curl your back out and push back from your shoulders as to resemble a cat making itself look large.', null, null, 'wger', 'b02825ca-bbe4-4a07-a162-2b7a6c0a662b', 'CC-BY-SA 4', 'cybro'),
  ('Core Rotation', 'isolation', false, false, true, 'Abs', '{"Quads","Abs"}', '{"Obliquus externus abdominis","Serratus anterior"}', '{"Bodyweight"}', 'Sit back, raise feet above the ground with knees bent and start rotating left and right with hands touching the ground every move.', null, null, 'wger', '1b140999-e1fa-49b5-9f2b-690bac959db3', 'CC-BY-SA 4', 'cybro'),
  ('Unilateral Hip Thrust', 'hinge', true, true, false, 'Legs', '{"Glutes"}', '{"Abs"}', '{"Bodyweight"}', 'Extend one leg while laying down and start raising your body with one leg touching the ground through the heel.', null, null, 'wger', '139e3d1a-ccd5-46cd-b953-8db6cea7b005', 'CC-BY-SA 4', 'cybro'),
  ('Isometria alle parallele', 'push_v', false, false, false, 'Shoulders', '{"Chest","Trapezius"}', '{}', '{}', 'The parallel bars isometric hold is a static upper-body exercise performed on dip bars (parallel bars). Instead of moving up and down like in a traditional dip, you hold a fixed position under tension.', null, null, 'wger', '7a1e0cd7-0076-4d4d-b05f-1d114235f199', 'CC-BY-SA 4', null),
  ('Tuck planche', 'push_v', false, false, true, 'Shoulders', '{"Shoulders","Abs","Serratus anterior"}', '{"Obliquus externus abdominis","Chest","Triceps"}', '{"Bodyweight"}', 'Basic calisthenics progression for the full planche', 'https://wger.de/media/exercise-images/1916/e7d97b4b-9fe4-4378-aea3-5a9d93b6eb8d.png', null, 'wger', '3e9973f6-c218-4dd4-850b-da6f4f1622bb', 'CC-BY-SA 4', 'ISSACS'),
  ('Barbell Silverback Shrug', 'push_v', false, false, false, 'Shoulders', '{"Trapezius"}', '{}', '{"Barbell"}', 'Stand with your feet shoulder width apart holding the barbell with both hands in front just past shoulder width.
Bend forward at the hips with a slight bend in your knees, keeping your back straight.
Engage your shoulder blades, as if you are trying to touch them together.
Release the shrug.
Description taken from MuscleWiki', null, null, 'wger', '64b50772-c73d-4833-8518-947a648fa623', 'CC-BY-SA 4', null),
  ('Wide-grip Pulldown', 'pull_v', false, false, true, 'Back', '{"Lats"}', '{"Shoulders","Brachialis","Serratus anterior","Trapezius"}', '{"Cable machine"}', 'Starting position:

Arms extended overhead, feeling a stretch in your lats.
Keep your shoulders depressed (don’t shrug upward).

Pulling phase (concentric):

Pull the bar down to your upper chest or collarbone area by driving your elbows down and back.
Keep your chest lifted and squeeze your shoulder blades together at the bottom.', null, null, 'wger', '55b9d286-c4cc-4a29-97ad-58cb13c2bb7e', 'CC-BY-SA 3', 'tuckerm'),
  ('Inverted Lat Pull Down', 'pull_v', false, false, true, 'Back', '{"Lats","Trapezius"}', '{"Biceps","Brachialis","Obliquus externus abdominis","Abs","Serratus anterior"}', '{"Pull-up bar"}', 'The Inverted Lat Pull Down (most commonly known as the Reverse Grip Lat Pull Down) is a variation of the standard exercise that uses an underhand (supinated) grip with hands at shoulder-width. This position shifts more emphasis to the lower lats and increases biceps involvement, often allowing for a greater range of motion and a deeper squeeze at the bottom of the movement.', null, null, 'wger', '1639425c-7dc6-4776-b039-47ef14a328ee', 'CC-BY-SA 4', 'amaesc'),
  ('Assisted Pull-Up', 'pull_v', false, false, true, 'Back', '{"Lats","Trapezius"}', '{"Shoulders","Biceps","Abs","Serratus anterior"}', '{"Resistance band"}', 'The Assisted Pull-Up is a compound vertical pulling exercise performed on a machine with a counterweight platform or by using resistance bands. It mimics the mechanics of a standard pull-up but reduces the total weight you have to lift, making it an excellent tool for building functional strength and perfecting your technique.', null, null, 'wger', '8bc4c616-e76b-4291-9074-186ecbbb3cfd', 'CC-BY-SA 4', 'amaesc'),
  ('Tricep Rope Pushdowns', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{"Lats"}', '{"Cable machine"}', 'Setup: Stand facing the cable, feet shoulder-width apart, with a slight forward lean.
Grip: Hold the rope with palms facing each other and elbows tucked tight to your ribs.
Execution: Push the rope down until arms are fully straight, pulling the ends apart at the bottom.
Control: Keep upper arms still and return to the start with a slow, controlled motion.', 'https://wger.de/media/exercise-images/1900/a8243245-8f8f-4e2b-93ca-694d416cb11d.png', null, 'wger', 'fc608f0e-d754-4911-ae59-8856952e7064', 'CC-BY-SA 4', 'nishant0712'),
  ('Dumbbell Curl', 'isolation', false, false, true, 'Arms', '{"Biceps","Brachialis"}', '{"Shoulders","Abs"}', '{"Dumbbell"}', 'The Dumbbell Curl is a classic isolation exercise for the arms. Unlike the Hammer Curl, it involves rotating your wrists (supination) as you lift the weights, which allows for a full contraction of the biceps.', null, null, 'wger', '99846da5-5dc8-4de1-ba55-ae2b4c03c30d', 'CC-BY-SA 4', 'amaesc'),
  ('Pullback', 'pull_h', false, false, true, 'Back', '{"Biceps","Lats"}', '{"Brachialis"}', '{"Cable machine"}', 'Set weight and grip for the cables in the cage. Take a few steps away, bend over, pull and extend the back at the same time.', null, null, 'wger', '289bd40b-e3dd-4217-8670-e475771a0ea7', 'CC-BY-SA 4', 'cybro'),
  ('Abdominal Crunch', 'isolation', false, false, true, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis","Serratus anterior"}', '{"Gym mat"}', 'The Abdominal Crunch is a classic core isolation exercise performed on the floor or a mat. Unlike a full sit-up, it involves a smaller range of motion where you only lift your shoulders and upper back off the ground, keeping your lower back pressed firmly against the floor.', null, null, 'wger', '2ac901e6-f0c2-416f-998f-e01e00fe0aa1', 'CC-BY-SA 4', 'amaesc'),
  ('Belt Squat', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings"}', '{}', 'Belt Squat: a squat variation done with a belt attached to a loading machine or platform so the weight is supported at the hips instead of on the spine. It mainly trains the quads and glutes, with much less lower-back fatigue than a barbell squat. Use a full range of motion, keep the torso upright, and drive through the mid-foot.', null, null, 'wger', 'e9f3446f-ca98-4bf2-817c-0dacd123cecd', 'CC-BY-SA 4', null),
  ('Arnold Shoulder Press', 'push_v', false, false, true, 'Shoulders', '{"Shoulders"}', '{"Trapezius","Triceps"}', '{"Dumbbell"}', 'Very common shoulder exercise.

As shown here: https://www.youtube.com/watch?v=vj2w851ZHRM', null, null, 'wger', 'f24cb758-9c0d-42d4-ad9e-6025c527dd13', 'CC-BY-SA 3', 'trzr23'),
  ('Barbell Lunges Standing', 'squat', false, true, false, 'Legs', '{"Quads"}', '{"Glutes"}', '{"Barbell"}', 'Put barbell on the back of your shoulders. Stand upright, then take the first step forward. Step should bring you forward so that your supporting legs knee can touch the floor. Then stand back up and repeat with the other leg.

Remember to keep good posture.', null, 'https://wger.de/media/exercise-video/46/200d9889-322f-476a-a47b-f15a1a97934a.MOV', 'wger', '04e7d7e4-f8d2-406d-97df-3df3bceec22c', 'CC-BY-SA 4', 'Mikko Ruohola'),
  ('Barbell Hack Squats', 'squat', false, true, true, 'Legs', '{"Quads"}', '{"Hamstrings","Glutes"}', '{"Barbell"}', 'Perform leg squats with barbell behind your legs', null, null, 'wger', 'dae6f6ed-9408-4e62-a59a-1a33f4e8ab36', 'CC-BY-SA 4', 'BePieToday'),
  ('Barbell Triceps Extension', 'isolation', false, false, true, 'Arms', '{"Triceps"}', '{"Shoulders","Chest"}', '{"Barbell"}', 'Position barbell overhead with narrow overhand grip.

Lower forearm behind upper arm with elbows remaining overhead. Extend forearm overhead. Lower and repeat.', 'https://wger.de/media/exercise-images/50/695ced5c-9961-4076-add2-cb250d01089e.png', null, 'wger', '13234b53-ea0c-41f1-9069-776865ea8eff', 'CC-BY-SA 4', 'sevae'),
  ('Dumbbell Push-Up', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Triceps"}', '{"Dumbbell"}', 'Normal Push-ups on Dumbbells, this brings a further range of movement', null, null, 'wger', '68e5eae7-7fd0-4d69-9b50-d0df15feac91', 'CC-BY-SA 4', null),
  ('Legend Chest Press', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Triceps"}', '{}', 'Plate-loaded chest press machine from Legend Fitness LeverEdge line.', null, null, 'wger', '2e96e572-ddb4-4251-a812-ccf03ea677a6', 'CC-BY-SA 4', null),
  ('3008 Abdominal Crunch', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'This is especially for the gym80 device 3008 Abdominal Crunch.', null, null, 'wger', '7870ad8d-a0c1-4e3a-a4fe-a237908eba9b', 'CC-BY-SA 4', null),
  ('Seated Cable chest fly', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Cable machine"}', 'Place a bench between two cable pulleys and adjust the pulleys so they are at chest/shoulder height when you are seated.
Grab the handles with a neutral grip and lean against the upright backrest.
Bring your arms together in front of your chest in a controlled motion, focusing on squeezing your chest muscles. Keep your elbows slightly bent throughout the movement.
Pause briefly at the top position.
Slowly lower your arms back to the starting position while maintaining control of the movement.
Repeat for reps.', 'https://wger.de/media/exercise-images/1922/eb750ee5-3220-4128-aef1-5e2f1ccff40a.webp', null, 'wger', '139772c6-e401-4281-8aa6-c7ff7fb49f6a', 'CC-BY-SA 4', 'shushu'),
  ('Seated V-Grip Row', 'pull_h', false, false, true, 'Back', '{"Lats","Trapezius"}', '{"Shoulders","Biceps","Abs","Serratus anterior"}', '{"Cable machine"}', 'The Seated V-Grip Row is a compound pulling exercise performed on a cable machine using a close-grip "V" handle. While seated with your feet braced, you pull the handle toward your midsection, focusing on back thickness and mid-back development.', null, null, 'wger', 'b2ca4a13-6fe2-4c4f-85b2-dcb5af28d2be', 'CC-BY-SA 4', 'amaesc'),
  ('Dead Bug (Core L1)', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{"Bodyweight"}', 'Vasco custom dead bug - foundational deep core stability and anti-extension. Teaches lumbar-pelvic dissociation, breath-coordination, and proximal stability for distal mobility. Prerequisite for all core training.', null, null, 'wger', '816d8bff-73c0-436c-8479-e0145f2324fc', 'CC-BY-SA 4', 'Vasco Custom'),
  ('Biceps Curls With Dumbbell', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{"Brachialis"}', '{"Dumbbell"}', 'Hold two dumbbells, the arms are streched, the hands are on your side, the palms face inwards. Bend the arms and bring the weight with a fast movement up. At the same time, rotate your arms by 90 degrees at the very beginning of the movement. At the highest point, rotate a little the weights further outwards. Without a pause, bring them down, slowly.

Don''t allow your body to swing during the exercise, all work is done by the biceps, which are the only mucles that should move (pay attention to the elbows).', 'https://wger.de/media/exercise-images/81/Biceps-curl-1.png', 'https://wger.de/media/exercise-video/92/8bfb917c-3d0d-49b9-8073-5d7e01c1b894.MOV', 'wger', '1ae6a28d-10e7-4ecf-af4f-905f8193e2c6', 'CC-BY-SA 3', 'wger.de'),
  ('Bent Over Rowing', 'pull_h', false, false, true, 'Back', '{"Lats"}', '{"Shoulders","Biceps"}', '{"Barbell"}', 'Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.
Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.
Then inhale and slowly lower the barbell back to the starting position.
Repeat for the recommended amount of repetitions.', 'https://wger.de/media/exercise-images/109/Barbell-rear-delt-row-1.png', null, 'wger', '4af6dbd9-8991-484b-9810-68f117c21edf', 'CC-BY-SA 3', 'wger.de'),
  ('Bent Over Dumbbell Rows', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{"Bench","Dumbbell"}', 'With dumbbells in hand, bend at the hip until hands hang just below the knees (similar to straight-legged-deadlift starting position). Keep upper body angle constant while contracting your lats to pull you ellbows back pinching the shoulder blades at the top. Try not to stand up with every rep, check hands go below knees on every rep.', 'https://wger.de/media/exercise-images/81/a751a438-ae2d-4751-8d61-cef0e9292174.png', null, 'wger', '94a5c406-7bcd-47f3-9687-bdf92a763932', 'CC-BY-SA 4', 'sebk'),
  ('Biceps Curls With SZ-bar', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{"Brachialis"}', '{"SZ-Bar"}', 'Hold the SZ-bar shoulder-wide, the back is straight, the shoulders slightly back, the arms are streched. Bend the arms, bringing the weight up, with a fast movement. Without pausing, let down the bar with a slow and controlled movement.

Don''t allow your body to swing during the exercise, all work is done by the biceps, which are the only mucles that should move (pay attention to the elbows).', 'https://wger.de/media/exercise-images/94/6dee2f60-aea2-4f2d-9bf6-aef50c4f9483.png', null, 'wger', '42227131-9b1e-4220-b082-c523f0651057', 'CC-BY-SA 3', 'wger.de'),
  ('Benchpress Dumbbells', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Triceps"}', '{"Bench","Dumbbell"}', 'Setup and Starting Position: Sit at the end of a flat bench with a dumbbell resting vertically against each thigh. Carefully lean back while driving the dumbbells toward your chest with your knees.

The “Leg Drive” and Posture: Plant your feet firmly on the floor. Retract your shoulder blades (press them together against the bench) and maintain a slight natural lumbar curve.

Starting Position: Push the dumbbells toward the ceiling. Your wrists should be aligned with your elbows. Rotate the dumbbells slightly inward (about 45 degrees) so that your elbows do not splay out too far to the sides, thereby protecting your shoulders.

Eccentric Phase (Lowering): Lower the dumbbells in a controlled manner toward the sides of your chest. Your elbows should lower at an angle of about 45–60 degrees relative to your body. Feel the stretch in the lower part of your chest.

Concentric Phase (Lift): Push the weight upward in a slight arc (toward the center), without letting the dumbbells collide at the top or fully locking out your elbows to maintain muscle tension. Exhale as you lift.

Translated with DeepL.com (free version)', 'https://wger.de/media/exercise-images/97/Dumbbell-bench-press-1.png', 'https://wger.de/media/exercise-video/75/080c799b-8afd-4130-8d72-9cef0cd79f54.MOV', 'wger', '28321cf3-70e6-48a4-ade1-d11382180cb3', 'CC-BY-SA 3', 'wger.de'),
  ('Biceps Curls With Barbell', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{"Brachialis"}', '{"Barbell"}', 'Hold the Barbell shoulder-wide, the back is straight, the shoulders slightly back, the arms are streched. Bend the arms, bringing the weight up, with a fast movement. Without pausing, let down the bar with a slow and controlled movement.

Don''t allow your body to swing during the exercise, all work is done by the biceps, which are the only mucles that should move (pay attention to the elbows).', 'https://wger.de/media/exercise-images/74/Bicep-curls-1.png', 'https://wger.de/media/exercise-video/91/483f4bff-e108-41f1-8e7b-0caf24952552.MOV', 'wger', '7b99a081-6b1a-4aa5-b86a-5a935d083a35', 'CC-BY-SA 3', 'wger.de'),
  ('Decline Bench Leg Raise', 'push_h', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Incline bench"}', 'Setup: Lie on a decline bench with your head at the top and grip the handles.
The Start: Extend legs fully, keeping them slightly elevated to engage your core.
The Lift: Raise your legs toward the ceiling using your abs, not momentum.
The Squeeze: Pause and contract your lower abdominals at the top.
The Return: Lower your legs slowly to the starting position with control.', 'https://wger.de/media/exercise-images/1889/bc51ef67-0c12-4340-a36c-42ef722778dd.png', null, 'wger', '9ac4813e-79a6-4a4d-ab93-9cfa5bf7b8fa', 'CC-BY-SA 4', 'nishant0712'),
  ('Bench Press', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Triceps"}', '{"Barbell","Bench"}', 'Lay down on a bench, the bar should be directly above your eyes, the knees are somewhat angled and the feet are firmly on the floor. Concentrate, breath deeply and grab the bar more than shoulder wide. Bring it slowly down till it briefly touches your chest at the height of your nipples. Push the bar up.

If you train with a high weight it is advisable to have a spotter that can help you up if you can''t lift the weight on your own.

With the width of the grip you can also control which part of the chest is trained more:

wide grip: outer chest muscles
narrow grip: inner chest muscles and triceps', 'https://wger.de/media/exercise-images/192/Bench-press-1.png', 'https://wger.de/media/exercise-video/73/2bdb390c-312c-4497-a722-5eed2c823e5a.MOV', 'wger', '3717d144-7815-4a97-9a56-956fb889c996', 'CC-BY-SA 3', 'sistab2'),
  ('Bench Press Narrow Grip', 'push_h', false, false, true, 'Arms', '{"Triceps"}', '{"Shoulders","Chest"}', '{"Barbell","Bench"}', 'Setup: Lie flat on the bench and grip the bar at shoulder-width (closer than a standard bench press).
Descent: Lower the bar with control to your lower chest.
Form: Keep your elbows tucked in tight against your torso—do not let them flare out.
Ascent: Press the bar straight back up, squeezing your triceps at the top.', 'https://wger.de/media/exercise-images/88/Narrow-grip-bench-press-1.png', null, 'wger', '3db63138-a047-4a4d-b616-1a0b7dfca105', 'CC-BY-SA 3', 'wger.de'),
  ('Lateral Rows on Cable, One Armed', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Cable machine"}', 'Set cable at waist height, start with arm across your belly and move han over and out too other side, one arm at the time.', 'https://wger.de/media/exercise-images/349/9d969203-9cb6-4d47-9c31-fef53bfe1de5.png', 'https://wger.de/media/exercise-video/349/9896d82e-d8b6-48af-bdd5-b8545dc523e9.MOV', 'wger', '57263316-6f34-4539-952b-b07e09bac3ba', 'CC-BY-SA 3', 'wger.de'),
  ('Decline Bench Press Barbell', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Barbell","Bench"}', 'Lay down on a decline bench, the bar should be directly above your eyes, the knees are somewhat angled and the feet are firmly on the floor. Concentrate, breath deeply and grab the bar more than shoulder wide. Bring it slowly down till it briefly touches your chest at the height of your nipples. Push the bar up.', 'https://wger.de/media/exercise-images/100/Decline-bench-press-1.png', null, 'wger', 'bcd801f0-9a38-4615-a91c-900153c8c234', 'CC-BY-SA 3', 'wger.de'),
  ('Decline Bench Press Dumbbell', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Bench","Dumbbell"}', 'Take two dumbbells and sit on a decline bench, the feet are firmly on the floor, the head is resting the bench. Hold the weights next to the chest, at the height of your nipples and press them up till the arms are stretched. Let the weight slowly and controlled down.', null, null, 'wger', 'dda69c96-62d4-4690-aa07-a4a0f6ceb63a', 'CC-BY-SA 3', 'wger.de'),
  ('Seated Hip Adduction', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{}', 'Starting Position: Sit on the machine with your knees inward and against the pads. Pull the pin to release the pads. Grab the handles on the sides.b', 'https://wger.de/media/exercise-images/12/4a42cc6f-648d-40cc-a72a-c49dd47e1667.webp', 'https://wger.de/media/exercise-video/12/5148c579-5df2-4618-9a7b-a2e29ac4dd7d.MOV', 'wger', '53906cd1-61f1-4d56-ac60-e4fcc5824861', 'CC-BY-SA 3', 'flori'),
  ('Abdominal Stabilization', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{"Gym mat"}', null, null, null, 'wger', '03db11cc-8079-463c-9399-6f346b100ce6', 'CC-BY-SA 3', 'andikeller'),
  ('Handstand Pushup', 'push_v', false, false, true, 'Shoulders', '{"Shoulders","Triceps"}', '{"Trapezius"}', '{"Bodyweight"}', 'The handstand push-up (press-up) - also called the vertical push-up (press-up) or the inverted push-up (press-up) also called commandos- is a type of push-up exercise where the body is positioned in a handstand. For a true handstand, the exercise is performed free-standing, held in the air. To prepare the strength until one has built adequate balance, the feet are often placed against a wall, held by a partner, or secured in some other way from falling. Handstand pushups require significant strength, as well as balance and control if performed free-standing.', 'https://wger.de/media/exercise-images/282/f6121ac9-330e-4ed7-8219-91ce246bf871.png', null, 'wger', '7704e810-c05d-47cc-a384-265e0231a497', 'CC0', 'BFad07'),
  ('Dips', 'push_h', false, false, false, 'Chest', '{"Chest","Triceps"}', '{}', '{"Bodyweight"}', 'A dip is an upper-body strength exercise. Narrow, shoulder-width dips primarily train the triceps, with major synergists being the anterior deltoid, the pectoralis muscles (sternal, clavicular, and minor), and the rhomboid muscles of the back (in that order).[1] Wide arm training places additional emphasis on the pectoral muscles, similar in respect to the way a wide grip bench press would focus more on the pectorals and less on the triceps.', 'https://wger.de/media/exercise-images/194/34600351-8b0b-4cb0-8daa-583537be15b0.png', 'https://wger.de/media/exercise-video/194/d039ec90-474d-47a9-a3ad-bf0b00828c82.MP4', 'wger', '09dd3e3c-e53a-4e2c-a2e3-645d334f53e2', 'CC0', 'BFad07'),
  ('Fly With Dumbbells, Decline Bench', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Bench","Dumbbell"}', 'The exercise is the same as with a regular bench:

Take two dumbbells and lay on a bench, make sure the feet are firmly on the ground and your back is not arched, but has good contact with the bench. The arms are stretched in front of you, about shoulder wide. Bend now the arms a bit and let them down with a half-circle movement to the side. Without changing the angle of the elbow bring them in a fluid movement back up.', null, null, 'wger', '55d0a5ec-b147-40c3-aa77-314e61c93689', 'CC-BY-SA 3', 'wger.de'),
  ('Ball crunches', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{}', null, null, null, 'wger', '36391719-d4ad-4e0f-991f-8eafd5947108', 'CC-BY-SA 4', 'Konsumopfer'),
  ('Biceps Curl With Cable', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Cable machine"}', 'Stand around 30 - 40cm away from the cable, the feet are firmly on the floor. Take the bar and lift the weight with a fast movements. Lower the weight as with the dumbbell curls slowly and controlled.', 'https://wger.de/media/exercise-images/129/Standing-biceps-curl-1.png', 'https://wger.de/media/exercise-video/95/ab770931-47d3-44fd-aef0-ac7a64c3b794.MOV', 'wger', 'bcb7020c-8678-496d-8f4d-aad0e233a5bd', 'CC-BY-SA 3', 'wger.de'),
  ('Fly With Cable', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{"Cable machine"}', 'cable machine, two steps forward, straight back', 'https://wger.de/media/exercise-images/122/Incline-cable-flyes-1.png', null, 'wger', '07c5b9f4-2be5-4a3d-b6d2-16235da1ae3a', 'CC-BY-SA 3', 'wger.de'),
  ('Hammercurls on Cable', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{"Brachialis"}', '{"Cable machine"}', 'Take a cable in your hands (palms parallel, point to each other), the body is straight. Bend the arms and bring the weight up with a fast movement. Without any pause bring it back down with a slow, controlled movement, but don''t stretch completely your arms.

Don''t swing your body during the exercise, the biceps should do all the work here. The elbows are at your side and don''t move.', 'https://wger.de/media/exercise-images/138/Hammer-curls-with-rope-1.png', 'https://wger.de/media/exercise-video/275/af1fff93-eb58-4ba7-97a4-b38ee67853b4.MOV', 'wger', '04365177-e078-489b-983a-8ac61b7346f1', 'CC-BY-SA 3', 'wger.de'),
  ('Glute Bridge', 'hinge', false, true, false, 'Legs', '{"Glutes"}', '{"Hamstrings"}', '{}', 'Lie on you back with your hips and knees flexed, feet on the ground. From this position, raise your butt off of the ground to a height where your body makes a straight line from your knees to your shoulders. To make the exercise more intense, you can add weight by letting a barbell rest on your hips as you complete the motion, or you can put your feet on a slightly higher surface such as a step or a bench.', null, null, 'wger', 'ceb0c2d0-06ac-4a49-89e7-8d7b1c1e5672', 'CC-BY-SA 4', 'tdprice12'),
  ('Close-grip Lat Pull Down', 'pull_v', false, false, false, 'Back', '{"Lats"}', '{}', '{}', 'Grip the pull-down bar with your hands closer than shoulder width apart, with your palms facing away from you. Lean back slightly. Pull the bar down towards your chest, keeping your elbows close to your sides as you come down. Pull your shoulders back at the end of the motion.', 'https://wger.de/media/exercise-images/158/0d51a0f2-622f-434b-beb8-1a003c54712a.png', null, 'wger', '63fbb8e5-6ebc-4def-8844-3e65e097213b', 'CC-BY-SA 3', 'tuckerm'),
  ('Braced Squat', 'squat', false, true, false, 'Legs', '{"Quads"}', '{"Glutes"}', '{}', 'Stand with feet slightly wider than shoulder-width apart, while standing as tall as you can.

Grab a weight plate and hold it out in front of your body with arms straight out. Keep your core tight and stand with a natural arch in your back.

Now, push hips back and bend knees down into a squat as far as you can. Hold for a few moments and bring yourself back up to the starting position.', null, null, 'wger', '8c6428f3-d41d-4ffc-8444-bb9b823bc42b', 'CC-BY-SA 4', 'sevae'),
  ('Calf Press Using Leg Press Machine', 'squat', false, true, false, 'Calves', '{"Calves","Soleus"}', '{}', '{}', 'Put the balls of your feet on an extended leg press pad. Use your calves to press the weight by flexing your feet/toes into a pointed position, and releasing back into a relaxed position.

This exercise builds mass and strength in the Gastrocnemius and Soleus muscles as well, if not better, than any calf exercise.', 'https://wger.de/media/exercise-images/146/8b284904-d072-4381-a256-4c81d8fd9c1f.png', null, 'wger', '0d79f259-3b28-4258-8a08-cffec062a710', 'CC-BY-SA 4', 'nate303303'),
  ('Calf Raises on Hackenschmitt Machine', 'isolation', false, true, false, 'Calves', '{"Calves"}', '{"Soleus"}', '{}', 'Place yourself on the machine with your back firmly against the backrest, the feet are on the platform for calf raises. Check that the feet are half free and that you can completely stretch the calf muscles down.

With straight knees pull up your weight as much as you can. Go with a fluid movement down till the calves are completely stretched. Repeat.', null, null, 'wger', '95a9cc46-270e-45f2-8a17-5665a23ff70b', 'CC-BY-SA 3', 'wger.de'),
  ('Butterfly Narrow Grip', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{}', 'The movement is the same as with a regular butterfly, only that the grip is narrow:

Sit on the butterfly machine, the feet have a good contact with the floor, the upper arms are parallel to the floor. Press your arms together till the handles are practically together (but aren''t!). Go slowly back. The weights should stay all the time in the air.', null, null, 'wger', '80ff0a3a-ae45-497d-8c27-2b12e3b6e1b8', 'CC-BY-SA 3', 'wger.de'),
  ('Butterfly', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Shoulders"}', '{}', 'Sit on the butterfly machine, the feet have a good contact with the floor, the upper arms are parallel to the floor. Press your arms together till the handles are practically together (but aren''t!). Go slowly back. The weights should stay all the time in the air.', 'https://wger.de/media/exercise-images/98/Butterfly-machine-2.png', null, 'wger', '99449eae-0eae-44ab-a57f-fc094bbdda13', 'CC-BY-SA 3', 'wger.de'),
  ('Crunches on Machine', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{}', 'The procedure is very similar as for regular crunches, only with the additional weight of the machine. Sit on the machine, put both feet firmly on the ground. Grab the to the weights, cables, etc. and do a rolling motion forwards (the spine should ideally lose touch vertebra by vertebra). Slowly return to the starting position.', null, null, 'wger', '401989e0-64c3-459d-bc47-2c171ab4f41d', 'CC-BY-SA 3', 'wger.de'),
  ('Incline Crunches', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Incline bench"}', 'Lay down on your back on a inclined bench, feet are on one end of the bench. Ask a partner or use some other help (barbell, etc.) to keep them fixed, your hands are behind your head. From this position move your upper body up till your head or elbows touch your knees. Do this movement by rolling up your back.', 'https://wger.de/media/exercise-images/56/Decline-crunch-1.png', null, 'wger', '7de7b8a8-313d-465f-bb22-8527ae45110a', 'CC-BY-SA 3', 'wger.de')
on conflict (name) do update set
  category          = excluded.category,
  primary_muscles   = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  equipment         = excluded.equipment,
  description       = excluded.description,
  image_url         = excluded.image_url,
  video_url         = excluded.video_url,
  source            = excluded.source,
  source_id         = excluded.source_id,
  license           = excluded.license,
  license_author    = excluded.license_author;
