-- Migration: seed the exercise library from wger (part 1 of 7)
--
-- GENERATED by scripts/build-exercise-seed.mjs — do not hand-edit. Re-run the
-- script to regenerate.
--
-- Source: https://wger.de (open exercise database, fetched via its public API)
-- Licences present: CC-BY-SA 4, CC0, CC-BY-SA 3
-- Each row carries its own license and license_author, which must be honoured
-- wherever its description or image is displayed. CC-BY-SA in particular
-- requires attribution and share-alike on the text.
--
-- NOT sourced from ExRx.net: that content is copyrighted and the site refuses
-- automated access. Its taxonomy — browse by body part, narrow by equipment —
-- is a structure rather than an expression, and is what this follows.
--
-- Split into 7 parts because the Supabase SQL editor truncates a
-- very large paste, and a cut inside a description leaves an unterminated
-- string literal. Run the parts in order; each is independent and re-runnable.
-- This part: 120 exercises.
--
-- Exercises kept: 722 of 863 fetched
-- With a description: 700 · with an image: 232 · with a video: 45
-- By category: Legs 166, Back 128, Arms 121, Abs 102, Shoulders 90, Chest 75, Cardio 31, Calves 9
-- Skipped 128: no primary muscle
-- Skipped 13: no usable name
--
-- pattern and unilateral are INFERRED from the exercise name, because wger
-- records neither. Both feed real maths — §4.3 picks the load increment from
-- pattern, §4.4 totals volume by it, and §4.1 keeps unilateral sets out of
-- bilateral PR comparisons — so check the ones you actually train. They are
-- heuristics over names, not facts from the source.
-- Inferred unilateral: 42

insert into public.exercises
  (name, pattern, unilateral, lower_body, compound,
   category, primary_muscles, secondary_muscles, equipment,
   description, image_url, video_url, source, source_id, license, license_author)
values
  ('Step Jack', null, false, false, true, 'Cardio', '{"Quads"}', '{"Shoulders","Glutes","Obliquus externus abdominis","Abs"}', '{"Bodyweight"}', 'The Step Jack is a low-impact plyometric-style move that provides cardiovascular benefits without the joint stress of jumping. It works the entire body, specifically targeting the legs, core, and shoulders. This move is ideal for beginners, individuals with joint sensitivities, or as a dynamic warm-up to gradually elevate the heart rate.
Notes (Instructions):

​Stand upright with your feet together and arms at your sides.
​Step your right foot out to the side while simultaneously swinging both arms up above your head.
Bring your right foot back to the center and lower your arms.
​Immediately repeat the movement, stepping out with your left foot.
​Continue alternating sides at a steady, rhythmic pace.', 'https://wger.de/media/exercise-images/1962/74041371-1019-4f89-9ebe-cec792484a46.png', null, 'wger', '2f10d91f-6c12-471b-bb9e-80840a56ce01', 'CC-BY-SA 4', 'Anon#2'),
  ('Slow Squat', 'squat', false, true, true, 'Legs', '{"Quads"}', '{"Hamstrings","Glutes","Abs"}', '{"Bodyweight"}', '​A tempo-based squat that uses controlled movement to increase muscle tension and improve lower-body stability.

​Lower: Descend slowly for 3 seconds.
​Pause: Hold at the bottom for 1 second.
​Stand: Return to the starting position at a normal pace.
Form: Keep your chest up and weight in your heels.', 'https://wger.de/media/exercise-images/1963/db285682-1ab3-4be0-ae00-5117ecce1ee6.png', null, 'wger', '2398e14f-02a6-4fdc-9f69-029e52dfe033', 'CC-BY-SA 4', 'Anon#2'),
  ('Wide Push-Up', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Abs","Triceps"}', '{"Bodyweight"}', '​A push-up variation with a wider hand placement to increase the emphasis on the outer chest muscles and shoulders.

​Setup: Place hands wider than shoulder-width apart on the floor.
Lower: Descend until your chest nearly touches the floor, keeping your core tight.
​Push: Drive through your palms to return to the start position.
​Form: Don''t let your lower back sag; keep a straight line from head to heels.', null, null, 'wger', '1842e1be-ac67-4f34-a527-4ca2b72d8e11', 'CC-BY-SA 4', 'Anon#2'),
  ('Marching High Knees', 'squat', false, true, true, 'Legs', '{"Quads"}', '{"Calves","Glutes","Abs"}', '{"Bodyweight"}', 'A low-impact cardio and mobility exercise that strengthens the hip flexors and improves balance.

​Movement: Stand tall and lift one knee toward your chest as high as comfortable.
​Arms: Swing the opposite arm forward as you lift your knee, similar to a walking motion.
​Core: Keep your abs engaged to maintain an upright posture.
​Pace: Perform the movement with control, alternating legs rhythmically.', 'https://wger.de/media/exercise-images/1965/03c08a42-dedb-4a46-8d15-acaf497a35a2.png', null, 'wger', 'fad49a13-b2a0-4b1f-b262-29b32248257d', 'CC-BY-SA 4', 'Anon#2'),
  ('Band Terminal Knee extension', 'squat', false, true, false, 'Legs', '{"Quads"}', '{}', '{"Resistance band"}', 'This is an end range strengthening exercise for the knee extensors. Start by looping a band around the back of one knee and anchoring the other end to a stable surface in front of you. Stand in a split stance with the banded knee bent and placed as the front leg. Straighten the knee to pull against the bands resistance and maintain a contraction in your quadriceps for up to 5 seconds before releasing.', 'https://wger.de/media/exercise-images/2494/02f1ae86-d374-4b5a-b314-a76c487ea1e9.png', null, 'wger', '3096b34e-1781-4f99-8187-d9acac8e712b', 'CC-BY-SA 4', 'Rehab Hero'),
  ('Lento avanti seduto', 'pull_h', false, false, false, 'Back', '{"Shoulders"}', '{}', '{"Dumbbell"}', 'slow controlled seated forward exercise with dumbbells', null, null, 'wger', '85cb0a1b-250e-400b-892b-50186dac0777', 'CC-BY-SA 4', 'Cf'),
  ('Single-arm dumbbell shoulder press', 'push_v', true, false, true, 'Shoulders', '{"Shoulders"}', '{"Abs","Serratus anterior","Trapezius","Triceps"}', '{"Dumbbell"}', 'Press the dumbbell vertically overhead in a controlled motion until your arm is fully extended, without locking the elbow. Slowly lower the dumbbell back to the starting position at shoulder height.', 'https://wger.de/media/exercise-images/1968/cd92e973-a0d9-4e5f-9011-5369012598d3.png', null, 'wger', '9dfce8f0-39fc-4204-9f84-500ec42074e9', 'CC-BY-SA 4', 'evtimovgeorg'),
  ('Kettlebell sumo high pull', 'pull_h', false, false, true, 'Back', '{"Trapezius"}', '{"Shoulders","Hamstrings","Glutes","Quads"}', '{"Kettlebell"}', 'A compound exercise combining elements of a sumo deadlift and a high pull. It targets the posterior chain, particularly the glutes, hamstrings, and upper back. The sumo stance increases hip engagement, while the high pull adds an explosive element, promoting power development.

Stand upright overtop of a kettlebell with your feet wider than shoulder-width apart angled out slightly.
Maintain a braced core and neutral spine throughout the exercise.
Hinge your hips backward and extend your arms to grab ahold the kettlebell with a double overhand grip.
With you lower legs nearly vertical to the ground, extend your hips to raise the kettlebell with your elbows high keeping it close to your body.
Once the kettlebell has reached shoulder height, lower back to the starting position.', null, null, 'wger', '03960339-fe14-4670-a7b3-4974b859ed37', 'CC-BY-SA 4', 'wgerpott'),
  ('Single Arm Plank to Row', 'pull_h', true, false, true, 'Back', '{"Shoulders","Biceps","Brachialis","Lats","Obliquus externus abdominis","Abs","Serratus anterior"}', '{}', '{"Kettlebell"}', 'Start position as row, extend to plank and back. Finish with row and repeat', 'https://wger.de/media/exercise-images/1022/f74644fa-f43e-46bd-8603-6e3a2ee8ee2d.jpg', null, 'wger', '768e0703-a04d-4d97-89ce-a49cd6be2b06', 'CC-BY-SA 4', null),
  ('Hip Airplane', 'squat', false, true, true, 'Legs', '{"Glutes"}', '{"Hamstrings","Calves","Soleus"}', '{"Kettlebell"}', 'Stand on one leg and lean your upper body slightly forward while keeping your back straight. Extend the free leg behind you so that your torso and leg form roughly one line. Slowly open your hip to the side by rotating your pelvis and upper body in a controlled way. Then close the hip again and return to the starting position.

The movement should mainly come from the hip. Keep your standing foot stable and avoid letting your knee collapse inward.', null, null, 'wger', '553fb643-32f0-447f-aecb-cdf75398d742', 'CC-BY-SA 4', 'TobiasFalk'),
  ('YTW Raises', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Bodyweight"}', 'The YTW exercise for scapular retraction is designed to strengthen the inter-scapular muscles between your shoulder blades, to help retract or pull your shoulders back, helping to maintain proper upright posture.', null, null, 'wger', '142fcef5-63a7-4d30-81e4-bc9d7073fe99', 'CC-BY-SA 4', 'probablyforging'),
  ('Kettlebell Swing', 'hinge', false, true, true, 'Legs', '{"Shoulders","Glutes"}', '{"Quads","Abs","Trapezius"}', '{"Kettlebell"}', 'While kettlebell swings are a full-body workout, they mostly target the muscles along the posterior chain (back of the body). The main muscles used are the glutes, hamstrings, spinal erectors, and muscles of the upper back.', 'https://wger.de/media/exercise-images/960/da4d0560-da89-4bb5-b91f-746458fb04ad.png', null, 'wger', 'd813ef7c-b10a-4c5c-ba55-6b9518e7ff4c', 'CC-BY-SA 4', 'clafal'),
  ('Box squat', 'squat', false, true, true, 'Legs', '{"Glutes","Quads","Soleus"}', '{}', '{"Bodyweight"}', 'Set up the box: Position the box behind you, about 3 feet from a squat rack if you''re using a barbell. Choose a height that allows you to squat down and gently tap your glutes on the box with your back straight.
Stand with proper form: Stand with your feet shoulder-width apart, toes pointed slightly outward. Engage your core and keep your back neutral. If using a barbell, rack it at shoulder height.
Lower down: Sit back as if going to sit on a chair, bending your knees and lowering your hips towards the box. Keep your core tight and back straight throughout the movement.
Controlled descent: Descend in a controlled manner until your glutes gently touch the box. Don''t plop down.
Pause and press up: Briefly pause at the bottom with your back straight and core engaged. Then, press through your heels to drive yourself back up to the starting position.

Improvements in coordination, balance and endurance, toning of the leg and buttock muscles and an overall increase in bone density eliminating the risk of osteoporosis.', 'https://wger.de/media/exercise-images/977/3124c091-6395-4377-96c5-56048b627ceb.png', null, 'wger', '151434a5-c046-459f-a3a9-c3125075856f', 'CC-BY-SA 4', 'clafal'),
  ('Commando pull-ups', 'pull_h', false, false, true, 'Back', '{"Shoulders","Biceps","Lats","Trapezius"}', '{}', '{"Pull-up bar"}', 'variation of the pull-up exercise, it is performed with a grip of one hand supine and one hand prone, do not twist the torso to get back to the front, the head passes once to one side, once to the other.', null, null, 'wger', 'e872658a-3bac-4d9e-bcf2-15919ebea43a', 'CC-BY-SA 4', 'clafal'),
  ('Incline Bench Reverse Fly', 'push_h', false, false, false, 'Back', '{"Shoulders","Trapezius"}', '{}', '{"Dumbbell","Incline bench"}', 'The incline dumbbell reverse fly is an upper-body exercise targeting the posterior or rear deltoids, as well as the postural muscles of the upper back. Because it targets such small muscles, this exercise is usually performed with light weight for high reps, such as 10-15 reps per set or more.', 'https://wger.de/media/exercise-images/828/2e959dab-f39b-4c7c-9063-eb43064ab5eb.png', null, 'wger', '70c99a4e-3340-4993-a7f1-2d2709dada1a', 'CC-BY-SA 4', 'cshep442'),
  ('Body-Ups', 'isolation', false, false, true, 'Arms', '{"Triceps"}', '{"Shoulders","Abs"}', '{"Bodyweight"}', 'Assume a plank position on the ground. You should be supporting your bodyweight on your toes and forearms, keeping your torso straight. Your forearms should be shoulder-width apart. This will be your starting position.
Pressing your palms firmly into the ground, extend through the elbows to raise your body from the ground. Keep your torso rigid as you perform the movement.
Slowly lower your forearms back to the ground by allowing the elbows to flex.
Repeat as needed.', null, null, 'wger', 'd551f24d-44fe-4761-9448-edf14d627827', 'CC-BY-SA 4', 'cal.zabel'),
  ('Speed Deadlift', 'hinge', false, true, true, 'Legs', '{"Hamstrings","Glutes"}', '{"Quads","Trapezius"}', '{}', 'Deadlift with short (less than one 1min) rest between sets.', null, null, 'wger', 'b1051c3e-78a9-4b73-899c-c700098cf1a8', 'CC-BY-SA 4', 'MrSteele'),
  ('Pullup on fingerboard', 'pull_v', false, false, true, 'Arms', '{"Biceps","Lats"}', '{"Brachialis","Trapezius"}', '{"Bodyweight"}', 'Pullup on a choosen edge of a fingerboard / hangboard', null, null, 'wger', 'a540925e-fe66-47cc-ae28-ecdce408fb6d', 'CC-BY-SA 4', 'marcelbader'),
  ('Glute-Ham Raise', 'squat', false, true, false, 'Legs', '{"Hamstrings"}', '{"Glutes"}', '{"Bench"}', 'Kneel on a glute-ham developer or have a partner hold your ankles. Keeping hips straight, lower your torso toward the floor under control, then curl back up by contracting the hamstrings and glutes.', null, null, 'wger', '537b41a8-870b-4b45-b8a5-e9672c6a359b', 'CC0', 'personal use'),
  ('Easy Continuous Swim (Freestyle)', null, false, false, true, 'Cardio', '{"Shoulders","Lats","Chest"}', '{"Hamstrings","Calves","Glutes","Quads","Abs","Triceps"}', '{}', 'Swim freestyle at a relaxed, steady pace without stopping — think conversation pace, not racing. Focus on smooth, even strokes rather than speed or breathing technique; this is just to get your body moving and your heart rate up.', null, null, 'wger', 'ddf4111d-907d-4d6c-b583-58323b96ca03', 'CC-BY-SA 4', 'Imported from swim plan'),
  ('Lying Dumbbell Row SS Seated Shrug', 'pull_h', false, false, true, 'Back', '{"Lats","Trapezius"}', '{"Biceps"}', '{"Dumbbell"}', 'laying on the stomach on a bench with slight angle', null, null, 'wger', 'dab7400b-e86e-4224-bcea-4a915dc928e0', 'CC-BY-SA 4', 'novadani'),
  ('Biceps with TRX', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Bodyweight"}', 'Grab the handles of the TRX straps, lean your body back, arms and legs extended, with your body positioned in a single straight line. (This is an arm exercise, not an abdominal one.)', 'https://wger.de/media/exercise-images/958/947ac249-475d-44ed-bed3-8dc433374f59.png', null, 'wger', '596b9d2d-0f01-41a0-97e1-1839ffdb824d', 'CC-BY-SA 4', 'clafal'),
  ('TRX Rows', 'pull_h', false, false, true, 'Back', '{"Shoulders","Biceps","Lats"}', '{}', '{"Bodyweight"}', 'This exercise serves as a lead-up to Pull Ups.', 'https://wger.de/media/exercise-images/959/53a5e008-bc31-4ee0-9463-69a858c2ec18.png', null, 'wger', 'e2599e86-d8b0-434e-8a48-aa3c2df7e790', 'CC-BY-SA 4', 'clafal'),
  ('Suspended crossess', null, false, false, false, 'Cardio', '{"Chest"}', '{}', '{"Bodyweight"}', 'Suspension exercise with trx for chest training', 'https://wger.de/media/exercise-images/927/7b392101-9c47-4693-935e-a88b1887eec5.jpg', null, 'wger', 'e0d9e9ef-09ee-4d26-9504-622093810414', 'CC-BY-SA 4', null),
  ('Forearm Plank (Core L1)', 'isolation', false, false, false, 'Abs', '{"Calves"}', '{}', '{"Bodyweight"}', 'Vasco custom forearm plank - foundational anterior core stability exercise. Teaches full-body tension, breath control, and anti-extension. Prerequisite for all advanced core work.', null, null, 'wger', '0c6764f2-fb86-43f1-bd35-04a35f74d5e4', 'CC-BY-SA 4', 'Vasco Custom'),
  ('Step-ups', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings","Calves"}', '{"Bench"}', 'Starting position:

Stand facing a chair.

Steps:

Step up onto the chair.
Step off the chair.
Repeat.', 'https://wger.de/media/exercise-images/981/f9377a7e-eb58-4cca-b805-2d36863aeb03.png', null, 'wger', '9e6dae29-5d03-440a-bdf1-2cb25a5179c2', 'CC-BY-SA 4', null),
  ('Push-up rotations', 'push_h', false, false, true, 'Arms', '{"Chest","Triceps"}', '{"Shoulders","Obliquus externus abdominis"}', '{"Bodyweight"}', 'Starting position:

Get into the starting push-up position, with your hands and toes touching the ground and back, arms and legs straight. To get to this position, you can lie down on your stomach, place your hands facing down next to your head, and lifting your arms up until they are straight.

Steps:

Perform a standard push-up:

1.a Bend arms until chest almost touches the ground, making sure the back is straight.1.b Use your arms to lift yourself back up to starting position.

Rotate your body to the side so that the back is straight, the bottom hand supporting the body is fully extended, and only the bottom hand and foot touch the floor.
Repeat, changing sides at step 2 each time.', null, null, 'wger', 'a9633731-1d86-4b4a-996f-33a1dee0b0e1', 'CC-BY-SA 4', null),
  ('Kneeling kickbacks', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Starting position:

Get down on all fours.

Steps:

Push one foot back until fully extended, concentrating on the gluteus muscles.
Stay for one second, then return to the initial position.
Repeat, alternating feet.', 'https://wger.de/media/exercise-images/990/de20457c-914a-45c9-8cf9-0ad9739759a1.png', null, 'wger', '6ddea666-5a57-4ac0-926f-01f8cfdaa4fd', 'CC-BY-SA 4', null),
  ('Tricep Pushdown on Cable', 'isolation', false, false, false, 'Arms', '{"Triceps"}', '{}', '{"Cable machine"}', 'The cable rope push-down is a popular exercise targeting the triceps muscles. It''s easy to learn and perform, making it a favorite for everyone from beginners to advanced lifters. It is usually performed for moderate to high reps, such as 8-12 reps or more per set, as part of an upper-body or arm-focused workout.', 'https://wger.de/media/exercise-images/805/7a437824-e2cc-46e1-804a-674f0ea31d25.png', null, 'wger', 'ea63d85c-8579-4dda-b99f-c4c8930f9af6', 'CC-BY-SA 4', 'cshep442'),
  ('Straight Bar Cable Curls', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Cable machine"}', 'Standing upright in front of Cable Tower using a straight bar', 'https://wger.de/media/exercise-images/912/e10a034f-6370-4dd6-b1c2-416b27844529.png', null, 'wger', '36274d27-3812-4b8c-80e2-ab59acf82c4d', 'CC-BY-SA 4', 'novadani'),
  ('Mentzer Pulldown', 'pull_v', false, false, false, 'Arms', '{"Biceps"}', '{"Lats"}', '{"Cable machine","Incline bench"}', 'Close grip front facing Pull down, while focusing on Biceps, Increases activation of biceps over the whole range, Avoid activating Lats.', 'https://wger.de/media/exercise-images/1971/729af526-19a0-4d3d-a258-196c7575d139.jpg', null, 'wger', 'c4185277-1d30-4684-9bc0-024ab7f2336a', 'CC-BY-SA 4', 'Mike Mentzer'),
  ('Single-Arm Lat Pulldown', 'pull_v', true, false, true, 'Back', '{"Lats","Trapezius"}', '{"Biceps","Brachialis"}', '{"Cable machine"}', 'Sit at the lat pulldown machine and grab the single handle with a neutral grip. Keep your torso stable, your chest lifted, and your shoulder blades slightly retracted. Start with your arm fully extended overhead, then pull the handle down toward your upper chest following a controlled, slightly diagonal path. Focus on engaging the latissimus dorsi while keeping the shoulder depressed and avoiding any torso rotation. Slowly return to the starting position, maintaining full control throughout the movement.', null, null, 'wger', 'b86fd8df-e726-4998-a7ee-000de0f70bf0', 'CC-BY-SA 4', 'evtimovgeorg'),
  ('Tricep Pull-Down', 'pull_v', false, false, false, 'Arms', '{"Triceps"}', '{"Chest"}', '{"Resistance band"}', 'Secure Band above you.

Stand facing band, with feet hip-width apart.
Bend your knees slightly to engage your core.
Keep your chest up, pin your shoulder blades back, and tuck your elbows tightly to the sides of your torso.
Exhale and pull the band straight down toward your thighs.
Inhale and slowly control the band as you let your arms return upwards to their starting position.', null, null, 'wger', '42cdddc2-970e-445c-a766-f6562bf63069', 'CC-BY-SA 4', 'G. Johnson'),
  ('Posterior Pelvic Tilt', 'isolation', false, false, true, 'Abs', '{"Abs"}', '{"Glutes","Obliquus externus abdominis"}', '{"Bodyweight"}', 'Lie on your back with knees bent, feet flat on the floor. Flatten your lower back against the floor by tilting your pelvis posteriorly, engaging your abs and glutes. Hold 5 seconds, release. This retrains pelvic positioning to counter anterior pelvic tilt.', null, null, 'wger', '0e8fd83f-4e97-4749-b5fd-da9d0e85e97a', 'CC-BY-SA 4', 'Raj'),
  ('Low row', 'pull_h', false, false, true, 'Back', '{"Trapezius"}', '{"Biceps","Lats"}', '{}', 'Based on Low Row Sel. by Technogym. In this version, you use it with two arms.', null, null, 'wger', 'bbcf5019-a57f-4e67-bd44-98cba129a0b7', 'CC-BY-SA 4', 'lbroggi'),
  ('Pulley (low, with triangle)', 'pull_h', false, false, true, 'Back', '{"Biceps","Lats"}', '{"Trapezius"}', '{}', 'This exercise is based on Technogym Pulley Sel. Hold the triangle with both hands and bring the weight towards your belly.', null, null, 'wger', '1bda9167-805e-4c7d-aafc-57cdcf5b6d7d', 'CC-BY-SA 4', 'lbroggi'),
  ('Abductors', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{}', 'Based on Abductors Sel. by Technogym.
Position yourself on the machine and open your legs as much as possible.
Return slowly to the original position.', null, null, 'wger', 'd02f6fe0-8ae3-4251-8f94-a63e38249a55', 'CC-BY-SA 4', 'lbroggi'),
  ('Adductors', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{}', 'Based on Adductor Sel. by Technogym.
Sit on the machine and set the rest position to a comfortable opening angle.
Close your legs.
Gently return to the rest position.', null, null, 'wger', '701d9cee-0797-4177-8556-252de669b56c', 'CC-BY-SA 4', 'lbroggi'),
  ('Adductor Side Plank', 'squat', false, true, false, 'Legs', '{"Hamstrings","Glutes"}', '{}', '{"Bench"}', 'Set up next to a bench in a 90° angle on your side. One leg goes up on the bench with the side of your calf touching it. The other leg goes below the bench. Forearm closer to the ground is at a 90° angle, hand pointing front. Now push off the floor with the forearm closer to the ground, upper side of your body should be completely straight, level with the bench (it''s a side plank after all). Hold that position.', null, null, 'wger', '1c60ade0-1e8c-475b-b2d3-bfdf313987f4', 'CC-BY-SA 4', 'hurr99'),
  ('Bear Walk 2', 'push_h', false, false, true, 'Chest', '{"Shoulders","Calves","Chest","Abs","Serratus anterior","Soleus","Triceps"}', '{"Glutes","Lats","Obliquus externus abdominis","Quads","Trapezius"}', '{"Bodyweight"}', '-Rest your weight on your palms and the balls of your feet, not dissimilar to normal pushup position

-Move by stepping with your R palm and L foot, then your L palm and R foot. Basically, walk like a lumbering bear.

-Move as fast as you can. Measure your reps/sets in either distance (i.e. 40 yards) or time (i.e. 45 seconds)

-Works your Pecs, Deltoids, Triceps, Traps, Lats, Abs and Lower Back, Hip Flexors, Quads, Glutes and Calves', null, null, 'wger', 'b7267f90-8706-442b-b918-507e16092b8e', 'CC-BY-SA 4', 'nate303303'),
  ('One-handed kettlebell curls', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Kettlebell"}', 'Standing with the kettlebell in one hand and bent at the elbow, start from a fully extended position until your hand reaches shoulder height. To perform the movement correctly, try not to push with your back or body.', 'https://wger.de/media/exercise-images/975/41d9267a-99bc-4e94-b1c4-0e39fe7a968f.png', null, 'wger', 'd7d4fc16-08cd-4568-87e7-d9e4e2f77393', 'CC-BY-SA 4', 'clafal'),
  ('Medicine ball booklet crunch', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'Using a medicine ball as an overload will make the exercise heavier.', 'https://wger.de/media/exercise-images/976/94649ea6-bf58-4fd9-90c1-b2ec96ee20cd.png', null, 'wger', '346634cf-3896-4c10-bd66-28fb69d02573', 'CC-BY-SA 4', 'clafal'),
  ('Knee Raises', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{"Pull-up bar"}', 'The 90° leg raise on the bar is a very intense exercise that involves all the abdominal muscles.', 'https://wger.de/media/exercise-images/978/d3ffe51f-7eb8-4cc9-9eae-105847af3005.png', null, 'wger', 'f4991a98-6422-4884-8ad3-43412f91fac1', 'CC-BY-SA 4', 'clafal'),
  ('Barbell Ab Rollout', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis"}', '{}', '{"Barbell"}', 'Place a barbell on the floor at your feet.

Bending at the waist, grip the barbell with a shoulder with overhand grip.

With a slow controlled motion, roll the bar out so that your back is straight.

Roll back up raising your hips and butt as you return to the starting position.', 'https://wger.de/media/exercise-images/41/34b37423-269f-43d4-9d29-d2a90eeaa6b4.png', null, 'wger', 'a6bced3c-72f5-42a3-9438-5569d46f49fd', 'CC-BY-SA 4', 'sevae'),
  ('Elliptical', null, false, false, true, 'Cardio', '{"Glutes","Quads","Trapezius"}', '{"Biceps","Abs","Triceps"}', '{"Bodyweight"}', 'It improves muscle toning, strengthens the leg muscles (quads, glutes, calves), helps vascularisation and increases resistance. The elliptical is also very useful if you aim to lose weight. Teste', null, null, 'wger', '95a300de-2ad8-492e-9364-13766d9e7618', 'CC-BY-SA 4', 'clafal'),
  ('Reverse Nordic Curl', 'squat', false, true, true, 'Legs', '{"Quads"}', '{"Glutes","Abs"}', '{}', 'Natural Leg Extension is alternative to Leg Extension machine with no equipment.', 'https://wger.de/media/exercise-images/909/159222d9-c1e4-46ae-89ee-6a2dfaab978d.png', null, 'wger', '6cbdd70c-0691-4288-b58a-24001384f1b3', 'CC-BY-SA 4', 'karly'),
  ('Leg raises pull up bar', 'pull_v', false, false, true, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis","Quads"}', '{"Pull-up bar"}', 'with a firm grip with both hands on the bar, raise your outstretched legs, until you reach a 90° angle with your torso.', 'https://wger.de/media/exercise-images/979/27097a3a-5749-428d-b94c-6082afe390f6.png', null, 'wger', 'b2025776-2397-4de7-a49e-296321169481', 'CC-BY-SA 4', 'clafal'),
  ('Bent High Pulls', 'push_v', false, false, false, 'Shoulders', '{"Trapezius"}', '{}', '{"Dumbbell"}', 'Bend over slightly while holding two dumbbells. Pull the dumbbells up to your chest, keeping your elbows as high as you can.', 'https://wger.de/media/exercise-images/79/da58dfbf-748a-461b-891e-3d6bc9cc4be2.png', null, 'wger', '01271ea0-088c-4e2b-95ad-876af7127057', 'CC-BY-SA 3', 'lakerbeezel'),
  ('Reverse Clamshell', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bodyweight"}', 'Lie on your side with your hips and knees bent, keeping your knees stacked on top of each other. Keep your feet together at first, then keep your knees touching while lifting your top foot upward. Slowly lower the foot back down with control.

Move only through the hip and avoid rolling your pelvis backward. The movement should be small, controlled, and focused on hip rotation.', null, null, 'wger', 'cf6bf132-fe21-4b70-8f73-006545246f05', 'CC-BY-SA 4', 'TobiasFalk'),
  ('Deadbug', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{}', 'Lie on your back, with your hips and knees bent to 90°. Raise both arms toward the ceiling. Pull your lower back to the floor to eliminate the gap. Start by pressing one leg out, and tapping the heel to the floor. "As you extend one leg, exhale as much as you can, keeping your lower back glued to the floor," Dunham says. When you can’t exhale any more, pull your knee back to the starting position. Make this more difficult by holding weight in your hands, or by lowering opposite arm and leg.', null, null, 'wger', 'd4db2355-4c99-4d80-a179-6aeced7c7fed', 'CC-BY-SA 4', 'Metin'),
  ('Hip Raise, Lying', 'pull_h', false, false, false, 'Back', '{"Glutes"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Lying down on your back, with your feet flat on the floor. Raise your hips up evenly as high as you can and hold for as long as you can.', null, null, 'wger', '541941e0-0fa5-4474-a382-9baf04948f8d', 'CC-BY-SA 4', 'James Mackay'),
  ('Barbell Lunges Walking', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings","Calves"}', '{"Barbell"}', null, null, 'https://wger.de/media/exercise-video/802/85d1d7f8-c3c5-47e8-9b26-56896919e6e7.MOV', 'wger', '072a9fa8-1028-47b3-b958-d8052c6b8661', 'CC-BY-SA 4', null),
  ('Lunges', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Starting position:

Stand with back straight.

Steps:

Take a large step forward with your left leg.
Bring your pelvis down until you almost touch the floor with your right knee.
Bring your pelvis back up.
Return to the starting position by stepping back.
Repeat, switching legs each time.', 'https://wger.de/media/exercise-images/984/5c7ffe68-e7b2-47f3-a22a-f9cc28640432.png', null, 'wger', '3284fd27-5402-4821-9c32-29066d4e2667', 'CC-BY-SA 4', null),
  ('Kick with Board', null, false, false, true, 'Cardio', '{"Glutes","Quads"}', '{"Hamstrings","Calves","Abs"}', '{}', 'Hold a kickboard with both hands, arms extended in front of you, face in the water (lift head forward to breathe when needed). Kick from your hips, not your knees, keeping your legs mostly straight with a slight bend and a steady, compact flutter kick. This builds leg endurance and keeps your body horizontal without needing to worry about your arms.', null, null, 'wger', '57d1a6fc-fc28-43a7-9beb-0e851a47a976', 'CC-BY-SA 4', 'Imported from swim plan'),
  ('Hollow Hold', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis","Abs"}', '{}', '{"Gym mat"}', 'Get on a mat and lie on your back. Contract your abs, stretch your arms and legs and raise them (your head and shoulders are also be raised). Make sure your lower back remains in contact with the mat.', 'https://wger.de/media/exercise-images/297/b10d3341-baa8-49ab-b462-5b3529389aac.png', null, 'wger', 'd059c63d-0a81-48a3-912a-44070c0def2e', 'CC0', 'Behrooz'),
  ('Blaze', null, false, false, true, 'Cardio', '{"Shoulders","Glutes","Chest","Quads"}', '{"Biceps","Hamstrings","Lats","Abs"}', '{"Bench","Dumbbell","Kettlebell"}', 'BLAZE is a full-body HIIT workout. Designed to supercharge your cardio fitness and strength. Delivered in its own purpose-built studio, BLAZE is a unique mix of martial arts, intense cardio and strength training.', null, null, 'wger', '24f988e7-51eb-44f5-92f2-d4e0199c2269', 'CC-BY-SA 4', 'ricwheatley'),
  ('Dumbbells on Scott Machine', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Dumbbell"}', null, null, null, 'wger', 'fe328b2b-cc6d-4f12-a2c6-85ce374217c7', 'CC-BY-SA 3', 'wger.de'),
  ('Chin Up', 'pull_v', false, false, true, 'Back', '{"Biceps","Lats"}', '{"Brachialis","Trapezius"}', '{"Pull-up bar"}', 'The chin-up (also known as a chin or chinup) is a strength training exercise. People frequently do this exercise with the intention of strengthening muscles such as the latissimus dorsi and biceps, which extend the shoulder and flex the elbow, respectively. In this maneuver, the palms are faced towards the body. It is a form of pull-up in which the range of motion is established in relation to a person''s chin.', 'https://wger.de/media/exercise-images/152/6c1a7459-266d-491a-bd50-7cbaea2bc771.png', null, 'wger', '87e6abc5-a701-442a-b4fb-bb2a7598a754', 'CC0', 'BFad07'),
  ('Bulgarian split squats left', 'squat', true, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Stand tall in front of a chair and take a large step. Put the upper part of one of your feet on the chair.
Bend the front knee, balancing with arms until the back knee almost touches the ground.
Push back to the starting position and repeat.', 'https://wger.de/media/exercise-images/988/6283b258-a4d7-4833-84f7-a38987022d3d.png', null, 'wger', '7ce489d2-1948-46de-aa80-277b2ca737aa', 'CC-BY-SA 4', null),
  ('Bulgarian split squats right', 'squat', true, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Stand tall in front of a chair and take a large step. Put the upper part of one of your feet on the chair.
Bend the front knee, balancing with arms until the back knee almost touches the ground.
Push back to the starting position and repeat.', null, null, 'wger', '44afe80f-1ab2-4149-adbf-d8e0ece990ce', 'CC-BY-SA 4', null),
  ('Split squats left', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Starting position:

Stand with your back straight. Take a large step forward with your left leg.

Steps:

Bring your pelvis down until you almost touch the floor with your right knee.
Bring your pelvis back up.
Repeat.', null, null, 'wger', '80d83f98-efe5-4d87-a403-c0feadc8650f', 'CC-BY-SA 4', null),
  ('Split squats right', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Starting position:

Stand with your back straight. Take a large step forward with your right leg.

Steps:

Bring your pelvis down until you almost touch the floor with your left knee.
Bring your pelvis back up.
Repeat.', null, null, 'wger', '1d8599d8-59a5-4faf-a9cf-b81639cbf68b', 'CC-BY-SA 4', null),
  ('Reverse lunges', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings"}', '{"Bodyweight"}', 'Starting position:

Stand straight, feet hip-width apart.

Steps:

Step backward with one leg so it can bend comfortably to a 90 degree angle.
Slowly bend both knees to form 90 degree angles.
Return to the starting position.
Repeat, alternating legs.', 'https://wger.de/media/exercise-images/999/d0931eb3-8db0-4049-bb08-aa4036072056.jfif', null, 'wger', '616f9026-1a1d-4ed8-b068-cfbb81b6a000', 'CC-BY-SA 4', null),
  ('Floor dips', 'isolation', false, false, true, 'Arms', '{"Triceps"}', '{"Shoulders","Chest"}', '{"Bodyweight"}', 'Starting position:

Sit with your arms behind you, supporting your back.Your fingers should point forward.Your knees should be bent, feet together.

Steps:

Raise your hips off the ground, straightening your arms.
Bend your elbows, bringing your hips down.
Straighten your arms, returning to the previous position.
Repeat steps 2 and 3.

Notes:

The exercise''s difficulty depends on how high you bring your hips.', 'https://wger.de/media/exercise-images/1000/553266a8-a972-48c5-a014-b12afac66f65.png', null, 'wger', 'cf79d9fb-ffce-4648-a64f-27e4274e4c20', 'CC-BY-SA 4', null),
  ('High plank', 'push_h', false, false, true, 'Chest', '{"Abs"}', '{"Shoulders","Obliquus externus abdominis","Triceps"}', '{"Bodyweight"}', 'Starting position:

Get into the high plank position:your hands and toes should be touching the ground, your back, arms and legs should be straight.To get to this position, you can lie down on your stomach, place your hands facing down next to your head, and lifting your arms up until they are straight.

Steps:

Maintain the starting position for the entire duration of the exercise.', null, null, 'wger', 'b2b40a54-e42b-49ec-97da-4c929ae41d42', 'CC-BY-SA 4', null),
  ('Facepull', 'push_v', false, false, false, 'Shoulders', '{"Trapezius"}', '{}', '{"Cable machine"}', 'Attach a rope to a pulley station set at about chest level.

Step back so you''re supporting the weight with arms completely outstretched and assume a staggered (one foot forward) stance. Bend the knees slightly for a stable base.

Retract the scapulae (squeeze your partner''s finger with your shoulder blades) and pull the center of the rope slightly up towards the face. A good cue is to think about pulling the ends of the rope apart, not just pulling back.

As you near your face, externally rotate so your knuckles are facing the ceiling.

Hold for one second at the top position and slowly lower.', null, 'https://wger.de/media/exercise-video/222/245a824b-cd39-45f2-b251-2c0b7efead0d.MOV', 'wger', 'd7a418d4-d0cb-4f85-8a7c-1e9d97152cbd', 'CC-BY-SA 4', 'abeworld'),
  ('Kettlebell deadlifts', 'pull_h', false, false, true, 'Back', '{"Hamstrings","Glutes"}', '{"Quads","Trapezius"}', '{"Kettlebell"}', 'Starting position:

Stand hip-width apart, with your kettlebell centered between your ankles. Your back should be straight, your head facing forward.

Steps:

Hinge at the hips and slightly bend at the knees to put your hands on the kettlebell handles. Your back should be straight as you perform the movement.
Grab the kettlebell handles, with your hands pushing in opposite directions as if to pull the handle apart.
While contacting your abs and glutes, stand straight up.
Hinge at the hips again to bring the kettlebell back down, similarly to step 1.
Repeat from step 3.

Tips:

Be sure you''re performing the movements correctly, as doing otherwise can lead to injury. For example, do not squat instead of hinging at the hips, do not round your back while reaching for the kettlebell, and do not lean back while standing up.', 'https://wger.de/media/exercise-images/1003/772d6e47-3865-4944-9255-7435d0b06782.png', null, 'wger', '9b5f8c6e-2436-4ded-aea9-8c698b0c8768', 'CC-BY-SA 4', null),
  ('Alternating bicep curls', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{"Brachialis"}', '{"Dumbbell"}', 'Starting position:

Start standing up with dumbbells in each hand, your back straight and feet hip-width apart. Your arms should be relaxed, pointing down. Your knees should be slightly bent, your abs contracted, and your shoulders down.

Steps:

Bend one arm at the elbow, bringing the dumbbell up to your shoulder. Your upper arm should remain motionless during this movement.
Bring the dumbbell back down until your arm is in its original relaxed position.
Repeat, switching arms.', 'https://wger.de/media/exercise-images/1012/8270fdb8-28f1-4eff-b410-af8642085b3f.png', null, 'wger', 'a136959c-b0c8-49d3-99b9-0a5f41abf00e', 'CC-BY-SA 4', null),
  ('Cable Woodchoppers', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis"}', '{}', '{"Cable machine"}', 'Set cable pulley slightly lower than chest height. Keep body facing forward with hips stable. Grab the pulley handle, fully extend your arms and bring your arms forward and across your body. Hold for 1 second at the end of the movement and slowly return to starting position.', null, null, 'wger', 'c867836d-2929-4977-b23c-014bc21ec08d', 'CC-BY-SA 3', 'robhoyt'),
  ('Hercules Pillars', 'isolation', false, false, true, 'Arms', '{"Biceps","Brachialis","Triceps"}', '{"Shoulders"}', '{"Cable machine"}', 'Grab two cables stand in the middle so both have tension and hold', null, null, 'wger', '8381f40c-3168-4d98-af60-6a89800dd308', 'CC-BY-SA 3', 'GrosseHund'),
  ('Reverse EZ Bar Cable Curls', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"Cable machine","SZ-Bar"}', 'Standing in front of cable tower using a SZ Bar', null, null, 'wger', '960697af-9a0e-4bfd-a8ba-989718b6b5c7', 'CC-BY-SA 4', 'novadani'),
  ('Single-arm cable pushdown', 'isolation', true, false, false, 'Arms', '{"Triceps"}', '{"Abs"}', '{"Cable machine"}', 'Single-arm cable pushdown is a unilateral isolation exercise that targets the triceps brachii. By working one arm at a time, it helps correct strength imbalances between sides while also engaging the core for stability.
Starting position:
Stand facing the cable machine with your feet shoulder-width apart. Attach a single handle to the high pulley. Grab the handle with one hand using an overhand grip (pronated), with your elbow bent at approximately 90° and tucked close to your body. Keep your core braced and your back straight.
Execution:
Push the handle downward in a controlled motion by extending your elbow until your arm is fully extended. Hold the contraction for 1 second at the bottom, then slowly return to the starting position.', null, null, 'wger', '83af8d94-319b-456b-92d8-75cec821a195', 'CC-BY-SA 4', 'evtimovgeorg'),
  ('Machine Leg Flexion', 'squat', false, true, false, 'Legs', '{"Hamstrings"}', '{}', '{"Cable machine"}', 'Adjust the back seat or pad so your knees align with the side pivot axis.Place the lower roller pad against your lower calves, just above the back of your ankles.Lower the upper thigh restraint pad so your legs stay firmly on the seat.Pick a light weight on the stack with the pin.', 'https://wger.de/media/exercise-images/2495/5978ac7d-f4d4-4807-87e6-03e457485191.png', null, 'wger', 'c690034b-400c-4da8-8c71-37afac81ec3f', 'CC-BY-SA 4', 'Me'),
  ('Bird Dog (Core L1)', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{}', '{"Bodyweight"}', 'Vasco custom bird dog - foundational contralateral limb coordination and lumbar stability. Teaches hip dissociation from spine, glute activation, and scapular control.', null, null, 'wger', '6d45afed-05c4-42a2-994b-5ef62a9d0aed', 'CC-BY-SA 4', 'Vasco Custom'),
  ('Nordic Curl', 'squat', false, true, false, 'Legs', '{"Hamstrings"}', '{"Glutes"}', '{}', 'The Nordic hamstring curl is one of the best lower-body exercises to build posterior leg strength, improve knee health, and prevent injury.', null, null, 'wger', '9b0f7101-b78a-4c47-b680-fbef15469a8a', 'CC-BY-SA 4', 'karly'),
  ('Reverse Preacher Curl (Close Grip)', 'isolation', false, false, false, 'Arms', '{"Biceps"}', '{}', '{"SZ-Bar"}', 'Sitting reverse on a Biceps Bench with a close grip', null, null, 'wger', 'edc44b1a-35d7-4c37-ab20-05842fb40576', 'CC-BY-SA 4', 'novadani'),
  ('Smith Machine Slight Incline Press', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{}', '* Execution * Start position:

Unrack the bar and hold it above your upper chest with arms fully extended.
Keep your shoulder blades retracted and pressed into the bench.
Lowering phase (eccentric):
Slowly bring the bar down to just below your collarbone or upper chest.
Maintain control — don’t bounce the bar.
Pressing phase (concentric):
Push the bar upward in a straight line until your arms are fully extended.
Focus on squeezing your upper chest at the top.
Lock and repeat:
Complete your reps, then safely rack the bar back into the hooks.', 'https://wger.de/media/exercise-images/925/67dbb1c9-b378-46f9-adb6-1f55b3d3007a.png', null, 'wger', 'ef2df6a2-41df-4a25-b2e0-4808dc2c3305', 'CC-BY-SA 4', 'novadani'),
  ('Chest Press', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{}', 'Adjust the seat height so that the grips are parallel to your chest.
Use your legs to push the foot forward pedal.
Bring the handles to the start position.
Keep your back in contact with the back pad, press outwards.
Press the handles away from your chest and exhale.
Allow the handles to come in gently until they reach your chest.
Allow the handles to return to your chest as you inhale.', 'https://wger.de/media/exercise-images/129/b263c968-e067-4750-916a-d8758a7df23e.webp', null, 'wger', '5c414175-fe72-455a-ba8f-a0575cf792bd', 'CC-BY-SA 3', 'wger.de'),
  ('Cross-Bench Dumbbell Pullovers', 'push_h', false, false, true, 'Chest', '{"Lats","Chest","Serratus anterior"}', '{}', '{"Dumbbell"}', 'Grasp a moderately weighted dumbbell so your palms are flat against the underside of the top plates and your thumbs are around the bar. Lie on your back across a flat bench so only your upper back and shoulders are in contact with the bench. Your feet should be set about shoulder-width apart and your head should hang slightly downward. With the dumbbell supported at arm''s length directly about your chest, bend your arms about 15 degrees and keep them bent throughout the movement. Slowly lower the dumbbell backward and downward in a semicircle arc to as low a position as is comfortably possible. Raise it slowly back along the same arc to the starting point, and repeat for the required number of repetitions.', 'https://wger.de/media/exercise-images/161/b9b1803e-2817-40bf-8ac7-e398ca86d8b4.png', null, 'wger', '6e00afb6-272d-44a2-8ae3-e7fa41b50f06', 'CC-BY-SA 3', 'powerade69'),
  ('Cycling', null, false, false, true, 'Cardio', '{"Obliquus externus abdominis","Trapezius"}', '{"Hamstrings","Brachialis","Glutes","Lats","Quads"}', '{"Bodyweight"}', 'Cycling, also called bicycling or biking, is the use of bicycles for transport, recreation, exercise or sport. People engaged in cycling are referred to as cyclists, bicyclists, or bikers. Apart from two-wheeled bicycles, cycling also includes the riding of unicycles, tricycles, quadracycles, recumbent and similar human-powered vehicles.', null, null, 'wger', '8dedde58-a5dc-4a23-ad20-fd7cf524f8b5', 'CC0', 'BFad07'),
  ('Machine chest fly', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{}', '{}', 'seated machine, straight back, slow exercise', 'https://wger.de/media/exercise-images/926/ae9deb5d-a1e9-4c30-b1e3-c128ba5d4969.png', null, 'wger', '1e827ef8-0a01-4b26-9e26-eff9d200acca', 'CC-BY-SA 4', 'novadani'),
  ('Hyperextensions', 'pull_h', false, false, false, 'Back', '{"Trapezius"}', '{}', '{}', 'Lie on the hyperextension pillow with your navel at the front edge, allowing your upper body to hang freely. Tighten all your back muscles and raise your torso until you''re horizontal, but no higher. Lower yourself slowly, maintaining a steady flow of muscles.', 'https://wger.de/media/exercise-images/128/Hyperextensions-1.png', null, 'wger', '37f6bd56-815a-4975-99af-05e749fae4b2', 'CC-BY-SA 3', 'wger.de'),
  ('High Knee Jumps', null, false, false, true, 'Cardio', '{"Hamstrings","Calves","Quads","Soleus"}', '{"Obliquus externus abdominis","Abs","Serratus anterior"}', '{}', 'Start with legs slightly wider than shoulder width
Drop into a bodyweight squat
As you hit the bottom of the squat, explode upwards into a jump while simultaneously tucking your knees into your chest midflight. Remain tucked until the apex of your jump.
Land on both feet, making sure your knees are not locked so as to avoid excessive strain upon your joints. Collect yourself into the next rep as quickly but under control as possible.', 'https://wger.de/media/exercise-images/285/4141e8b2-d9f2-4597-8ef0-7768127fd0ec.png', null, 'wger', '3edbb63e-f326-4bd0-8af3-2d5deabb864f', 'CC-BY-SA 4', 'nate303303'),
  ('Bus Drivers', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{}', 'Sitting with a Weight Plate, used as wheel, in both hands; raised slightly below eye level', 'https://wger.de/media/exercise-images/915/fe8ebece-dff8-4700-b84c-9110e2e074f5.png', null, 'wger', '3d85bdce-e1a9-48a2-b14d-8032820ebf25', 'CC-BY-SA 4', 'novadani'),
  ('Hip Thrust', 'hinge', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Barbell","Bench"}', 'The bar should go directly on your upper thigh, directly below your crotch. Your feet should be directly under your knees. Push your hips up so that you form a straight line from your knees to your shoulders. Use a pad for comfort.', null, 'https://wger.de/media/exercise-video/294/45bacf4b-1bb6-4d47-8bd1-9f00eddd4019.MOV', 'wger', '19a289c0-33af-4055-bb34-3570c2975d3d', 'CC-BY-SA 4', 'Bret Contreras'),
  ('High Pull', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{"Glutes"}', '{}', 'Use a light barbell, perform explosive lift up starting from underneath knee cap level. Lift/raise explosively using hips, at shoulder level. Tempo: 2111', null, null, 'wger', 'b526b17b-408d-4da2-8940-ceaf9dae9d93', 'CC-BY-SA 3', 'Mahoney'),
  ('Clamshell to Reverse Clamshell', 'squat', false, true, false, 'Legs', '{"Glutes"}', '{}', '{"Bodyweight"}', 'Lie on your side with your hips and knees bent, keeping your legs stacked. Lift your top knee into a clamshell position and keep the leg elevated throughout the movement. From there, alternate between opening the knee upward and lifting the foot upward, moving through hip external and internal rotation.

Keep the movement slow and controlled. Do not let the top leg rest on the bottom leg between repetitions.', null, null, 'wger', 'f77b7cc6-e163-4f92-afa8-5ec431f32588', 'CC-BY-SA 4', 'TobiasFalk'),
  ('Bobbing Exhale Drill', null, false, false, false, 'Cardio', '{"Abs"}', '{}', '{}', 'Stand in chest-deep water. Take a breath, submerge your face fully, and exhale slowly and completely through your nose and/or mouth the whole time you''re underwater — a gentle humming sound can help keep the exhale steady and controlled. Once you''re empty of air, lift your head, take a fresh breath, and go back under. Repeat continuously. The goal is training your body that all your exhaling happens underwater, so all you need to do at the surface is inhale.', null, null, 'wger', 'c4b2ed05-38d5-47fc-9ad1-c23f09fddd61', 'CC-BY-SA 4', 'Imported from swim plan'),
  ('Muscle up', 'pull_h', false, false, true, 'Back', '{"Biceps","Lats"}', '{"Shoulders","Triceps"}', '{"Pull-up bar"}', 'The body is then explosively pulled up by the arms in a radial pull-up, with greater speed than a regular pull-up. When the bar approaches the upper chest, the wrists are swiftly flexed to bring the forearms above the bar. The body is leaned forward, and the elbows are straightened by activating the triceps. The routine is considered complete when the bar is at the level of the waist and the arms are fully straight.

To dismount, the arms are bent at the elbow, and the body is lowered to the floor, and the exercise can be repeated.

As a relatively advanced exercise, muscle-ups are typically first learned with an assistive kip. The legs swing (kip) up and provide momentum to assist in the explosive upward force needed to ascend above the bar. More advanced athletes can perform a strict variation of the muscle-up which is done slowly, without any kip. This variation begins with a still dead hang and uses isometric muscle contraction to ascend above the bar in a slow, controlled fashion.', null, null, 'wger', '0027b172-a83e-4f79-af47-483302a22c02', 'CC-BY-SA 4', 'arson'),
  ('Side plank right', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{"Bodyweight"}', 'Starting position:

Lie down on your side, with your bottom elbow at a right angle, arm sticking out. Lift your pelvis off the floor by lifting your bottom shoulder up, keeping the forearm on the floor; your head, pelvis, and feet should be in a straight line.

Steps:

Hold this position.', null, null, 'wger', '5e2761cf-839e-435e-bedb-35e132dcb5ce', 'CC-BY-SA 4', null),
  ('Reverse Curl', 'isolation', false, false, false, 'Arms', '{"Biceps","Brachialis"}', '{}', '{"Barbell","Dumbbell"}', 'The reverse-grip barbell curl is a variation on the biceps curl where the palms face downward. The switch from an underhand to an overhand grip brings the forearm and brachialis muscles more into the exercise.', null, null, 'wger', '2cd5e3c6-a8c0-456a-ab47-5e7b3a435407', 'CC0', 'BFad07'),
  ('Roman Chair Crunch', 'isolation', false, false, false, 'Abs', '{"Abs"}', '{"Obliquus externus abdominis"}', '{}', 'Crunches on roman chair. Keep your torso straight, abs tight, and don''t come up all the way vertical or lie flat to keep constant tension on your abs.', null, null, 'wger', 'af2f774c-296c-4d14-8e4a-fad77175ae37', 'CC-BY-SA 3', 'MaddieBeasley'),
  ('Pistol squats right', 'squat', true, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings","Calves","Abs"}', '{"Bodyweight"}', 'Stand on one leg, with your other leg straight and slightly forward.
Bend one knee slowly, descending into a squat and keeping your back and your other leg straight.
Slowly raise yourself from the squat, straightening the bent knee and keeping the other leg straight.
Repeat.', null, null, 'wger', 'ec9dca8d-1456-430a-abed-70b8bab4779a', 'CC-BY-SA 4', null),
  ('Calf raises, right leg', 'isolation', false, true, false, 'Calves', '{"Calves"}', '{"Soleus"}', '{"Bodyweight"}', 'Stand on the floor or on the edge of a step to increase the range of movement.
Raise one foot.
Lift your heel until you''re standing on your toes.
(variable) Stay in this position for three seconds
Slowly lower your foot until you almost touch the ground with your heel - don''t slam your foot!', null, null, 'wger', '04ba9a37-4725-43f0-a0b6-767cdab9a79e', 'CC-BY-SA 4', null),
  ('Cable Cross-over', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Shoulders"}', '{"Cable machine"}', 'Begin with cables at about shoulder height, one in each hand. Take a step forward so that one foot is in front of the other, for stability, and so that there is tension on the cables. Bring hands together in front of you. Try to make your hands overlap (so that the cables cross) a few inches.', 'https://wger.de/media/exercise-images/71/Cable-crossover-2.png', null, 'wger', 'b16e3e5d-8401-4d2b-919c-15b536f9ec5e', 'CC-BY-SA 3', 'wger.de'),
  ('Long-Pulley, Narrow', 'pull_h', false, false, true, 'Back', '{"Lats"}', '{"Biceps","Brachialis"}', '{"Cable machine"}', 'The exercise is the same as the regular long pulley, but with a narrow grip:

Sit down, put your feet on the supporting points and grab the bar with a wide grip. Pull the weight with a rapid movement towards your belly button, not upper. Keep your arms and elbows during the movement close to your body. Your shoulders are pulled together. Let the weight slowly down till your arms are completely stretched.', null, null, 'wger', '77c98954-b50d-46f0-9912-3981f856d5a6', 'CC-BY-SA 3', 'wger.de'),
  ('Overhand Cable Curl', 'isolation', false, false, false, 'Abs', '{"Biceps"}', '{}', '{"Cable machine"}', 'Hands at shoulder height, curl arms in toward head, then back out.', null, null, 'wger', 'c7058ff8-ca3b-4822-abdb-6341ce37c4d1', 'CC-BY-SA 3', 'ThisGirl0819'),
  ('Straight Bar Cable Front Raise', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Cable machine","SZ-Bar"}', 'Back to cable tower, cable between legs, SZ Bar', null, null, 'wger', 'ca16aa3c-9b43-4d81-ae60-1e225163b767', 'CC-BY-SA 4', 'novadani'),
  ('Rope Pullover/row', 'pull_h', false, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine","Incline bench"}', 'Set up bench in front of cable row machine. Lean over bench to do a row/pullover with rope that targets lats. See picture.', 'https://wger.de/media/exercise-images/1634/9a4704d3-1b25-43e3-b244-3885f4d3db87.png', null, 'wger', '148f2ffc-05e2-486b-874f-2a401337a1c6', 'CC-BY-SA 4', 'Rottekongen'),
  ('Single arm row', 'pull_h', true, false, false, 'Back', '{"Lats"}', '{}', '{"Cable machine","Incline bench"}', 'Sitting on the ground, use a high cable in a single grip, to do lat pulldowns with a focus on a long stretch in the lats.', 'https://wger.de/media/exercise-images/1637/a1fbe83a-a3e5-49f6-a2c2-5d5b533c2be8.png', null, 'wger', '81dd44b3-67b3-4198-9e57-c2a80b3c4102', 'CC-BY-SA 4', 'Rottekongen'),
  ('Long-Pulley (low Row)', 'pull_h', false, false, true, 'Back', '{"Lats"}', '{"Biceps","Brachialis"}', '{"Cable machine"}', 'Sit down, put your feet on the supporting points and grab the bar with a wide grip. Pull the weight with a rapid movement towards your belly button, not upper. Keep your arms and elbows during the movement close to your body. Your shoulders are pulled together. Let the weight slowly down till your arms are completely stretched.', 'https://wger.de/media/exercise-images/143/Cable-seated-rows-2.png', null, 'wger', 'a7e6c20a-6ddc-4401-9935-ace2d02e3995', 'CC-BY-SA 3', 'wger.de'),
  ('Wall Push-ups (Vasco L1)', 'push_h', false, false, true, 'Chest', '{"Chest"}', '{"Shoulders","Obliquus externus abdominis"}', '{"Bodyweight"}', 'Vasco custom beginner wall push-up for zero-equipment home training. Part of 7-day Push/Pull/Core/Lower/Full/Recovery/Rest periodization. 6:30 AM wake, 1hr sessions. Stoic discipline focus.', null, null, 'wger', '37895cdd-aa94-43b5-8b76-4494b7ffeac2', 'CC-BY-SA 4', 'Vasco Custom'),
  ('Side Plank (Core L1)', 'isolation', false, false, true, 'Abs', '{"Shoulders","Lats","Chest"}', '{"Biceps","Brachialis","Obliquus externus abdominis"}', '{"Bodyweight"}', 'Vasco custom side plank - foundational lateral core stability. Targets obliques, QL, and hip abductors. Essential for spinal stability and rotational control.', null, null, 'wger', '2caf3474-9855-4d0b-a50f-dbc08772b151', 'CC-BY-SA 4', 'Vasco Custom'),
  ('Barbell Clean and press', 'push_v', false, false, false, 'Shoulders', '{"Shoulders","Chest"}', '{}', '{"Dumbbell"}', 'This exercise involves lifting a barbell from the ground to the shoulders, then pressing it overhead. It is a compound movement that targets multiple muscle groups, including the legs, back, shoulders, and arms. It is often used in strength and conditioning programs to improve overall power and athleticism.', 'https://wger.de/media/exercise-images/1638/046c09b0-c35d-48d0-a552-39dd49f956d2.webp', null, 'wger', 'e9e7372c-b5c1-45d9-ae5c-b1aa0fc2e2ce', 'CC-BY-SA 4', 'Rottekongen'),
  ('Smith Press', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Incline bench"}', 'Sitting almost 90 degree angle, smith machine', 'https://wger.de/media/exercise-images/916/9bf7555a-fec6-43a9-b343-aae496744e5e.png', null, 'wger', 'cbf4cf16-f188-4a60-a223-aa50b163f4b7', 'CC-BY-SA 4', 'novadani'),
  ('Isometric Wipers', 'push_h', false, false, false, 'Chest', '{"Chest"}', '{"Abs"}', '{"Bodyweight"}', 'Assume push-up position, with hands slightly wider than shoulder width.

Shift body weight as far as possible to one side, allowing the elbow on that side to flex.

Reverse the motion, moving completely over to the other side.

Return to the starting position, and repeat for the desired number of repetitions.', null, null, 'wger', '2f5032de-df6d-406b-b709-9223ef5c3e24', 'CC-BY-SA 4', 'cal.zabel'),
  ('Jumping Jacks', 'squat', false, true, false, 'Legs', '{"Quads"}', '{}', '{}', 'A jumping jack or star jump, also called side-straddle hop in the US military, is a physical jumping exercise performed by jumping to a position with the legs spread wide and the hands going overhead, sometimes in a clap, and then returning to a position with the feet together and the arms at the sides', 'https://wger.de/media/exercise-images/320/6c9124b6-3551-47a8-9c22-20141c8b9c53.png', null, 'wger', '4d255f25-f199-401a-bc81-7ffab1d0ed24', 'CC-BY-SA 4', 'student1234'),
  ('Landmine press', 'push_v', false, false, true, 'Shoulders', '{"Shoulders"}', '{"Chest","Triceps"}', '{"Barbell"}', null, null, null, 'wger', '91c47c8b-6290-4885-8921-df9aa7958c00', 'CC-BY-SA 4', 'Torsten Linnecke'),
  ('Quadriped Arm and Leg Raise', 'pull_h', false, false, true, 'Back', '{"Shoulders","Glutes","Serratus anterior","Trapezius"}', '{"Lats"}', '{"Bodyweight"}', 'In this exercise, the back muscles and the muscles of the back of the leg and back of the arm are activated by lifting the crossed arm and leg at the same time in the crawling position. It also improves balance and proprioception. The movement is done symmetrically.

Get into a crawling posture.2. Draw your abdomen in, then raise your right leg and left arm.3. You should keep your abdomen in for 8 seconds.4. After 8 seconds, slowly lower your arm and leg.5. Then release your muscle.', 'https://wger.de/media/exercise-images/957/0fd94587-6021-4763-856e-7227f5fcba2a.png', null, 'wger', '80c167b9-3749-48a1-8686-fc2163a1e7fb', 'CC-BY-SA 4', 'utkb'),
  ('Prone Scapular Retraction - Arms at Side', 'pull_h', false, false, false, 'Back', '{"Trapezius"}', '{}', '{}', 'Lying on stomach with head on towel.

Stretch arms straight out to your sides.

Slowly lift your arms, pulling your shoulderblades together, hold for 3 seconds.', null, null, 'wger', '9cb69afc-7a44-4a22-b9a9-7bde8aca5b11', 'CC-BY-SA 4', 'donaddon'),
  ('Pike Push Ups', 'isolation', false, false, false, 'Arms', '{"Chest"}', '{"Triceps"}', '{"Bodyweight"}', 'Push Up performed from a pike position (optional to have feet elevated).', 'https://wger.de/media/exercise-images/454/447f3c17-405f-46e0-b138-65c2a8caaab0.png', null, 'wger', '3b96a05b-9705-48da-b43e-6e098234bb35', 'CC-BY-SA 4', 'Nash'),
  ('Seated Dumbbell Side Lateral', 'push_v', false, false, false, 'Shoulders', '{"Shoulders"}', '{}', '{"Dumbbell"}', 'seated slightly leaned forward at beginning of exercise', null, null, 'wger', '6d010eae-2e36-4ec6-b191-c0373f237bb4', 'CC-BY-SA 4', 'novadani'),
  ('T-Bar row', 'pull_h', false, false, false, 'Back', '{"Lats","Trapezius"}', '{}', '{"Barbell"}', 'bent over with triangle grip, slightly bent knees', null, null, 'wger', '1eeccede-29c5-4f38-9ba7-d77c7c47993d', 'CC-BY-SA 4', 'novadani'),
  ('Dumbbell Bent Over Face Pull', 'pull_h', false, false, true, 'Back', '{"Shoulders","Lats"}', '{"Trapezius"}', '{"Dumbbell"}', 'This exercise involves using dumbbells to perform a bent over face pull, which targets the upper back and shoulders. The movement involves pulling the weights towards the face while keeping the elbows high and squeezing the shoulder blades together.', 'https://wger.de/media/exercise-images/1639/8927346e-f5ca-4795-bdf1-5ac9309401e7.webp', null, 'wger', '51ab6376-eb3e-42dc-ad48-46166c94adac', 'CC-BY-SA 4', 'AlucardEvil40'),
  ('Wall-Hold Rotation', null, false, false, false, 'Cardio', '{"Obliquus externus abdominis"}', '{"Abs"}', '{}', 'Hold the pool wall or edge with one hand, body horizontal at the surface, legs kicking gently behind you. Keep your face in the water, exhaling continuously, then rotate your head to the side — not lifting it up — so one goggle stays in the water while the other clears the surface. Take a quick breath, then rotate your face back down to neutral. This isolates the head-rotation motion without any arm strokes to think about.', null, null, 'wger', '9a5d36b8-7fa5-4705-8e9b-fafa211a13d6', 'CC-BY-SA 4', 'Imported from swim plan'),
  ('Turkish Get-Up', 'isolation', false, false, true, 'Abs', '{"Shoulders","Glutes","Obliquus externus abdominis","Serratus anterior"}', '{}', '{"Dumbbell"}', 'Starting on back, move to the standing position with dumbbell in one hand. Switch hands between reps.', null, null, 'wger', '309bfd2b-1af4-49db-b64b-d7d7c7dd39bb', 'CC-BY-SA 4', 'dookie1481'),
  ('Weighted Step-ups', 'squat', false, true, true, 'Legs', '{"Glutes","Quads"}', '{"Hamstrings","Calves"}', '{}', 'box step ups w/ barbell and 45''s on each side', null, null, 'wger', '591992cb-48ee-4b39-b790-e05b4a2c11e3', 'CC0', 'jigglychipmunk'),
  ('Dumbbell Hang Power Cleans', 'pull_h', false, false, true, 'Back', '{"Hamstrings","Glutes"}', '{"Calves","Quads","Trapezius"}', '{"Dumbbell"}', 'On your feet, stand tall with your dumbbells, holding them at your sides. Hinge at the hips to lower them to your knees (picture 1). Stand back up with a slight jump, using the momentum to pull the dumbbells up on to your shoulders (picture 2). Stand up straight, then lower under control to your sides and repeat. Keep this fast and explosive; if your heart rate doesn’t hit the roof, you’re doing them wrong.', 'https://wger.de/media/exercise-images/1087/d85f4e02-b20c-457c-bdfb-0b00e2d14150.jpg', null, 'wger', 'f0f53b8e-0136-4195-baf3-781903651359', 'CC-BY-SA 4', 'philip'),
  ('Dumbbell sumo deadlift', 'hinge', false, true, true, 'Legs', '{"Hamstrings","Glutes"}', '{"Quads","Trapezius"}', '{"Dumbbell"}', 'Lower your dumbbell to the ground between your legs. Assume a wide stance and with a straight back squat down. With the dumbbell standing upright, grip it by the top of the ‘head’ (picture 1).Keeping your chest up and core braced, push the floor away, driving back upwards to a standing position (picture 2). Repeat. If you can easily achieve 20-30 reps, use two dumbbells.', 'https://wger.de/media/exercise-images/1088/9f66b288-ce8f-4154-ba80-78fee267263c.jpg', null, 'wger', '0c30c543-e2cc-499b-bc31-8c28db445ed2', 'CC-BY-SA 4', 'philip'),
  ('Trunk Rotation With Cable', 'isolation', false, false, false, 'Abs', '{"Obliquus externus abdominis"}', '{"Lats"}', '{"Cable machine"}', 'Seated trunk rotation with cable', null, null, 'wger', '90e9f590-7d68-4afb-9f95-8429246ea4aa', 'CC-BY-SA 4', 'Robertcoop')
on conflict (name) do update set
  category          = excluded.category,
  primary_muscles   = excluded.primary_muscles,
  secondary_muscles = excluded.secondary_muscles,
  equipment         = excluded.equipment,
  description       = excluded.description,
  image_url         = excluded.image_url,
  video_url         = excluded.video_url,
  source            = excluded.source,
  source_id         = excluded.source_id,
  license           = excluded.license,
  license_author    = excluded.license_author;
